### ISSUE TITLE
Authentication Delegate

### ISSUE THREAD

**Issue by Vortec4800** [parse-community/Parse-Swift#105]
I'm in the process of writing some custom authentication providers for an internal system we have, using the existing ParseLDAP and other 3rd party classes that already exist as examples. We have this working on the Objective-C SDK, but I have a couple questions about the Swift SDK.

The ObjC SDK has an Authentication Delegate with a method with the siguature `public func restoreAuthentication(withAuthData authData: [String: String]?) -> Bool` which gets called on launch to recreate any state that needs to be done. For example, we use this time to recreate the oAuthSwift client with our token details, and refresh the token if necessary.

I don't see a similar system for this in the Swift SDK. How does auth restoration from serialized data on launch work in the SDK? I can potentially send in a PR if it's something that needs to be added.

**Comment by cbaker6** [comment]
> I don't see a similar system for this in the Swift SDK. How does auth restoration from serialized data on launch work in the SDK? I can potentially send in a PR if it's something that needs to be added.

Good catch, it's currently missing. Can you open a PR? I'll suggest updates if needed

**Comment by Vortec4800** [comment]
Okay, I'll dig in and see what I can do, and send it your way to check out. If I have any questions I'll post them here.

**Comment by cbaker6** [comment]
Close due to https://github.com/parse-community/Parse-Swift/pull/107#issuecomment-839929321
