### ISSUE TITLE
ParseInstallation.current is always nil after ParseUser.logout

### ISSUE THREAD

**Issue by funkenstrahlen** [parse-community/Parse-Swift#110]
When `ParseUser.logout` is called it also clears the current ParseInstallation by calling `ParseInstallation.deleteCurrentContainerFromKeychain`. This is expected.

https://github.com/parse-community/Parse-Swift/blob/f3f22444e7b15fd2d248bfb4fd1244edb76ed748/Sources/ParseSwift/Objects/ParseUser.swift#L80-L84

https://github.com/parse-community/Parse-Swift/blob/f3f22444e7b15fd2d248bfb4fd1244edb76ed748/Sources/ParseSwift/Objects/ParseInstallation.swift#L185-L190

Afterwards `ParseInstallation.current` always returns nil.

Expected: A new `ParseInstallation` is created when `ParseInstallation.currentInstallationContainer.currentInstallation` is nil.

I think this could be the right place to create a new installation when its missing:

https://github.com/parse-community/Parse-Swift/blob/f3f22444e7b15fd2d248bfb4fd1244edb76ed748/Sources/ParseSwift/Objects/ParseInstallation.swift#L136-L142

I currently see no way to create a new `ParseInstallation` object from outside the framework. The only place in code I found which actively sets a new installation is `ParseInstallation.updateKeychainIfNeeded`. This only gets called on `fetch`, `save` or similar requests. However I can not call `fetch` or `save` when `ParseInstallation.current` is nil.

**Comment by funkenstrahlen** [comment]
I am happy to work on a PR to handle this issue. However I'd like to discuss the correct way to fix this before as I am not very familiar with the codebase yet.

**Comment by cbaker6** [comment]
Installation is currently created when you initialize the SDK:

https://github.com/parse-community/Parse-Swift/blob/702422287d84c765d6366f9543dbdc4730ff7d8b/Sources/ParseSwift/Parse.swift#L68-L71

Which ends up calling: https://github.com/parse-community/Parse-Swift/blob/702422287d84c765d6366f9543dbdc4730ff7d8b/Sources/ParseSwift/Internal/BaseParseInstallation.swift#L28-L31

Which ends up calling the code you linked to in your comment above. The workaround you can do on your side for now is to create an init for your Installation in a similar way and reinitialize your Installation using dispatch like how the SDK initializer does it

**Comment by funkenstrahlen** [comment]
Thank you for your quick response.

I tried to implement your suggested workaround. However it does not work as expected in this case.

1. `ParseUser.logout` clears `CurrentInstallationContainer` from `ParseStorage` and `KeychainStorage`.
2. Calling `Self.current = self` runs `Self.currentInstallationContainer.currentInstallation = newValue`
3. This creates a new `CurrentInstallationContainer` **before** setting the new installation as `newValue`
4. Therefore the `ParseInstallation` created this way is missing an `installationId` as the `installationId` currently only gets created when a new `currentInstallationContainer` is created.

Do you agree this is an actual issue in the current *ParseSwift* implementation and we should work on a fix in the framework?

**Comment by cbaker6** [comment]
> Therefore the ParseInstallation created this way is missing an installationId as the installationId currently only gets created when a new currentInstallationContainer is created.

This doesn't seem right as this is the same process the SDK uses to create the installationId.

**Comment by funkenstrahlen** [comment]
Thank you for the PR regarding this issue. I tested the changes and posted feedback in the PR thread.
