### ISSUE TITLE
ParseUser.delete() does not remove session from server

### ISSUE THREAD

**Issue by lsmilek1** [parse-community/Parse-Swift#111]
Hi,

I am not sure if it is but or desired behaviour... After calling `PrsUser.current?.delete(completion: { result in ... })` in the client app the user object gets removed from server, but the session object remains intact.

Calling `PrsUser.logout  { result in ... }` does remove the session, so should I log out user first before deleting the account, or could we achieve it in one call?

What I want to achieve is to remove account together with related sessions, if user decide to stop using my app.

Thank you!

**Comment by cbaker6** [comment]
> Calling PrsUser.logout { result in ... } does remove the session, so should I log out user first before deleting the account, or could we achieve it in one call?

If you log the user out first, my guess is if you are using Parse’s default ACL and CLP, you won’t be able to successfully delete the user.

The solution to your problem may be through cloud code afterDelete, remove the sessionToken https://docs.parseplatform.org/cloudcode/guide/#afterdelete

**Comment by lsmilek1** [comment]
cbaker6, thank you for your prompt answer, as always! It makes sense, I will have a look into the cloud code. I guess then this was answered and can be closed as it is actually desired behaviour since there is no "delete account" function and what I was calling is deleting the user object only. 

It came to my mind that client app could do the cleaning itself (together with other user's data and objects), before deleting the user at last, but that kind of don't make sense as that process might be more prone to interruptions.
