### ISSUE TITLE
Remove automatic retrieval of badge in ParseInstallation

### ISSUE THREAD

**Issue by cbaker6** [parse-community/Parse-Swift#113]
Getting the badge value automatically is something native to the Objective-c SDK (and currently Parse-Swift). It requires using UIKit or AppKit to retrieve and accessing it properly means `ParseInstallation` has to always be called on the main queue. This leads to awkward implementation and usage of `ParseInstallation`. In addition, Parse-Swift works on OSs that don't have badges like Linux and Android.

I plan to remove the automatic retrieval of badge. If a developer wants to populate this field they can create their own dispatches before adding it to `ParseInstallation`.

This will lead to easier usage and less buggy and more predictable (example https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1568) behavior when using `ParseInstallation`.

Feel free to comment with your thoughts...

**Comment by funkenstrahlen** [comment]
I think this is a good idea! 👍
