### ISSUE TITLE
Array of Pointer not working in User class

### ISSUE THREAD

**Issue by Mammut-Felix** [parse-community/Parse-Swift#130]
Hey Parse-Community!

I'm trying to get an array of pointers from a user. 
This works perfectly with a logged in user. 
```swift
User.current?.fetch(includeKeys: ["pointerArray"], options: [], callbackQueue: .main, completion: { result in
    // Do stuff
}
```

But when logging in for the first time it doesn't work.
```swift
User.login(username: username, password: password) { results in
   // Do stuff
}
```

I get the following error: 
```
ParseError(code: ParseSwift.ParseError.Code.unknownError, message: "Error decoding parse-server response: {...} with error: The data couldn’t be read because it is missing. Format: {...} 
```

The Objects:
```swift
struct User: ParseUser, Codable {
    var username: String?
    var email: String?
    var password: String?
    var authData: [String: [String: String]?]?
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?

    var pointerArray: [CustomObject]?
}

struct CustomObject: ParseObject, Codable {
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?

    var title: String?
}
```

**Comment by cbaker6** [comment]
Hi @Mammut-Felix, when posting a potential issue, please post the full `ParseError` as it often shows where the problem is. You can remove any private info.

Also, is the struct you provided what you actually tested. You originally posted:

```swift

struct User: ParseUser, Codable {
    var username: String?
    var email: String?
    var password: String?
    var authData: [String: [String: String]?]?
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?

    var pointerArray: [CustomObject] // Not optional, which will definitely give you an error because all keys should be optional
}
```

These are not the same...

You can see this [answer](https://community.parseplatform.org/t/cant-fetch-objects-with-pointers/1471/2?u=cbaker6) for more details as from you original post it seems like the same problem.

**Comment by Mammut-Felix** [comment]
Hi @cbaker6, thanks for your reply.
Yeah I changed the post because I forgot the optional. In my test the array is also optional.

The complete ParseError:

```
ParseError(code: ParseSwift.ParseError.Code.unknownError, message: "Error decoding parse-server response: Optional(<NSHTTPURLResponse: 0x6000018d9800> { URL: https://parse.endpoint/login } { Status Code: 200, Headers {\n    \"Access-Control-Allow-Origin\" =     (\n        \"*\"\n    );\n    \"Content-Encoding\" =     (\n        gzip\n    );\n    \"Content-Type\" =     (\n        \"application/json; charset=utf-8\"\n    );\n    Date =     (\n        \"Mon, 26 Apr 2021 11:42:53 GMT\"\n    );\n    Etag =     (\n        \"W/\\\"1ef-EOV9mGaVgYexdK/WN2AMiTxS3P8\\\"\"\n    );\n    Server =     (\n        nginx\n    );\n    \"Strict-Transport-Security\" =     (\n        \"max-age=31536000; includeSubDomains; preload\"\n    );\n    Vary =     (\n        \"Accept-Encoding\"\n    );\n    \"access-control-allow-headers\" =     (\n        \"X-Parse-Master-Key, X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, X-Parse-Request-Id, Content-Type, Pragma, Cache-Control\"\n    );\n    \"access-control-allow-methods\" =     (\n        \"GET,PUT,POST,DELETE,OPTIONS\"\n    );\n    \"access-control-expose-headers\" =     (\n        \"X-Parse-Job-Status-Id, X-Parse-Push-Status-Id\"\n    );\n    \"content-security-policy\" =     (\n        \"default-src \'self\' http: https: data: blob: \'unsafe-inline\'\"\n    );\n    \"referrer-policy\" =     (\n        \"no-referrer-when-downgrade\"\n    );\n    \"x-content-type-options\" =     (\n        nosniff\n    );\n    \"x-frame-options\" =     (\n        SAMEORIGIN\n    );\n    \"x-powered-by\" =     (\n        Express\n    );\n    \"x-xss-protection\" =     (\n        \"1; mode=block\"\n    );\n} }) with error: The data couldn’t be read because it is missing. Format: Optional(\"{\\\"objectId\\\":\\\"w6d9Be0kUW\\\",\\\"emailVerified\\\":true,\\\"username\\\":\\\"email@email.com\\\",\\\"accType\\\":\\\"admin\\\",\\\"createdAt\\\":\\\"2021-03-22T13:57:47.210Z\\\",\\\"updatedAt\\\":\\\"2021-04-26T11:41:55.265Z\\\",\\\"email\\\":\\\"email@email.com\\\",\\\"firstname\\\":\\\"firstname\\\",\\\"lastname\\\":\\\"lastname\\\",\\\"pointerArray\\\":[{\\\"__type\\\":\\\"Pointer\\\",\\\"className\\\":\\\"CustomObject\\\",\\\"objectId\\\":\\\"ghB7KjzWSQ\\\"}],\\\"ACL\\\":{\\\"*\\\":{\\\"read\\\":true},\\\"role:Admin\\\":{\\\"read\\\":true,\\\"write\\\":true},\\\"w6d9Be0kUW\\\":{\\\"read\\\":true,\\\"write\\\":true}},\\\"sessionToken\\\":\\\"r:9121a3ece6de6e0588e49b5e187c7ccf\\\"}\")")
```

At the CustomObject all properties are optional, too.

**Comment by cbaker6** [comment]
Something doesn't seem right with your code. The error states: `The data couldn’t be read because it is missing.` which usually indicates it couldn't decode a required key, but you are saying everything is optional and works when you `includeKeys: ["pointerArray"],...`. Are you sure you only have one `User` struct and all the keys are optional? What happens when you comment out `pointerArray` in your User struct and then login?

```swift
struct User: ParseUser, Codable {
    var username: String?
    var email: String?
    var password: String?
    var authData: [String: [String: String]?]?
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?

    //var pointerArray: [CustomObject] // Not optional, which will definitely give you an error because all keys should be optional
}
```

It looks like your `ParseUser` doesn't match your server as your server is giving you back properties like `accType`, etc. This shouldn't be causing your issue, but you will need to add them to your User struct if you intend to use them on the client in the future.

All `ParseObject`s are `Encodable` and `Decodable`, you shouldn't need to add `Codable`, I would imagine the compiler is giving you warning.

**Comment by cbaker6** [comment]
Be sure to verify your code against the example in playgrounds: https://github.com/parse-community/Parse-Swift/blob/99b619696889be6f92a4130a31d58afc93739f4b/ParseSwift.playground/Pages/8%20-%20Pointers.xcplaygroundpage/Contents.swift#L67-L85

**Comment by cbaker6** [comment]
I've added another example to ParseUser in playgrounds that uses a `ParseObject` array similar to your example called `allScores`. 

https://github.com/parse-community/Parse-Swift/blob/b4d15de99a5d67fb0996dc2cb072541cec2001e9/ParseSwift.playground/Pages/4%20-%20User%20-%20Continued.xcplaygroundpage/Contents.swift#L87-L104

The playground examples work which leads me to believe something is wrong with your code. You should look through the examples and verify your code is setup properly.

**Comment by Mammut-Felix** [comment]
@cbaker6 Thank you for your support. I've got it going now. The error was actually in the CustomObject

**Comment by cbaker6** [comment]
Can you post what the error was and your your fix just in case someone else has the same issue in the future?

Feel free to close this issue
