### ISSUE TITLE
.fetch() with custom objectId

### ISSUE THREAD

**Issue by lsmilek1** [parse-community/Parse-Swift#138]
I am not sure if I misunderstood `fetch` and `find` or I am hitting some bug. 

* `fetch` I should use when I want to get objects based on `objectId` field
* `find` I should use when I have some query criteria and want to find one or more objects

I believe I can use find to get one single object with given `objectId` also, but I guess it is more performant to use fetch on unique objects?

What I got stuck is a `fetch` response returning empty object. I use custom `objectId` on this object and the save and update is working well. Before the first `fetch` I don't know the createAt date, so I init the struct with any `Date()`:

```
        init(objectId: String) {
                self.objectId = objectId
                self.createdAt = Date()
        }
```

then I call the fetch like this:

```
        let profileToFetch = PrsProfile(objectId: objectId)
        print("profileToFetch: \(profileToFetch)")
        profileToFetch.fetch { results in
            switch results {
            case .success(let profile):
                print("fetched profile: \(profile)")
            case .failure(let error):
                print("error: \(error)")
            }
        }
```

So struct being passed to fetch is:

> profileToFetch: PrsProfile ({"createdAt":{"__type":"Date","iso":"2021-05-11T09:28:21.877Z"},"objectId":"Uo9eYl2rkB"})

But the response gives back empty object:

> fetched profile: PrsProfile ({})

When I do not specify `createdAt` in init, the fetch function throws error due to `isSaved` check in SDK:

```
guard object.isSaved else {
            throw ParseError(code: .unknownError, message: "Cannot Fetch an object without id")
        }
```

`inkludekemys: ["*"]` is also not helping here. There is also no code in `beforeSave` trigger. How should I fetch an object with customId?

Thank you!

**Comment by cbaker6** [comment]
What happens when you use “first”?

**Comment by cbaker6** [comment]
If the server isn’t finding the object and you are sure it’s there, then it looks like it could be a parse-server issue instead of parse-swift. You want to open an issue on that repo

**Comment by cbaker6** [comment]
I will say I tried both of these in playgrounds and they worked fine with customObjectId:

```swift
let query = GameScore.query("objectId" == "myObjectId")
query.first { result in
    switch result {
    case .success(let found):
        print(found)
    case .failure(let error):
        print(error)
    }
}

let query = GameScore.query("objectId" == "myObjectId")
query.find { result in
    switch result {
    case .success(let found):
        print(found)
    case .failure(let error):
        print(error)
    }
}
```

**Comment by cbaker6** [comment]
The fetch is a bug in Parse-Swift

**Comment by lsmilek1** [comment]
Ahh, so for the `.fetch()` I will not have to specify `createdAt` anymore, right? Thank you very much for the support!

**Comment by lsmilek1** [comment]
I noticed that after update I do not need to specify the `createdAt` anymore for the `fetch()` function, but I still struggle to use the `.fetch()` because it returns `.success` with empty object when there is no object under certain `objectId`

> fetched profile: PrsProfile ({})

`.query.first("objectId" == objectIdToFetch)` throws useful error code in that case:

> Error querying: ParseError(code: ParseSwift.ParseError.Code.objectNotFound, message: "Object not found on the server.")

So I ended up not using `.fetch()` but I wonder now if there is any performance cost of `.query.first("objectId" == objectIdToFetch)` over `.fetch()`?

Or I do something wrong and `.fetch()` should also return `ParseSwift.ParseError.Code.objectNotFound` when there is no object under the objectId yet?

**Comment by cbaker6** [comment]
> I noticed that after update I do not need to specify the createdAt anymore for the fetch() function, but I still struggle to use the .fetch() because it returns .success with empty object when there is no object under certain objectId

I'm not able to replicate this behavior and `fetch` seems to work as expected when I test it in playgrounds: 
https://github.com/parse-community/Parse-Swift/blob/f606382b5bf4fd1ae9554e1a186eaddf029acf1c/ParseSwift.playground/Pages/15%20-%20Custom%20ObjectId.xcplaygroundpage/Contents.swift#L108-L119

This returns:

```swift
Fatal error: Error fetching: ParseError(code: ParseSwift.ParseError.Code.objectNotFound, message: "Object not found."): file __lldb_expr_377/15 - Custom ObjectId.xcplaygroundpage, line 117
```

> but I wonder now if there is any performance cost of .query.first("objectId" == objectIdToFetch) over .fetch()?

`first` queries with `count == 1`, so I doubt there's a performance hit, particularly since I believe the objectId is indexed automatically by the Parse Server.

**Comment by lsmilek1** [comment]
Thank you for prompt feedback. I double-checked the init() in my `PrsProfile` as well as ACL and CLP and I am not able to find out why it is not working. 

- Unfortunately I am held on an older version of Parse Server as I am using Back4App for now, so that could be a reason. ParseSwift SDK is 1.8.0. 
- Other reason what comes to my mind is that I have under the same objectId already an existing object of a different class `PrsUser`. Here I believe it is not the cause, but...

I will test it as soon as I move to higher version of Parse. For now I will stay with `.first()` as the objectId is indexed, yes.

Thank you!
