### ISSUE TITLE
AnyCodable no longer public

### ISSUE THREAD

**Issue by Vortec4800** [parse-community/Parse-Swift#141]
In a recent version of the SDK, `AnyCodable` (and the En/Decodable versions) were changed from public to internal. Our project used `AnyDecodable` as part of a Cloud code return value:

```swift
struct CheckUserStatusCloudFunction: ParseCloud {
	typealias ReturnType = [String: AnyDecodable]
	
	var functionJobName = "checkUserStatus"
	
	var platform = "ios"
	var appIdentifier: String
}
```

The server returns a dictionary where the keys are all strings, and the values are various codable values like string, bool, int, etc. Normally we would create a struct to contain the results, but this specific functionality needs to be generic and could be used by different apps and the result may have different keys so it can't be statically typed in that way.

I can just add my own version of AnyCodable to the project, but this seems like a lot of duplication for something that already exists in the project. Can this be made public again?

**Comment by cbaker6** [comment]
Please see the comment for the reason and the solution: https://github.com/parse-community/Parse-Swift/pull/127#issue-622671395

**Comment by Vortec4800** [comment]
Thank you, I didn't realize this was an adaptation of another library. I'll include this as a dependency and use it instead.
