### ISSUE TITLE
Cannot use [object Object] as a query parameter

### ISSUE THREAD

**Issue by Randallcp** [parse-community/Parse-Swift#147]
I wrote the following code: 

```
static func getAuthor(from book: Book, completion: @escaping ((Result<Author, Error>) -> Void)) {
    let query = Author.query().include("book").where("book" == book)
    query.first { results in
        switch results {
            case .success(let author):
                completion(.success(author))
            case .failure(let error):
                completion(.failure(error))
        }
    }
}
```

And expected to be able to fetch the Author that had the property "book" of type Pointer<Book> and of value of the book I passed in. (I previously fetched the Book and passed it directly into here)

Here is my Author:

```
struct Author: ParseObject {

    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?

    var book: Book?
}
```

But when the query runs I get the error ParseError(code: ParseSwift.ParseError.Code.invalidJSON, message: "You cannot use [object Object] as a query parameter.")

Note: Sorry if this by any chance possible through a different approach (and please let me know how :)) The parse sdk allowed me to do this with where(equalTo:)... so I was assuming this was a bug.

**Comment by cbaker6** [comment]
Your book should probably be a pointer since that's how it's saved to your Author class. What happens when you try:

```swift
static func getAuthor(from book: Book, completion: @escaping ((Result<Author, Error>) -> Void)) {
    let bookPointer = try! book.toPointer()
    let query = Author.query().include("book").where("book" == bookPointer)
    query.first { results in
        switch results {
            case .success(let author):
                completion(.success(author))
            case .failure(let error):
                completion(.failure(error))
        }
    }
}
```

Note, that your error is a server error and not a Swift SDK error.
