### ISSUE TITLE
Missing error when saving a user with an email which already exists on the server

### ISSUE THREAD

**Issue by funkenstrahlen** [parse-community/Parse-Swift#149]
Parse Server enforces unique email addresses on the users collection.

Currently the signup function only takes a username and password.

Setting the email of the user and saving after signup does succeed when the email does not already exists. However if the email already exists no error occurs on the client side.

This is my signup code:

```swift
    public func signupWith(username: String, email: String, password: String) {
        guard PodliveUser.current != nil else {
            fatalError("Can not signup because current user is nil")
        }
        PodliveUser.current?.username = username
        PodliveUser.current?.password = password
        PodliveUser.current?.email = email
        PodliveUser.signup(username: username, password: password) { [self] (result) in
            switch result {
            case .success(var user):
                // save user again to store email on the server
                user.save { (resut) in
                    switch result {
                    case .success(_):
                        NotificationCenter.default.post(name: Notification.Name.userUpdated, object: nil)
                    case .failure(let error):
                        print("Could not save email after signup: " + error.localizedDescription)
                    }
                    NotificationCenter.default.post(name: Notification.Name.userUpdated, object: nil)
                }
            case .failure(let error):
                print("Could not signup " + error.localizedDescription)
            }
        }
    }
```

I expected to see the error `Could not save email after signup`. However the email of the user is set locally but is not persisted on the server (if a user with the email already exists).

An even better approach in my eyes is to include the email in the signup function directly so I do not have to do multiple network calls.

I use ParseSwift 1.7.2 with Xcode 12.5.

**Comment by cbaker6** [comment]
You are setting the current user and then using the static method for signup. The `email` isn’t being considered in your example. 

The correct way to do it using the instance method for signup:

```swift
var user = PodLiveUser() // You can create an init on your PodLiveUser to take email, username, password if you want
user.email = “custom@email.com”
user.username = “hello”
user.password = “password”
user.signup {  (result) in
            switch result {
            case .success(var user):
                // save user again to store email on the server
                user.save { (resut) in
                    switch result {
                    case .success(_):
                        NotificationCenter.default.post(name: Notification.Name.userUpdated, object: nil)
                    case .failure(let error):
                        print("Could not save email after signup: " + error.localizedDescription)
                    }
                    NotificationCenter.default.post(name: Notification.Name.userUpdated, object: nil)
                }
            case .failure(let error):
                print("Could not signup " + error.localizedDescription)
            }
        }
```

**Comment by cbaker6** [comment]
Your code also has:

```swift

guard PodliveUser.current != nil else {
            fatalError("Can not signup because current user is nil")
        }
        PodliveUser.current?.username = username
        PodliveUser.current?.password = password
        PodliveUser.current?.email = email
```

If current != nil, this means the user is already signed in, but your code is attempting to signup the user who’s already signed in. If you really want to check if emails are unique. You should just modify and save the email to the user after the first signup instead of attempting to signup again without logging out first.

**Comment by funkenstrahlen** [comment]
Thank you very much for your reply! Signup works as expected when using instance method instead of the static one.

Why is there even as static signup method available?

**Comment by cbaker6** [comment]
> Why is there even as static signup method available?

It allows you to sign up without creating an instance. This is useful when attempting to signup a user with just the username and password. If I remember correctly, Apple recommends allowing users to sign up without requiring email, particularly when you have any 3rd party authentication
