### ISSUE TITLE
Detecting disconnected LiveQuery

### ISSUE THREAD

**Issue by lsmilek1** [parse-community/Parse-Swift#156]
I am trying to build a robust way how to detect any missed liveQuery updates due to connectivity issue with the playground code example combined with `NWPathMonitor()`:

```
    var subscription: SubscriptionCallback<PrsProfile>?
    
    let monitor = NWPathMonitor()
    
    func testLiveQueryOnProfile() {
        print("testing live query for objectId: \(String(describing: PrsUser.current?.objectId))")
        //testing LiveQuery only
        if let objectId = PrsUser.current?.objectId {
            //: Create a query just as you normally would.
            let query = PrsProfile.query("objectId" == objectId)
            //: This is how you subscribe to your created query using callbacks.
            subscription = query.subscribeCallback!
            print("cached subscription: \(String(describing: subscription))")
            //: This is how you receive notifications about the success
            //: of your subscription.
            subscription!.handleSubscribe { subscribedQuery, isNew in
                //: You can check this subscription is for this query
                if isNew {
                    print("Successfully subscribed to new query \(subscribedQuery)")
                } else {
                    print("Successfully updated subscription to new query \(subscribedQuery)")
                }
            }
            
            //: This is how you register to receive notificaitons of events related to your LiveQuery.
            subscription!.handleEvent { _, event in
                switch event {

                case .entered(let object):
                    print("LQ Entered: \(object)")
                case .left(let object):
                    print("LQ Left: \(object)")
                case .created(let object):
                    print("LQ Created: \(object)")
                case .updated(let object):
                    print("LQ Updated: \(object)")
                case .deleted(let object):
                    print("LQ Deleted: \(object)")
                }
            }
            
            //: This is how you register to receive notificaitons about being unsubscribed.
            subscription!.handleUnsubscribe { query in
                print("Unsubscribed from \(query)")
            }
            
            monitor.pathUpdateHandler = { path in
                if path.status == .satisfied {
                    // Indicate network status, e.g., back to online
                    print("back to online")
                } else {
                    // Indicate network status, e.g., offline mode
                    print("offline mode")
                }
            }
            monitor.start(queue: .global())
            
        }
    }
```

for testing I am using Xcode's Network Link Conditioner. I am not able to detect when the LiveQuery socket or subscription got lost, as the `NWPathMonitor()` is not reliable in this case (connection path did not change, only 100% loss occurs) and the `SubscriptionCallback` does not call any event.

What is the correct way to get notified when LiveQuery is not anymore listening? When I test this procedure: block connection bandwidth, app to background for a moment, app resumes active, unblock the traffic.. the following return true even when there are no events being received anymore:

`ParseLiveQuery.getDefault()?.isConnected`

The client should know when it should re-fetch actual state and subscribe again to the queries. I struggle to find out how to detect that moment

**Comment by cbaker6** [comment]
> What is the correct way to get notified when LiveQuery is not anymore listening? When I test this procedure: block connection bandwidth, app to background for a moment, app resumes active, unblock the traffic.. the following return true even when there are no events being received anymore: ParseLiveQuery.getDefault()?.isConnected

Maybe the websocket isn't actually closed during your testing? `isConnected` seems to be doing what it's suppose to do:

https://github.com/parse-community/Parse-Swift/blob/b064000d07724e2e2f2fab2306bf52098ab353a6/Sources/ParseSwift/LiveQuery/LiveQuerySocket.swift#L115-L129

https://github.com/parse-community/Parse-Swift/blob/b064000d07724e2e2f2fab2306bf52098ab353a6/Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift#L295-L311

**Comment by lsmilek1** [comment]
I added a bunch of print statements to better understand the behaviour:

```
   func printLiveQueryClient() {
        print("testing subscription: \(subscription)")
        let client = ParseLiveQuery.getDefault()
        print("testing LiveQuery isConnected: \(client?.isConnected)")
        print("testing LiveQuery isConnecting: \(client?.isConnecting)")
        print("testing LiveQuery isSocketEstablished: \(client?.isSocketEstablished)")
        if let objectId = PrsUser.current?.objectId {
            //: Create a query just as you normally would.
            let query = PrsProfile.query("objectId" == objectId)
            print("testing LiveQuery isSubscribed: \(try? client?.isSubscribed(query))")
            print("testing LiveQuery isPendingSubscription: \(try? client?.isPendingSubscription(query))")
        }
    }
```

Out of curiosity I print it in `sceneDelegate` app life cycle functions and it always gives following:

> testing subscription: Optional(ParseSwift.SubscriptionCallback<Felse.PrsProfile>)
> testing LiveQuery isConnected: Optional(true)
> testing LiveQuery isConnecting: Optional(false)
> testing LiveQuery isSocketEstablished: Optional(true)
> testing LiveQuery isSubscribed: Optional(true)
> testing LiveQuery isPendingSubscription: Optional(false)

I noticed that I can hold the app sometimes for a long time with packet loss 100% (I tried 10 minutes) and when I unblock it, it takes some minute, but the client receives the updates. On the other hand, sometimes already after 3 minutes being active and throttled and mostly when I try to put app in the background when blocking the traffic, and then it becoming back active - although the print statements show the same - the client does not receive any updates anymore. 

So did I misunderstood the WebSocket and LiveQuery completely and I should unsubscribe in `sceneWillResignActive` and subscribe again after `sceneDidBecomeActive`? What is a good practice?

**Comment by lsmilek1** [comment]
Reading through the documentation I gained some understanding and I found this [article](https://www.vadimbulavin.com/network-connectivity-on-ios-with-swift/) informative. What I am not sure about is the way how to use the SDK. Putting aside any connectivity conditions for now (as that is rather extreme end case) here is an example with healthy connection:

1) in `sceneWillResignActive` the it prints as previously mentioned:

> testing subscription: Optional(ParseSwift.SubscriptionCallback<Felse.PrsProfile>)
> testing LiveQuery isConnected: Optional(true)
> testing LiveQuery isConnecting: Optional(false)
> testing LiveQuery isSocketEstablished: Optional(true)
> testing LiveQuery isSubscribed: Optional(true)
> testing LiveQuery isPendingSubscription: Optional(false)

2) right after in `sceneDidEnterBackground` I try to close the WebSocket to off-load server and the printed states changes:

```
print("closing web socket")
ParseLiveQuery.getDefault()?.close()
```

> closing web socket
> testing subscription: Optional(ParseSwift.SubscriptionCallback<Felse.PrsProfile>)
> testing LiveQuery isConnected: Optional(false)
> testing LiveQuery isConnecting: Optional(false)
> testing LiveQuery isSocketEstablished: Optional(true)
> testing LiveQuery isSubscribed: Optional(true)
> testing LiveQuery isPendingSubscription: Optional(false)

3) coming back in `sceneDidBecomeActive` I try to reopen it again, but that call seems to not have any effect:

```
print("opening web socket")
let client = ParseLiveQuery.getDefault()
print("client: \(client)")
client?.open(completion: { error in
     print("error while opening webSocket: \(error?.localizedDescription)")
})
```

> opening web socket
> client: Optional(<ParseSwift.ParseLiveQuery: 0x7ffa91125290>)
> testing subscription: Optional(ParseSwift.SubscriptionCallback<Felse.PrsProfile>)
> testing LiveQuery isConnected: Optional(false)
> testing LiveQuery isConnecting: Optional(false)
> testing LiveQuery isSocketEstablished: Optional(true)
> testing LiveQuery isSubscribed: Optional(true)
> testing LiveQuery isPendingSubscription: Optional(false)

The updates are not received after this, even the `open()` does not throw any error. `isConnected` & `isConnecting` stays false (no code race there).

In the [article](https://www.vadimbulavin.com/network-connectivity-on-ios-with-swift/) I find a nice trick with the configuration and later delegate to detect any connectivity issues. But I believe the configuration and delegate are reserved for the ParseLiveQuery class itself, so it can handle the states, so I am not sure if I can use that:
```
let config = URLSessionConfiguration.default
config.waitsForConnectivity = true
config.timeoutIntervalForResource = 300 
```
```
class NetworkingHandler: NSObject, URLSessionDelegate {
    func urlSession(_ session: URLSession, taskIsWaitingForConnectivity task: URLSessionTask) {
        // Indicate network status, e.g., offline mode
    }
    
    func urlSession(_ session: URLSession, task: URLSessionTask, willBeginDelayedRequest: URLRequest, completionHandler: (URLSession.DelayedRequestDisposition, URLRequest?) -> Void) {
        // Indicate network status, e.g., back to online
    }
}

let session = URLSession(configuration: config, delegate: NetworkingHandler(), delegateQueue: .main)
```

I believe the SDK is indeed doing what it should, I just am not able to understand how to use it in a clean way after reading the playgrounds example to not cause any hanging open sockets on the server side, miss as less as possible updates due to connectivity and also to use it through the app live cycle without getting in a dead end like above.

Should I in this case init ParseLiveQuery in my data store class, then assign it as setDefault() and if closing the connection I should set it to nil?

```
var liveQueryClient = try? ParseLiveQuery()
ParseLiveQuery.setDefault(liveQueryClient)
```
...and in `sceneDidEnterBackground` set:
```
var liveQueryClient = nil
```
...later  in `sceneDidBecomeActive` set it again with new client?
```
var liveQueryClient = try? ParseLiveQuery()
ParseLiveQuery.setDefault(liveQueryClient)
```

**Comment by cbaker6** [comment]
What’s the output on the server side when testing your network conditions? The server logs live query connections/disconnections. Do these match the client? If so, then the client is working correctly and I’m not sure what else you could do on the client side.

I recommend going through the [testcases for live query](https://github.com/parse-community/Parse-Swift/blob/main/Tests/ParseSwiftTests/ParseLiveQueryTests.swift), if you find a problem in one of the tests, or find a test is missing, feel free create a PR with the update. This will add tests that are repeatable as I will need be able to replicate your examples above. A heads up, the URL mocker for the tests currently cannot mock websockets, so it will attempt to make real connections.

**Comment by lsmilek1** [comment]
Closing as the problem is rather my knowledge. :-) I am using back4app for now and I see some logs in the dashboard's cloud code info log, but I can't figure out the timestamp logic as they seems to appear with a lot of delay and not in a continuous sequence:

> 2021-06-09T12:25:05.641Z - Create new client: a422a5fa-3b37-4b29-9d1a-f7805ed18390
> 2021-06-09T12:12:57.834Z - Client disconnect: c7a1dcda-b865-4942-a8f7-11ab7302b799
> 2021-06-09T12:04:46.252Z - Create new client: c7a1dcda-b865-4942-a8f7-11ab7302b799
> 2021-06-09T12:04:34.209Z - Client disconnect: 4a893bf0-e003-4fd3-8769-e523723a892a
> 2021-06-09T12:03:32.395Z - Create new client: 4a893bf0-e003-4fd3-8769-e523723a892a
> 2021-06-09T12:03:08.188Z - Create new client: f8222da2-678a-4a11-91e6-440181a77daa
> 2021-06-09T12:03:07.600Z - Parse LiveQuery Server starts running
> 2021-06-09T10:40:29.577Z - Client disconnect: 2caae016-6468-4b5b-8453-f16b487e2336
> 2021-06-09T10:35:02.862Z - Create new client: 2caae016-6468-4b5b-8453-f16b487e2336
> 2021-06-09T10:35:01.969Z - Parse LiveQuery Server starts running
> 2021-06-09T09:23:52.032Z - Create new client: 7283a515-b393-464f-a531-5a1e3124a13f
> 2021-06-09T09:23:39.611Z - Client disconnect: 7a28c8ad-db74-4150-a4a3-751acdd433e5
> 2021-06-09T09:23:14.660Z - Create new client: 7a28c8ad-db74-4150-a4a3-751acdd433e5
> 2021-06-09T09:17:18.013Z - Parse LiveQuery Server starts running
> 2021-06-09T09:17:16.159Z - Parse LiveQuery Server starts running
> 2021-06-09T09:03:20.316Z - Create new client: cad1bb42-fb35-4c08-b0b2-555179b81ee3
> 2021-06-09T09:03:19.788Z - Parse LiveQuery Server starts running

They are sorted in the log but the records 12:03:32 showed up after the 12:04:34 and the most recent 12:25:05 is still about 15 minutes old. I guess they will be still showing up
