### ISSUE TITLE
Decoding error when saving nested object

### ISSUE THREAD

**Issue by ribotinho** [parse-community/Parse-Swift#157]
Hi all,

I am encountering an issue when saving a nested object.

I have a teacher object that has a name (string) and a language (custom object)

```
struct teacher : ParseObject {
    
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
    
    var name : String
    var langauge : language
}
```

```
struct language : ParseObject{
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
    
    var code : String
}
```

I have no problem creating and saving language objects, but when I try to save a Teacher object I am getting a decoding error:

ParseError(code: ParseSwift.ParseError.Code.unknownError, message: "decoding error: typeMismatch(Swift.Array<Any>, Swift.DecodingError.Context(codingPath: [], debugDescription: \"Expected to decode Array<Any> but found a dictionary instead.\", underlyingError: nil))")

I am running the parse server on a localhost. macOS Big Sur and SwiftUI.

I have also tried saving the example of Author and Book in the Swift Playgrounds example code but I am getting exactly the same output.

Any one would know how can I solve this? Or what I am missing?

Kind regards,
Pau

**Comment by cbaker6** [comment]
Hi Pau, your nested object properties need to be "optional" because after it's saved it will come back as a Parse Pointer and will not contain the property `code`. Try:

```swift
struct language : ParseObject{
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
    
    var code : String? //change to optional
}
```

Because of this, I recommend making all of your properties optional.

You can look at the playgrounds for examples: https://github.com/parse-community/Parse-Swift/blob/main/ParseSwift.playground/Pages/8%20-%20Pointers.xcplaygroundpage/Contents.swift

**Comment by cbaker6** [comment]
Also, be sure to check through closed issues. This has been answered before here: https://github.com/parse-community/Parse-Swift/issues/130#issuecomment-826764877

**Comment by ribotinho** [comment]
Thanks for your prompt reply Corey!

I am afraid changing the property to optional is not solving the issue.

I've tried once again with the example code in the playgrounds you linked and I am getting the same exact error:

Fatal error: Error saving: ParseError(code: ParseSwift.ParseError.Code.unknownError, message: "decoding error: typeMismatch(Swift.Array<Any>, Swift.DecodingError.Context(codingPath: [], debugDescription: \"Expected to decode Array<Any> but found a dictionary instead.\", underlyingError: nil))")

**Comment by cbaker6** [comment]
What version of the Swift SDK and the parse-server are you running? I just ran the latest version of the Swift SDK against the latest server and 4.5.0 and I'm not getting any errors.

Also, the test cases in the SDK will catch this if it is broken

**Comment by ribotinho** [comment]
I installed the SDK via Podfile this morning
- ParseSwift (1.8.0)

And it looks like I am running 3.9. I'll upgrade to 3.9 and try this again

"parse-server": "^3.9.0"

**Comment by cbaker6** [comment]
Maybe you saved your Parse class properties with different types than your current type. If you use Parse Dashboard to delete your old class (assuming you only have dummy data in there) and then save your current type, it might fix your issue. The types for your properties need to match the types on your Parse server database (mongo or postgres)

The log output you sent seems related to your Xcode and network connection and don't seem to be related to the Swift SDK

**Comment by ribotinho** [comment]
I am using MongoDB and this is just a test project so everything is dummy data.

This might sound stupid, but do I need to create each class in the database before trying to save instances there? I have not done so for language

**Comment by cbaker6** [comment]
> do I need to create each class in the database before trying to save instances there? I have not done so for language

Not necessarily, as long as you as you didn't set `allowClientClassCreation == false` on the server, you can create from the client, https://docs.parseplatform.org/ios/guide/#restricting-class-creation

**Comment by ribotinho** [comment]
Tried also deleting any previously saved data in the database but it's not that either. I guess I'll start from scratch tomorrow with a fresh install. Thanks for your help!

**Comment by ribotinho** [comment]
Re-installed everything. Created a new Xcode project (with the playgrounds examples, book and author) and I am encountering the same exact behavior.

```
Server health is: ok
Saved Book ({"objectId":"BhbBuy4mRA","updatedAt":{"__type":"Date","iso":"2021-06-11T09:48:26.422Z"},"title":"hello","createdAt":{"__type":"Date","iso":"2021-06-11T09:48:26.422Z"}})
testParseMongo/ContentView.swift:57: Fatal error: Error saving: ParseError(code: ParseSwift.ParseError.Code.unknownError, message: "decoding error: typeMismatch(Swift.Array<Any>, Swift.DecodingError.Context(codingPath: [], debugDescription: \"Expected to decode Array<Any> but found a dictionary instead.\", underlyingError: nil))")
2021-06-11 11:48:26.444745+0200 testParseMongo[5980:148481] testParseMongo/ContentView.swift:57: Fatal error: Error saving: ParseError(code: ParseSwift.ParseError.Code.unknownError, message: "decoding error: typeMismatch(Swift.Array<Any>, Swift.DecodingError.Context(codingPath: [], debugDescription: \"Expected to decode Array<Any> but found a dictionary instead.\", underlyingError: nil))")
```

Any other ideas why this might be happening?

**Comment by cbaker6** [comment]
This is a bug as it looks like the parse-server has issues supporting transactions for mongo (doesn't occur with postgres).

I'm working on a PR that will turn off transactions by default.

**Comment by cbaker6** [comment]
@ribotinho thanks reporting and retesting.

Can you let us know if v1.8.1 solves the problem?

**Comment by ribotinho** [comment]
@cbaker6 I confirm the issue is now fixed and I can successfully save the nested object. Thanks a ton once again for your help! :)

**Comment by cbaker6** [comment]
Thanks for reporting! Let us know if you find any other bugs or suggested improvements.
