### ISSUE TITLE
Help wanted with v1.0 feature additions

### ISSUE THREAD

**Issue by cbaker6** [parse-community/Parse-Swift#16]
We are gearing up for the v1.0 release and would like your assistance with adding features. The features to be added can be found in https://github.com/parse-community/Parse-Swift/projects/1

Many of the features to be added have counterparts in the Objective-C SDK and though they are not implemented the same, can provide some guidance on what's needed. The [Objective-C SDK test cases](https://github.com/parse-community/Parse-SDK-iOS-OSX/tree/master/Parse/Tests/Unit) are also useful understanding what needs to be tested for the features.

There are some examples of Parse-Swift unit tests [here](https://github.com/parse-community/Parse-Swift/tree/main/Tests/ParseSwiftTests) 

If you decide to take one on, just submit a Pull Request and change it to "Draft" to let people know you are working on it.

**Comment by cbaker6** [comment]
We also need help documenting the public methods via markdown. This would be great for those who are new to Parse or those thinking of converting or using the Swift SDK for their new apps.

Some of the comments can be used from the obj-c SDK, but retrofitted for Swift:

The docs currently populate automatically when your PR is accepted. You can see the bare docs here: http://parseplatform.org/Parse-Swift/api/

**Comment by paulfreeman** [comment]
@cbaker6 I may be able to give a hand with part of the docs in the near future. I plan to port an objective-c parse app to a full SwiftUI based package once Files _upload_ support is in place and I have completed my current workload in a week or two.

**Comment by cbaker6** [comment]
@paulfreeman are you thinking of porting the iOS docs? https://github.com/parse-community/docs/tree/gh-pages/_includes/ios that show up here: https://docs.parseplatform.org/ios/guide/

If so, that would be great! @TomWFox what's the best way to go about this? My guess would be to create a PR to the docs repo adding a "swift" folder and then copy any file being converted from `ios` to `swift`. Then convert the file by making the relevant changes to the Parse-Swift SDK (removing the objective-c code). If there's a better way to do it, feel free to let us know

**Comment by TomWFox** [comment]
@cbaker6 That sounds good to me. My [PR to add a fluter guide](https://github.com/parse-community/docs/pull/671) should provide some direction in terms of the setup although I don't think I finished.

I wouldn't discourage any improvements being made if parts of the iOS guide seem poorly written etc but it will probably be much quicker to review if it's as straight a copy and paste as possible.

@paulfreeman or @cbaker6 give me a shout if you get started on the guide because I may try and get the setup done if I have some free time at some point.

**Comment by novemTeam** [comment]
I'll give it a try to help porting Unit tests

**Comment by cbaker6** [comment]
@novemTeam thanks for your interest in helping! Would you mind working on the CloudCode feature [here](https://github.com/parse-community/Parse-Swift/projects/1#card-46203840)?

- The main feature implementation [here](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/5dad4f224d5ae4b36ead891acbdfc15b86d527ae/Parse/Parse/Internal/CloudCode/PFCloudCodeController.m).

- The objc test cases are (These can be rolled into 1 swift file): [CloudUnitTests](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse/Tests/Unit/CloudUnitTests.m), [CloudCommandTests](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse/Tests/Unit/CloudCommandTests.m), [CloudUnitTests](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse/Tests/Unit/CloudUnitTests.m)

**Comment by novemTeam** [comment]
A few months ago, I started converting my Objective-C app to Swift, I used Parse so I am relying a lot on ParseSwift now.
I think it's in my advantage to help get ParseSwift launched.
Would be better if we got some more people on this.

I'll now take a look at it and let you know what I can do.

**Comment by cbaker6** [comment]
There are also some features that are currently in the Parse-Swift SDK that don't have tests. This might be an easier place to start since you don't need to add the feature first. It's possible the features need some additions, but some look intact, just need testing. One of the feature sets that falls in this category are Mutation Operations, https://github.com/parse-community/Parse-Swift/tree/main/Sources/ParseSwift/Mutation%20Operations

The tests in Objective-C are here: [FieldOperationTests](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/5dad4f224d5ae4b36ead891acbdfc15b86d527ae/Parse/Tests/Unit/FieldOperationTests.m) [FieldOperationDecoderTests](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/5dad4f224d5ae4b36ead891acbdfc15b86d527ae/Parse/Tests/Unit/FieldOperationDecoderTests.m)

You can look through what needs testing by looking at the codecov

-

**Comment by pmmlo** [comment]
@cbaker6 Is the idea to keep LiveQuery as a separate SDK or have it integrated into Parse-Swift?

**Comment by cbaker6** [comment]
Since it shouldn’t need any dependencies and the code needed to enable LiveQuery shouldn’t be large, it will most likely be integrated
