### ISSUE TITLE
Query for Null property

### ISSUE THREAD

**Issue by boardmain** [parse-community/Parse-Swift#160]
how to query for nil value?

 let query = Pagina.query("stato" == "PUBBLICATA", "parent" == nil)

i have

Generic parameter 'T' could not be inferred

**Comment by cbaker6** [comment]
You should use http://parseplatform.org/Parse-Swift/api/Functions.html#/s:10ParseSwift12doesNotExist3keyAA15QueryConstraintVSS_tF

**Comment by cbaker6** [comment]
Closing this out since it has an answer. Feel free to reopen if the question still remains.
