### ISSUE TITLE
Parse Swift can't decode custom ParseCloud errors

### ISSUE THREAD

**Issue by dblythy** [parse-community/Parse-Swift#164]
Throwing a custom error code from a Parse Cloud function results in:

```
ParseError(code: ParseSwift.ParseError.Code.unknownError, message: "Error decoding parse-server response: Optional(<NSHTTPURLResponse: 0x100d74140> { URL: http://localhost:1337/1/jobs/test } { Status Code: 200, Headers {\n    \"Content-Type\" =     (\n        \"application/json\"\n    );\n} }) with error: The data couldn’t be read because it is missing. 
```

Failing case:

```
    func testCustomError() {

        let encoded: Data = "{\"error\":\"Error: Custom Error\",\"code\":2000}".data(using: .utf8)!

        MockURLProtocol.mockRequests { _ in
            return MockURLResponse(data: encoded, statusCode: 200, delay: 0.0)
        }
        do {
            let cloud = Cloud(functionJobName: "test")
            _ = try cloud.startJob()
            XCTFail("Should have thrown ParseError")
        } catch {
            if let error = error as? ParseError {
                XCTAssertNotEqual(error.code, ParseError.Code.unknownError)
                XCTAssertEqual(error.code.rawValue, 2000)
            } else {
                XCTFail("Should have thrown ParseError")
            }
        }
    }
```

Proposed solution:

Add `.other` enum to error, and `intCode` property to Parse.Error

**Comment by cbaker6** [comment]
@dblythy thanks for your PR! Here’s a response I gave to a similar proposal? https://github.com/parse-community/Parse-Swift/pull/106#issuecomment-809542815

From your addition, does this mean the other SDKs currently allow users to create their own errors and mask them as Parse errors? I could be wrong here, but I would think errors would come from a set list of known Parse errors. If a user generates an error, maybe it can fall under “unknownError” or add a new error code on the server specific to user errors? Not sure what’s the best approach, but definitely open to hear you and the servers team thoughts.

My fear is allowing developers to mask their errors as parse errors and then people submit issues to Parse repos claiming they are Parse errors when they are not

**Comment by cbaker6** [comment]
My reasoning of using unknownError is because of how Flo documented ParseError before I took over it: https://github.com/parse-community/Parse-Swift/blob/603486ae6f2d27a7d5fdf9f94379bf045265ad36/Sources/ParseSwift/Types/ParseError.swift#L37

It seems believed all SDK errors, technically custom SDK errors should fall under this error. So I can see other errors going here as well

**Comment by dblythy** [comment]
The main problem is that if you use a _custom_ error, (which is already supported in Parse Server as well as every other SDK) Parse Swift can't decode it.

Such as:

```
Parse.Cloud.define("runFunction", ({user}) => {
  if (user.get('trialExpired')) {
     throw new Parse.Error(9000, "Your trial has expired");
  }
  ...
});
```

Call function:
```
if (e.code === 9000) {
// redirect to upgrade page
}
```

https://github.com/parse-community/parse-server/issues/6477

**Comment by cbaker6** [comment]
If I understand the discussion you linked it’s proposing to restrict custom errors to a specific range? https://github.com/parse-community/parse-server/issues/6477#issuecomment-637901549

That seems reasonable I guess and prevent some of my concern above

**Comment by dblythy** [comment]
The discussion linked is more to highlight that throwing specific custom errors from Cloud Code or third party modules is a common use case.

The main use for me is to change the behaviour of the app based on the custom error code response from the Parse Server.

**Comment by dblythy** [comment]
Furthermore:

https://github.com/parse-community/parse-server/blob/10695194b21a3ae2d34f88704a50a5ac0890202c/spec/CloudCode.spec.js#L143

**Comment by dblythy** [comment]
FYI to anyone using this, you can use ParseError.otherCode if you are throwing custom Parse Errors from Parse Cloud
