### ISSUE TITLE
New Installations created every time

### ISSUE THREAD

**Issue by dblythy** [parse-community/Parse-Swift#180]
In the Android SDK, the device stores its installation. When `.current` is called again later, the same installation is saved.

I am saving `Installation.current?`, however each time the app is reopened a new `Installation` object is saved in the database.

Does anyone have any ideas?

**Comment by cbaker6** [comment]
Linux and Android don’t have a Keychain. Are you initializing the Swift SDK with a Key/Value Store that you are persisting across launches? If not, there’s no way for the SDK store the previous installations or login. See comment: https://github.com/parse-community/Parse-Swift/issues/98#issuecomment-803293135

**Comment by cbaker6** [comment]
I made the comments above because you mentioned "Android".

If you are using an Apple OS, can you show your code and explain what you are doing? Do you see the same issue when you [signup](https://github.com/parse-community/Parse-Swift/blob/5ee216f8a7987d5ee67928d43184d38fbdec9a09/ParseSwift.playground/Pages/3%20-%20User%20-%20Sign%20Up.xcplaygroundpage/Contents.swift#L38-L57) and then [save your installation](https://github.com/parse-community/Parse-Swift/blob/5ee216f8a7987d5ee67928d43184d38fbdec9a09/ParseSwift.playground/Pages/6%20-%20Installation.xcplaygroundpage/Contents.swift#L40-L54) in playgrounds? It seems the installation is behaving correctly there.

Also, did you look through #115 it may provide some insight

**Comment by dblythy** [comment]
Hey @cbaker6, thank you for your response.

Installation is saved by:

```
func application(
      _ application: UIApplication,
      didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data
    ) {
        Installation.current?.setDeviceToken(deviceToken)
        Installation.current?.save { _ in }
    }
```

And on login:

```
Installation.current?.save { _ in }
```

And linked to user by:

```
Parse.Cloud.beforeSave(
  Parse.Installation,
  ({ user, object }) => {
    if (user) {
      object.set('user', user);
    } else {
      object.unset('user');
    }
    object.unset('save');
    return object;
  },
  {
    skipWithMasterKey: true,
  }
);

Parse.Cloud.beforeLogin(({ installationId, object }) => {
  (async () => {
    const installation = await new Parse.Query(Parse.Installation)
      .equalTo('installationId', installationId)
      .first({ useMasterKey: true });
    if (installation) {
      installation.set('user', object);
      await installation.save(null, { useMasterKey: true });
    }
  })();
});

Parse.Cloud.afterLogout(({ installationId }) => {
  (async () => {
    const installation = await new Parse.Query(Parse.Installation)
      .equalTo('installationId', installationId)
      .first({ useMasterKey: true });
    if (installation) {
      installation.unset('user');
      await installation.save(null, { useMasterKey: true });
    }
  })();
});
```

The installation is functioning fine, it's just that every time a user logs in and out, a new installation is created rather than using the previous one. Should I just delete in installation object on logout?

**Comment by cbaker6** [comment]
> The installation is functioning fine, it's just that every time a user logs in and out, a new installation is created rather than using the previous one.

Yes, you are correct, a new installation is created on the client after logout due to #112. 

> Should I just delete in installation object on logout?

Yes, if you have a Cloud Code cleanup Installation function, you can use that if needed. If I remember correctly, the server deletes Installations on logout

**Comment by cbaker6** [comment]
Closing for now, feel free to reopen if there are more questions.
