### ISSUE TITLE
ParseUser.current does not have fields set after .signup(), but it has after .login()

### ISSUE THREAD

**Issue by lsmilek1** [parse-community/Parse-Swift#186]
I have noticed that after `.signup()` in the client app, the `ParseUser.current` does not include the same data as when `.login()` is used:

```
        var newUser = PrsUser()
        newUser.email = email
        newUser.password = password
        newUser.username = email
        newUser.signup { [weak self] result in
            print("after sign-up: \(PrsUser.current)")
            ...
        }
```
> after sign-up: Optional(_User ({"ACL":{"TYlvXr8mcV":{"write":true,"read":true}},"username":"cc@cc.cc","objectId":"TYlvXr8mcV","createdAt":{"__type":"Date","iso":"2021-07-05T14:42:12.333Z"}}))

```
      PrsUser.login(username: email, password: password) { [weak self] result in
            print("after login: \(PrsUser.current)")
            ...
      }
```
> after login: Optional(_User ({"updatedAt":{"__type":"Date","iso":"2021-07-05T14:42:14.506Z"},"maxA":30,"minA":20,"emailVerified":false,"gch":0,"ACL":{"TYlvXr8mcV":{"write":true,"read":true}},"maxD":20,"sof":true,"username":"cc@cc.cc","objectId":"TYlvXr8mcV","email":"cc@cc.cc","createdAt":{"__type":"Date","iso":"2021-07-05T14:42:12.333Z"}}))

calling `PrsUser.current?.fetch(completion: { _ in })` right after `.signup()` success does not fill the missing fields. Is this intended behaviour? If so, should not `PrsUser.current?.fetch(completion: { _ in })` update the missing fields?

Thank you!

**Comment by cbaker6** [comment]
Can you post your `PrsUser` and whatever cloud code you have related to before and after saving a user. Without much knowledge of what you are doing, it seems like you are setting default values somewhere.

The previous comment I made is related and may solve your problem https://github.com/parse-community/Parse-Swift/issues/149#issuecomment-846983523

**Comment by cbaker6** [comment]
I looked into this further and it looks like it was a bug in the SDK where the SDK didn't correct store the User instance to `current`.

Based on your example, I'm assuming all of your properties persist to the cloud correctly during sign up, you just were missing data in the keychain?

**Comment by lsmilek1** [comment]
Yes, that is correct. In the cloud there were all fields set correctly. I just noticed it because I was trying to read the users email after sign-up in one of the views later. In above example the `PrsUser` was not modified between sign-up and login trials, so the above prints are actual values from that state. As for the cloud code, I am just adjusting the ACL as the back4app server version kept user write public:

```
Parse.Cloud.beforeSave(Parse.User, ({object, log, context}) => { 
  	//object is the user object itself
	if (!object.existed()) {
		//when user creates account, ACL to be set only for him
		const acl = new Parse.ACL();
		acl.setPublicReadAccess(false);
		acl.setPublicWriteAccess(false);
		object.setACL(acl);
	} 
});
```

Thank you for a lightning fast reaction!

**Comment by lsmilek1** [comment]
I was testing this now and I think there is still some unwanted behaviour. Specifically:

1) Sign-up with email, where I set the email also as an username

```
var newUser = User()
newUser.email = email
newUser.password = password
newUser.username = email
newUser.signup { [weak self] result in
     print("after sign-up: \(User.current)")
}
```
The ParseUser.current gets already updated in the keychain directly after sign-up (the email field is set):
>after sign-up: Optional(_User ({"username":"bb@bb.bb","email":"bb@bb.bb","objectId":"ZekaM6pAaI","updatedAt":{"__type":"Date","iso":"2021-07-14T07:42:46.237Z"},"createdAt":{"__type":"Date","iso":"2021-07-14T07:42:46.237Z"}}))

2) Then I save the rest of the fields based on what user has in the client app:
```
let user = User(user: self.userDataStore.currentPrivateUser)
user.save { result in
     switch result {
     case .success(let user):
         //device has current state
         print("user data from device were uploaded: \(user)")
    }
}
```
Even I am not setting the email field anymore (as it also does not show of in the uploaded struct):
>user data from device were uploaded: _User ({"pid":"pSwdtc0rht","gch":0,"minA":20,"objectId":"ZekaM6pAaI","updatedAt":{"__type":"Date","iso":"2021-07-14T07:43:13.166Z"},"sof":true,"maxD":20,"maxA":30}) 

The value for `email`, `username`, `emailVerified` fields are not anymore in ParseUser.current:
>current User: Optional(_User ({"pid":"pSwdtc0rht","gch":0,"minA":20,"objectId":"ZekaM6pAaI","updatedAt":{"__type":"Date","iso":"2021-07-14T07:43:13.166Z"},"sof":true,"maxD":20,"maxA":30}))

Maybe I understand it wrong and the `email`, `username`, `emailVerified` fields should not be saved in keychain at all. If so, please confirm, so that I will persist them in the local database

Thank you!

**Comment by cbaker6** [comment]
It’s probably your second coding block. I need to see your User(user:) initializer to understand what’s going on, but after sign in or login, all changes need to be made to User.current.

Also, you can perform all of step 2 in step 1 before signing up. The purpose of the sign up method you are using is to set your properties before signing up

**Comment by lsmilek1** [comment]
As the singInWithApple use these functions too and there the client does not know yet if it is new sign-up or login, I did split it into two. It helps a bit also in a re-try function later, should the process fail (I am creating Profile object directly after sign-up). Nevertheless with your great guidance I could reduce the code by a little and also the `User.current?.save { }` was indeed my mistake and reason why I have not seen the fields later. Now it works as intended! Thank you!
