### ISSUE TITLE
handling error in .saveAll()

### ISSUE THREAD

**Issue by lsmilek1** [parse-community/Parse-Swift#188]
I am learning how to efficiently save objects in batch and how to properly handle the errors and I noticed that the code is throwing only one error it gets from the batch. Here is a simple example and I try to upload 2 objects that are not yet on the server - one with objectId = nil and other with defined objectId:
```
    objects.saveAll { result in
            switch result {
            case .success(let saveResults):
                for result in saveResults {
                    switch result {
                    case .success(let savedObject):
                        savedObjects.append(savedObject)
                    case .failure(let error):
                        assertionFailure("error saving oblect: \(error.localizedDescription)")
                    }
                }
            case .failure(let error):
                self.handle(error: error, syncCategory: .inboxObjects, localId: "all")
            }
        } 
```

What is a bit confusing for me is that the `.success(let saveResults)` is also a `Result` but the failure in that result seems to not be reached as the .saveAll() catch the failure according to lines:

https://github.com/parse-community/Parse-Swift/blob/fca7ab159542f94b1295e2f24013489627890ae3/Sources/ParseSwift/Objects/ParseObject.swift#L258-L264

So in this example, because I use `allowCustomObjecId` the first object throws:
>ParseError code: missingObjectId

But the second object does not throw anything as the function does not come to the second object. What makes sense, as it tries to construct command and gets stopped by following guard (although I am getting lost in the code so I might be wrong):

https://github.com/parse-community/Parse-Swift/blob/fca7ab159542f94b1295e2f24013489627890ae3/Sources/ParseSwift/API/API%2BCommands.swift#L370-L372

My question would be then... If the `.saveAll()` fails due to one object in array, how can I find out what object it was so that I could exclude it from repeated upload or show warning in the UI?

**Comment by cbaker6** [comment]
It seems like you are hitting this particular situation because of what I posted here:

I recommend choosing one of the options I mentioned. The try is throwing correctly: https://github.com/parse-community/Parse-Swift/blob/fca7ab159542f94b1295e2f24013489627890ae3/Sources/ParseSwift/Objects/ParseObject.swift#L223

If you want to submit a PR and attempt to identify the specific object that throws, I will review it, but attempting to save mixed environment custom objectId's isn't recommended and not supported by the SDK.

**Comment by lsmilek1** [comment]
Do you mean what you posted [here](https://community.parseplatform.org/t/both-custom-and-generated-objectid-in-one-project/1812/2?u=lsmilek1), right?

I will switch to server generated Ids as I have basically only one class that got custom objectId to save few cloud code queries. Therefore I believe this situation won't happen anymore as I see that `createCommand()` and `updateCommand()` do not throw and `saveCommand()` has only the `.missingObjectId()`

https://github.com/parse-community/Parse-Swift/blob/fca7ab159542f94b1295e2f24013489627890ae3/Sources/ParseSwift/API/API%2BCommands.swift#L333-L363

As mixed generated+custom objectId is not supported, do you think that such enhancement would be of any use? I believe we can close this topic, otherwise it would make more sense to support the mixed environment also?

**Comment by cbaker6** [comment]
> Do you mean what you posted here, right?

Yes

> As mixed generated+custom objectId is not supported, do you think that such enhancement would be of any use?

Posting my answer [here](https://community.parseplatform.org/t/both-custom-and-generated-objectid-in-one-project/1812/4?u=cbaker6) for future reference.

> I believe we can close this topic

Feel free to close if you don't have any more questions.
