### ISSUE TITLE
Crash after calling subscribeCallback

### ISSUE THREAD

**Issue by SWereszczynski** [parse-community/Parse-Swift#193]
Hi,

In my project, I am currently changing `Parse-SDK-iOS-OSX` & `ParseLiveQuery-iOS-OSX` to `Parse-Swift  (1.8.6.)` client. 
Everything went very well, except for parse live query. Live query is working with `ParseLiveQuery-iOS-OSX` so I assume that parse server is configured properly and does not require any other configuration.

This is my parseSwift setup:

```
ParseSwift.initialize(applicationId: Constants.Parse.applicationId,
                      clientKey: Constants.Parse.clientKey,
                      serverURL: serverURL)
```

This is how i am trying to get subscribeCallback:

```
var subscription: SubscriptionCallback<PUser>?
        
func testLiveQuery() {
      guard let userId = PUser.current?.objectId else { return }

      let query = PUser.query("objectId" == userId)
      subscription = query.subscribeCallback
}
```
subscription is a global variable. Class that stores it, is not deallocated.

and after calling query.subscribeCallback I am getting `EXC_BAD_ACCESS`. On concurrent thread I found this:

<img width="1679" alt="Screenshot 2021-07-14 at 16 14 56" src="https://user-images.githubusercontent.com/6656674/125637767-fc5b3cd3-c11b-4e5f-b6ae-d754956c161b.png">

I also tested subscribeCallback with parse live query client with the same result.

When I want to create new parse live query client or use the one that exists I get the same error. So basically the error occurs when I want to do something with the parse live query client and not only when subscribing to the query.

Am I doing something wrong here?

**Comment by cbaker6** [comment]
Can you post your code for PUser?

**Comment by SWereszczynski** [comment]
Sure

```
import ParseSwift

struct PUser: ParseUser {
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
    var authData: [String : [String : String]?]?
    var username: String?
    var email: String?
    var emailVerified: Bool?
    var password: String?
    
    var emailVerifiedAuth0: Bool?
    var completedProfileSignup: Bool?
    var profileimage: ParseFile?
    var title: String?
    var fullname: String?
    var displayName: String?
    var website: String?
    var isOnline: Bool?
    var phoneNumber: String?
    var showAvailability: Bool?
    var notificationCount: Int?
    var currentCompany: ParseCompany?
}
```

Yes I saw playground examples. I used it in my project but with the same effect (crash)

**Comment by cbaker6** [comment]
This needs more information as there’s not enough to replicate your issue. Can you post the code for when you actually use subscribeCallback and what’s calling it, when the crash actually occurs, are you using any threads yourself in your app?, etc.

**Comment by cbaker6** [comment]
You can try the main branch that includes the fix in #195 to see if it works, but there won’t be a guaranteed fixed until you provide something that can be replicated or show more about your usecase

**Comment by SWereszczynski** [comment]
Ok thank you, I'll check it out.

By the way, I realized that it works on the simulator, but creshes on the real device. I'll let you know when I find something useful

**Comment by SWereszczynski** [comment]
I was able to run LiveQueryClient on real device only when: (even 1.8.6)

1. Deintegrate pods
2. Run .xcodeproj
3. Add parseSwift via SPM

Running .xcworkspace with ParseSwift as the only one pod in a project caused a crash

**Comment by cbaker6** [comment]
Can you show your code: https://github.com/parse-community/Parse-Swift/issues/193#issuecomment-880642366

**Comment by SWereszczynski** [comment]
AppDelegate:
```
import UIKit
import ParseSwift

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {

        guard let serverURL = URL(string: Constants.Parse.baseUrl) else {
            debugLog("❌ coudn't initialize parse due to missing server URL")
            return true
        }
        
        ParseSwift.initialize(applicationId: Constants.Parse.applicationId,
                              clientKey: Constants.Parse.clientKey,
                              serverURL: serverURL)

        PInstallation.current?.save(completion: { _ in })
        setupNavigation()

        return true
    }
    
    private func setupNavigation() {
        self.window = UIWindow(frame: UIScreen.main.bounds)
        window?.makeKeyAndVisible()
        let viewController = SplashViewController()
        window?.rootViewController = UINavigationController(rootViewController: viewController)
    }
}
```

SplashViewController:
```
final class SplashViewController: UIViewController {
    
    var subscription: SubscriptionCallback<PUser>?
    let query = PUser.query()
    
    init() {
        super.init(nibName: nil, bundle: nil)
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        subscription = query.subscribeCallback
        
        subscription?.handleEvent({ _, event in
            switch event {
            case .entered(let object):
                print("entered \(object)")
            case .left(let object):
                print("left \(object)")
            case .created(let object):
                print("created \(object)")
            case .updated(let object):
                print("updated \(object)")
            case .deleted(let object):
                print("deleted \(object)")
            }
        })
    }
}
```

**Comment by SWereszczynski** [comment]
podfile 

```
platform :ios, '13.0'
inhibit_all_warnings!

target 'XYZ' do

    use_frameworks!
    
    pod 'ParseSwift', '~> 1.8.6'

    target 'XYZTests' do
      inherit! :search_paths
    end
    
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
      end
    end
end
```

**Comment by SWereszczynski** [comment]
@cbaker6  it started to work. huh :) 

I am not 100% sure what was that, but it might be something connected to pods configuration or maybe old Parse-Live-Query client cached some data and there was a conflict. 

I was cleaning Xcode project, removing deliveredData, removing app, removing keychain, deintegrating pods and nothing works. 

Just wanted to let you know that it works. On Monday I will try to find the reason WHY 

Have a nice weekend!

**Comment by Tymoteusz24** [comment]
@SWereszczynski I am experiencing the same issue you mentioned. Have you found a reason of that? and how to fix it?

**Comment by SWereszczynski** [comment]
@Tymoteusz24 I think this issue was connected with having parse pod and dbdebugtoolkit pod as well. They don’t seem to be working together. Removing DBDebugtoolkit fixed the problem

**Comment by Tymoteusz24** [comment]
@SWereszczynski thx, However, I am not using DBDebugtoolkit. Maybe some other dependency cause that on my end.
I will try to migrate to the [redacted] and check if problem exists there
