### ISSUE TITLE
ParseFacebook sets accessToken instead of access_token

### ISSUE THREAD

**Issue by dblythy** [parse-community/Parse-Swift#201]
Hi!

Unless I'm doing something wrong, I'm unable to login with Facebook.

The issue is cause by the fact that Parse Server uses `access_token`, yet Parse Swift uses `accessToken`.

Failing test:

```
func testMakeDictionary() {
        let authData = ParseFacebook<User>
            .AuthenticationKeys.id.makeDictionary(userId: "testing",
                                                  accessToken: "testAccessToken",
                                                  authenticationToken: "testAuthToken")
        XCTAssertEqual(authData["id"],"testing")
        XCTAssertEqual(authData["access_token"],"testAccessToken")

        let secondAuthData = ParseFacebook<User>
            .AuthenticationKeys.id.makeDictionary(userId: "testing",
                                                  accessToken: nil,
                                                  authenticationToken: "testAuthToken")

        XCTAssertEqual(secondAuthData["id"],"testing")
        XCTAssertEqual(secondAuthData["token"],"testAuthToken")
    }
```

https://github.com/parse-community/parse-server/blob/9ea355b4635226ae4da17c8cc5fb0321e3fdec5e/src/Adapters/Auth/facebook.js#L24

**Comment by dblythy** [comment]
No matter what I tried, I would get Invalid OAuth from facebook.

After logging the graph request URL, it was:

`me?fields=id&access_token=undefined`

I also have FB Login successfully working on Parse Android.

By changing `AuthenticationKeys.accessToken.rawValue` (accessToken) to `CodingKeys.accessToken.rawValue` (access_token), the issue was resolved and login worked again.

**Comment by cbaker6** [comment]
Makes sense, can you create a PR with the fix?

**Comment by dblythy** [comment]
Can do!
