### ISSUE TITLE
Make it possible to create a user when there are custom required columns in Parse User Database

### ISSUE THREAD

**Issue by novemTeam** [parse-community/Parse-Swift#213]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).

### Current Limitation
You can't signUp a new User when there is a custom required field in the Database.

### Feature / Enhancement Description
Make it possible to add a custom variable to the signup function

### Example Use Case
```
User.signup(username: "", password: "", custom: ["myCustom" : "example"]) { result in
    <#code#>
}
```

### Alternatives / Workarounds
I think the only workaround is to make the column optional, and not required. But then you need to make two calls to the database, to update that value when the user is created.

[Stackoverflow question reference](https://stackoverflow.com/questions/68685989/how-to-create-a-new-user-with-custom-required-fields-in-parse)

**Comment by cbaker6** [comment]
This can be done by using the instance version of signUp in the [documentation](http://parseplatform.org/Parse-Swift/api/Protocols/ParseUser.html#/s:10ParseSwift0A4UserPAAE6signup7options13callbackQueue10completionyShyAA3APIV6OptionOG_So17OS_dispatch_queueCys6ResultOyxAA0A5ErrorVGctF). An example is shown in the playgrounds: https://github.com/parse-community/Parse-Swift/blob/38caf2e01c2adaf458825ff341d86979ff6b7243/ParseSwift.playground/Pages/4%20-%20User%20-%20Continued.xcplaygroundpage/Contents.swift#L144-L164

This was also answered here: https://github.com/parse-community/Parse-Swift/issues/149#issuecomment-846983523
