### ISSUE TITLE
urlError.errorCode -1011 and -1001 for LQ reconnection

### ISSUE THREAD

**Issue by lsmilek1** [parse-community/Parse-Swift#216]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).

### Current Limitation

At certain scenarios when:
- the internet connection is being held at 100% loss the LQ reconnection algorithm receives urlError.errorCode -1001 "The request timed out."
- sometimes when Parse Server restart is not fast enough, the reconnection algorithm receives urlError.errorCode -1011 "There was a bad response from the server."
what eventually falls through the error check on the line **539** not attempting again.
https://github.com/parse-community/Parse-Swift/blob/16cbcfacd44bbfb7db54183c4d2ccbc56df81d14/Sources/ParseSwift/LiveQuery/ParseLiveQuery.swift#L532-L556

### Feature / Enhancement Description

Adding the two mentioned error codes on the line **539** if not in conflict with other functionality

### Alternatives / Workarounds

Possible workaround is to call `.open()` in receiveDelegate:

```swift
    func received(_ error: Error) {
        print("received: \(error)")
        let code = (error as NSError).code
        if let parseError = error as? ParseError, parseError.message.contains("Reached max attempts") {
            print("LQ max attempts reached")
            if serviceAvailable {
                unsuccessfulAttempts = maxUnsuccessfulAttempts
                dataStore.mainTabBarController.parseServiceDidStopSync(success: serviceAvailable)
            }
            
        } else if code == -1011 || code == -1001, serviceAvailable {
            print("attempting open WS after 1011 || 1001 code")
            ParseLiveQuery.getDefault()?.open(isUserWantsToConnect: false, completion: { error in
                guard let error = error else {
                    // Resumed task successfully
                    return
                }
                print(error)
            })
        }
    }
```

As it is still out of my expertise it seems as rather unreliable workaround. It is triggering `.open()` still a long while after the max 20 attempts is reached and already twice ended up in `EXC_BAD_ACCESS (code=1, address=0x18)` on line **100**

https://github.com/parse-community/Parse-Swift/blob/16cbcfacd44bbfb7db54183c4d2ccbc56df81d14/Sources/ParseSwift/LiveQuery/LiveQuerySocket.swift#L95-L124

The `EXC_BAD_ACCESS (code=1, address=0x18)` is probably caused by multiple calls on `.open()` as the `receiveDelegate` becomes error for each query subscription. Refactoring the error handling with flag seems more reliable: 

```swift
    var attemptingOpenWS = false {
        didSet {
            //setting parse service availability here
        }
    }

    func received(_ error: Error) {
        guard serviceAvailable else { return }
        let code = (error as NSError).code
        let client = ParseLiveQuery.getDefault()
        if code == -1011 || code == -1001, !attemptingOpenWS {
            attemptingOpenWS = true
            self.unsuccessfulAttempts += 1 //<- counting to 3 and set serviceAvailable = false
            client?.open(isUserWantsToConnect: false, completion: { error in
                DispatchQueue.main.async {
                    self.attemptingOpenWS = false
                }
            })
        }
        if let parseError = error as? ParseError {
            if parseError.message.contains("Reached max attempts") {
                print("LQ max attempts reached")
                //setting parse service availability here
            }
        }
    }
```

**Comment by cbaker6** [comment]
Are you proposing to add the following to line 539?:

```swift
if urlError.errorCode == -1005 || urlError.errorCode == --1011 {
```

This may not solve the issue as "There was a bad response from the server." is a broad error that iOS, etc. provides.

I'll also mention that it's not intended for the SDK to handle every possible scenario which is why the delegates are there to allow the developer to make the decision on what to next in undefined scenarios

**Comment by cbaker6** [comment]
Can you submit a PR with this change and then I can take a look?

**Comment by lsmilek1** [comment]
I just tried it in separate fork and the workaround mentioned above seems to work more reliable. I must say I am still a little confused by the networking and probably later will find some other details, but for now I will stick with the current workaround. I apologise for any confusions!

**Comment by cbaker6** [comment]
Can you create a PR with the changes you made!

**Comment by lsmilek1** [comment]
Here it is, although it did not show much improvement when tested with Network conditioner blocking the connection 100%, but that is probably an extreme condition unnecessary to handle: 
https://github.com/parse-community/Parse-Swift/pull/217
