### ISSUE TITLE
Multiple apps are running the same ParseUser

### ISSUE THREAD

**Issue by novemTeam** [parse-community/Parse-Swift#223]
### Issue Description
I have an app that uses the ParseSwift SDK. I started a new app a week ago, and I noticed some issues with my other app. I started to look into it and I noticed that my first app had the User credentials of my second app.

This shouldn't happen in any case cause my apps have different Bundle Identifiers. They are not related in any case.

I also noticed that when I log in to one app, it asks me for my Keychain password on the other app. 

I do not have this issue on iOS

### Steps to reproduce
Create 2 projects with different Bundle Identifiers. Add the ParseSwift SDK

###  Environment

Parse Swift
- SDK version: `1.9.4`
- Operating system (iOS, macOS, watchOS, etc.): `macOS`
- Operating system version: `Monterey 12.0 Beta 6`

Server
- Parse Server version: `4.4.0`
- Operating system: `Back4App`

**Comment by cbaker6** [comment]
This is definitely possible because of the way the Keychain is setup. I will take a look at it soon.

**Comment by novemTeam** [comment]
@cbaker6  I don't exactly know how **Parse** handles stuff when it comes to the **Keychain**, but could it be an option to add a part of the **Parse** `applicationId` to the **Keychain** name which stores the _Parse User data_?

**Comment by cbaker6** [comment]
This [post]() states why the issue you mentioned is happening:

> macOS doesn’t have the concept of “local app” keychain [1]. Rather, each app has its own keychain search list and sees all the items in all the keychains in that search list. This search list typically includes the login keychain and the System keychain, but there can be other keychains inserted in the list, either by the user or programmatically. Such keychains can either be filed-based or backed by security token (like a smart card).
>Credentials within the keychain are governed by an access control list, so when you try to use the credential you may end up triggering a user authentication dialog.

Not sure of a solution yet…

**Comment by novemTeam** [comment]
I am currently doing it like this:

```
if error.code == ParseError.Code.invalidSessionToken {
     try? User.logout()
     NotificationCenter.default.post(name: Notification.flUserChanged, object: nil, userInfo: [:])
}
```

But this doesn't really fix the issue. It now just allows the user to login again. Not optimal at all.

**Comment by cbaker6** [comment]
For macOS, might be able to put the whole keychain in a key/value dictionary with the key being the app bundleID, which might solve part of the problem
