### ISSUE TITLE
Wrong image data when fetching image

### ISSUE THREAD

**Issue by vdkdamian** [parse-community/Parse-Swift#226]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Swift](https://github.com/parse-community/Parse-Swift/releases). 
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases).

### Issue Description
I am seeing issues when fetching an image. When i fetch an image for the first time, it loads the image corretly. But when it then tries to load for the second time, the image is broken. I looked at what the downloaded image looks like when opening in a text editor. 

I noticed it doesn't contain data, but a path. This is an example:
`file:\/\/\/var\/folders\/y5\/3qbps9t11cb2fz7lh1x8bw7w0000gn\/T\/com.app.myApp\/CFNetworkDownload_rDopeR.tmp`

My uploaded images in the Database are valid images. 

I want to point out that this way of fetching images always worked for me. It's since the Beta's that there is something wrong, but I don't find anything on the Apple Developer known issues page. 

### Steps to reproduce
This is an example of code I use.

```
let modelQuery =  Model.query()
modelQuery.find { result in
    switch result {
    case .success(let model):
        if let imageURL = model.image?.localURL {
            print("imageURL: \(imageURL)")
            if let imgData = try? Data(contentsOf: imageURL) {
                print("imgData: \(imgData)")
                print("imgData as string: \(String(decoding: imgData, as: UTF8.self))")
                self.imageData = imgData
            }
        } else {
            model.image?.fetch(completion: { result in
                switch result {
                case .success(let fetchedImage):
                    if let localImageUrl = fetchedImage.localURL {
                        print("localImageUrl: \(localImageUrl)")
                        if let imgData = try? Data(contentsOf: localImageUrl) {
                            print("imgData: \(imgData)")
                            print("imgData as string: \(String(decoding: imgData, as: UTF8.self))")
                            self.imageData = imgData
                        }
                    }
                case .failure(_):
                    break
                }
            })
        }
        self.model = model
    case .failure(_):
        break
    }
}
```

This is my log:

<img width="1606" alt="Schermafbeelding 2021-09-06 om 17 25 04" src="https://user-images.githubusercontent.com/44820440/132238974-746cf860-a29b-4f90-93cb-1287b2a16526.png">

### Actual Outcome
`file:\/\/\/var\/folders\/y5\/3qbps9t11cb2fz7lh1x8bw7w0000gn\/T\/com.app.myApp\/CFNetworkDownload_rDopeR.tmp`

### Expected Outcome
Image data

### Failing Test Case / Pull Request

- [ ] 🤩 I submitted a PR with a fix and a test case.
- [ ] 🧐 I submitted a PR with a failing test case.

###  Environment
Parse Swift
- SDK version: `1.9.8`
- Operating system (iOS, macOS, watchOS, etc.): `iOS, macOS`
- Operating system version: `iOS 15 Beta 8, Monterey 12.0 Beta 6`

Server
- Parse Server version: `4.4.0`
- Operating system: `Back4App`

### Logs
```
localImageUrl: file:///Users/name/Library/Containers/com.app.myApp/Data/Library/Application%20Support/parse/com.app.myApp/Downloads/d48e0511e7660ab8e59fa2bb74cd48a4_1600.png
imgData: 123 bytes
imgData as string: "file:\/\/\/var\/folders\/y5\/3qbps9t11cb2fz7lh1x8bw7w0000gn\/T\/com.app.myApp\/CFNetworkDownload_rDopeR.tmp"
```

**Comment by cbaker6** [comment]
@novemTeam can you fill out the complete issue template? It looks like you removed information

**Comment by novemTeam** [comment]
@cbaker6 I updated it. I still left out the Database info because I am just using Back4App

**Comment by cbaker6** [comment]
What happens when you use the latest version of Xcode 12? If this only occurs in Xcode 13 beta, it's probably not worth a fix until 13 goes Gold. If you can find some documentation that states Xcode 13 is changing the way downloaded data is handled, then I can take a look to see how to adjust.

**Comment by novemTeam** [comment]
It did always work in Xcode 12.

**Comment by cbaker6** [comment]
PR #212 uses Xcode 13 beta 5. I believe there are test cases that cover this scenario that don't fail on Xcode 13. Can you look through them to verify? https://github.com/parse-community/Parse-Swift/blob/main/Tests/ParseSwiftTests/ParseFileTests.swift. If you find that something is missed, you can open a PR to add the test case.

**Comment by novemTeam** [comment]
@cbaker6 Sorry for the late response, kinda busy. I'll take a closer look this weekend.

**Comment by novemTeam** [comment]
@cbaker6  I was unable to run the Tests because of lack of experience. But I do indeed think there should be a test to check if the file at `.localURL` is indeed a file.

Maybe something like this? I don't know if there is a better way to check if it is a image. 

```
do {
     let data: Data = try Data(contentsOf: fetchedFile2.localURL!)
     XCTAssertGreaterThan(data.count, 200)
} catch {
     XCTFail("Should get data. Error \(error)")
     return
}
```

I also tried a few more things. I ran my project with Xcode 13 on my friends iPhone, and had the same issue. The images don't download correctly.

It also changes, 1/10 times it downloads correctly, the other times i get images with a path in it. See the screenshots

Here are some more screenshots 

<img width="128" alt="Schermafbeelding 2021-09-12 om 16 05 23" src="https://user-images.githubusercontent.com/44820440/132990745-e89d5151-d84f-4ec5-93da-b931338ab21e.png">
<img width="794" alt="Schermafbeelding 2021-09-12 om 16 05 52" src="https://user-images.githubusercontent.com/44820440/132990747-c321a9fb-6c48-4f95-a1ae-3da3ab79767d.png">

**Comment by cbaker6** [comment]
I checked this in Playgrounds: https://github.com/parse-community/Parse-Swift/blob/1a30fb60191b41b4d4fbb5c5bf528d0277fb5c69/ParseSwift.playground/Pages/9%20-%20Files.xcplaygroundpage/Contents.swift#L42-L97

As well as in a sample I made that heavily uses ParseFile for pictures: 

I didn't see the issue you mentioned and everything seems to be working correctly. I recommend looking into other areas of how you are handling files in your app or maybe your server configuration.

**Comment by cbaker6** [comment]
You should also checkout your cache policy: https://github.com/parse-community/Parse-Swift/blob/1a30fb60191b41b4d4fbb5c5bf528d0277fb5c69/Sources/ParseSwift/Parse.swift#L70-L74

**Comment by novemTeam** [comment]
@cbaker6 is this something I can change when using Back4App?

Also, did you run your test on iOS 15? Because I really can't see what I could be doing wrong when downloading images... 

I just followed the documentation

**Comment by cbaker6** [comment]
> @cbaker6 is this something I can change when using Back4App?

I’m not sure how Back4app works as I self-host, but if you have access to your index.js file you can add it.

> Also, did you run your test on iOS 15? Because I really can't see what I could be doing wrong when downloading images...

My tests in https://github.com/parse-community/Parse-Swift/issues/226#issuecomment-917660569 Used iOS 15 specifically and I didn’t have any issues.

**Comment by novemTeam** [comment]
```
if let iconIcon = icon.iconImage {
    iconIcon.fetch { result in
        switch result {
        case .success(let fetchedFile):
            print("fetchedFile.data: \(String(describing: fetchedFile.data))")
            if let dataFromWebsiteIcon = try? Data(contentsOf: fetchedFile.localURL!) {
                print("dataFromWebsiteIcon: \(dataFromWebsiteIcon)")
                let websiteIcon = websiteFolder.appendingPathComponent("Icon.png")
                if fileManager.fileExists(atPath: websiteIcon.path) {
                    do {
                        try dataFromWebsiteIcon.write(to: websiteIcon)
                    } catch {
                        assertionFailure("Error writing Icon image: \(error)")
                    }
                } else {
                    fileManager.createFile(atPath: websiteIcon.path, contents: dataFromWebsiteIcon, attributes: nil)
                }
            } else {
                print("Error: couldn't get data from file.")
            }
        case .failure(let error):
            assertionFailure("Error fetching: \(error)")
        }
    }
}
```

I get these logs: 

```
fetchedFile.data: nil
dataFromWebsiteIcon: 137 bytes
```

**Comment by cbaker6** [comment]
This is how I download files: 

https://github.com/netreconlab/SnapCat/blob/8218047ef311c7610da8f4cde6db0dd1108c0047/SnapCat/Utility.swift#L28-L44

**Comment by novemTeam** [comment]
Update: I changed my `App Groups` path name and then it downloaded my images again in a correct way. If I then delete the folder with the images, and redownload the icons, it's broken again.

So I am able to download images the first time, but then there is something wrong with the data at `fetchedFile.localURL!` if I read the data from this, I get that path, and not the image

**Comment by novemTeam** [comment]
@cbaker6 Your code returns a UIImage, but I need the data.
I tried a part of your code:

```
if let path = image.localURL?.relativePath,
   let image = UIImage(contentsOfFile: path) {
    completion(image)
} else {
    completion(defaultImage)
}
```

then changed it to this : 
```
if let path = image.localURL?.relativePath {
    if let dataImage = try? Data(contentsOf: path) {
        print("dataImage: \(dataImage)")
    } else {
        print("No Image")
    }
} else {
    print("No Image")
}
```

This also printed me that path, and not an image. (It printed 137 bytes, so I know this is that path line. It's way to small to be my image)

**Comment by novemTeam** [comment]
**Update:**
I created a new project really quick, I have the same issue with this project

**Comment by novemTeam** [comment]
I created a new App in Back4App, I connected the Test app to it, it's the same issue.

You can download the file.  Setup the `App Groups` capabilty in Xcode, add this path in all the targets: 
<img width="404" alt="Schermafbeelding 2021-09-17 om 19 21 45" src="https://user-images.githubusercontent.com/44820440/133828865-22fc235c-b340-4298-926b-53e9a4bf42f2.png">

Then run the mac app. Navigate to this path:
/Users/**_user_**/Library/Group Containers/group.test.ParseImageTest/NVMParseImageTest

You should see a folder "WebsiteIcons". The first time it downloads the icon, it will show the icon in the "WebsiteIcons" folder, in "acv-online.be". 
If you then remove the folder "WebsiteIcons", and re-run the app. You should see the issue. This is where it always goes wrong with me. You'll see there is a file in the folder, but it will be an invalid image.

Hope this helps. 


[ParseImageTest.zip](https://github.com/parse-community/Parse-Swift/files/7187352/ParseImageTest.zip)

**Comment by cbaker6** [comment]
What happens when you don’t add “App Groups”?

**Comment by novemTeam** [comment]
@cbaker6 I disabled `App Groups`, changed the paths to the default app documents folder, still have the same issue.

If you have time, can you check the Xcode Test project I attach? Hopefully you can recreate the issue. 

[ParseImageTest 2.zip](https://github.com/parse-community/Parse-Swift/files/7191987/ParseImageTest.2.zip)

**Comment by cbaker6** [comment]
I will not ba able to test out your zip files. Instead, you should attempt to make your case repeatable as a test case and submit the PR.

you also mentioned your server is 4.4.0, does the problem still persist on the latest server 4.10.3?

**Comment by novemTeam** [comment]
These are the only ones I can set, I tried 4.2.0, 4.4.0, 4.5.0. None of them work. I don't know why you don't even bother try Testing my zip files... It was a project with all the keys set up, but OK. 

For me the issue is repeatable. I tried everything.

<img width="2339" alt="Schermafbeelding 2021-09-19 om 15 36 37" src="https://user-images.githubusercontent.com/44820440/133929582-4908e64b-fa81-49ef-a870-eea7bf9e200d.png">

**Comment by novemTeam** [comment]
I went to the `fetchedFile.localURL` path on mac it clearly shows that the image is damaged when downloaded here, so no offense, but I don't think that has anything to do with my code. 

Since I just read the contents of the file from this path and write the to my desired location, I think it must have something to do when downloading the image from the ParseSwift SDK.

The image below is in dutch, but it says that the image is damaged. As mentioned before, there is just a path in this file.
I tried 3 parse server versions, so I don't think the issue is from there neither. 
![Schermafbeelding 2021-09-19 om 15 44 47 (2)](https://user-images.githubusercontent.com/44820440/133929991-f0dbfc67-91a1-4c67-9549-e77f47cfe8da.png)

**Comment by Xevro** [comment]
I tested the zip project on my computer and I had the same issue.
The first time the image was downloaded correctly, after deleting the folder it downloaded the image but it was damaged and could not be opened.

Xcode 13-beta-5
MacOS Monterey 12.0 bèta (21A5506j)

**Comment by cbaker6** [comment]
As I’ve stated previously https://github.com/parse-community/Parse-Swift/issues/226#issuecomment-922471294, the zip files don’t mean much. It seems the issue may be something with “app groups” or even how you are using app groups and files. I don’t see this issue at all with the apps I pointed to using Xcode beta 5 or the RC. As I’ve also stated https://github.com/parse-community/Parse-Swift/issues/226#issuecomment-913751881, you testing on a beta when the real version isn’t even out yet. Whatever the issue is, you need to create a failing testcase and a PR (as the issue template states) in order for it be addressed. If either of you submit a PR in the correct format, it will be reviewed.

**Comment by cbaker6** [comment]
Also, both of you are mentioning that you are not only testing on a beta Xcode, you are even testing on a beta Mac OS, Monterey. There’s not even CI for this in GitHub Actins. If you find a reasonable solution, add the correct test cases that don’t break the current CI, then I’ll review the PR.

**Comment by novemTeam** [comment]
@cbaker6 iOS 15 launched yesterday, and Xcode is also out of Beta. 

I found that it has nothing to do with App Groups. I will take a look at it next week. If I find a fix, I'll create a PR.

I also have this issue on both macOS as iOS.

**Comment by cbaker6** [comment]
> @cbaker6 iOS 15 launched yesterday, and Xcode is also out of Beta.
> 
> I found that it has nothing to do with App Groups. I will take a look at it next week. If I find a fix, I'll create a PR.
> 
> I also have this issue on both macOS as iOS.

You tested on macOS Big Sur or Monterey? Monterey is still in beta

**Comment by cbaker6** [comment]
In addition, have you tried your apps on “real” iOS 15 devices. Using the released version of iOS 15, I don’t have any issues with posting and fetching photos in the apps I mentioned above. 

I recommend checking and clarifying if you are 1) Running Monterey beta 2) running it on an Intel or M1 machine 3) Are your issues present on Big Sur 4) Do you have issues running on real iOS 15 devices?

I personally don’t develop on a beta macOS and I cannot replicate any of the issues mentioned on anything that is actually released, nor can the CI replicate it. If you choose to develop on beta software you are choosing to encounter the risk of buggy behavior and may need to modify code to support.

**Comment by novemTeam** [comment]
@cbaker6 Yes its on Monterey. But I actually started noticing the issue on the Beta software of iOS 15. 

I'll know more next week to see if it still persists on the official version of iOS 15.

Also want to mention that this issue is not a really big problem for my app. I started recreating my app in Swift instead of objective c. So i then knew that ParseSwift was in a really early stage so things could fail. 

I also decided to target iOS 15 and macOS Monterey since Swift and SwiftUI got some important/big improvements. 

So the version I am developing now is not in production yet. 

So next week I'll know more and investigate the issue more and keep you informed.

**Comment by novemTeam** [comment]
`CFNetworkDownload_dqx5Vh.tmp` these files, are they created by Apple or by Parse? Cause I managed to locate them, and I saw that the first time downloading the image, this file looks like **Screenshot 1**, and then the second time, it look like **Screenshot 2**. So is it possible that this is an Apple issue?

To find these files I needed to dig in hidden folders, and found out that these are the folders where Apple caches things. 
I think I need some help to find the real issue here.

**Comment by novemTeam** [comment]
In the File `API+Command`, function `downloadFile(_:)` I changed a line of code in order to be able to inspect the cache files. 
I changed it from 
`try FileManager.default.moveItem(at: tempFileLocation, to: fileLocation)`
to
`try FileManager.default.copyItem(at: tempFileLocation, to: fileLocation)`

I made a video to highlight the problem, maybe this helps you understand a little bit better.

[Dropbox video url](https://www.dropbox.com/s/yutvm0w1q2vtxdw/ParseIssue%20LQ.mov?dl=0)

**Comment by cbaker6** [comment]
Anything that begins with “CF” is always apple. I’m not sure what that .tmp does is used for.

**Comment by novemTeam** [comment]
Okay, I'll reach out to Apple. I'll keep you posted

**Comment by novemTeam** [comment]
@cbaker6 So I got a response from Apple, and it seems like it is an issue from the Parse framework.

![image](https://user-images.githubusercontent.com/44820440/139792890-9f934b5d-4829-4fb8-b68b-01bc52c2c0cd.jpeg)

The link they added to their response:
[URLSession](https://github.com/parse-community/Parse-Swift/blob/85366e63118a0907e798cabeee211260f168b558/Sources/ParseSwift/API/URLSession%2Bextensions.swift#L112)

I'll look more at this when I get home from work, but if you see something already, let me know.

**Comment by cbaker6** [comment]
I thought I found something wrong, but I was mistaken. 

When you are originally saving your ParseFiles, do the names have extensions? For example, `.txt`? It's possible you uploading your files to your server incorrectly. If you store them as data you need to know how to convert them on your client. I won't be able to tell if there's an issue until I'm able to test on a Monterey machine, but it seems out this works fine for Big Sur and before. The `.tmp` files are created by the OS during the download, the SDK simply moves that file after download so the OS doesn't delete it and converts it to the extension you named the file with.

**Comment by novemTeam** [comment]
> When you are originally saving your ParseFiles, do the names have extensions? For example, `.txt`? It's possible you uploading your files to your server incorrectly. If you store them as data you need to know how to convert them on your client. I won't be able to tell if there's an issue until I'm able to test on a Monterey machine, but it seems out this works fine for Big Sur and before. The `.tmp` files are created by the OS during the download, the SDK simply moves that file after download so the OS doesn't delete it and converts it to the extension you named the file with (the OS actually converts by renaming the file).
> 
> If you didn't add an extension and the server couldn't determine it for you, you will need to handle the conversion yourself on the client side.

I think you might be on to something. I have files that are uploaded with the ParseSwift SDK, and they work fine. The problem I am noticing is indeed with files I uploaded manually in the database.
But I upload every image as `Icon.png`. So the extension is defined in the name.

![Schermafbeelding 2021-11-02 om 17 10 32](https://user-images.githubusercontent.com/44820440/139898580-1433fdf4-0aa5-4b45-8502-a05d8cec3b0e.png)

If I download it from the database, it looks like this: 
<img width="469" alt="Schermafbeelding 2021-11-02 om 17 12 27" src="https://user-images.githubusercontent.com/44820440/139900114-1370af53-1585-4e07-821d-b9bc34f73465.png">

**Comment by cbaker6** [comment]
I updated one of my systems to Monterey and all of the [ParseFileTests.swift](https://github.com/parse-community/Parse-Swift/blob/main/Tests/ParseSwiftTests/ParseFileTests.swift) passes.

You can test the `ParseFileTests` on your system, if it passes (which it should), then the problem is most likely something you are doing on your end and not the SDK.

**Comment by novemTeam** [comment]
Hmm, I literately have no idea where I could be doing something wrong

**Comment by cbaker6** [comment]
> I think you might be on to something. I have files that are uploaded with the ParseSwift SDK, and they work fine. The problem I am noticing is indeed with files I uploaded manually in the database.
But I upload every image as Icon.png. So the extension is defined in the name.

If you are uploading manually through the dashboard maybe the dashboard doesn't send the same info the Swift SDK sends when saving the photo. If so, it can possibly be a dashboard bug or, you are not uploading properly.

**Comment by novemTeam** [comment]
> If you are uploading manually through the dashboard maybe the dashboard doesn't send the same info the Swift SDK sends when saving the photo. If so, it can possibly be a dashboard bug or, you are not uploading properly.

Yes, maybe, but do you have an idea why the first download does work, but on second attempt not?

**Comment by cbaker6** [comment]
> Yes, maybe, but do you have an idea why the first download does work, but on second attempt not?

I actually might... This may be a small bug related to caching. When you call your second fetch, do:

```swift
let fetchedFile2 = try parseFile.fetch(options: [.cachePolicy(.returnCacheDataDontLoad)])
```

and tell me if it works. I'll post a potential patch soon for you to test.

**Comment by vdkdamian** [comment]
I'll try out [#272](https://github.com/parse-community/Parse-Swift/pull/272) for some users in a few days. But it seems like this fixed this issue

**Comment by cbaker6** [comment]
If a developer comes across this thread and is using Swift SDK < 2.1.0, the workaround was mentioned in https://github.com/parse-community/Parse-Swift/issues/226#issuecomment-913864845 and https://github.com/parse-community/Parse-Swift/issues/226#issuecomment-958012896. Essentially change the cache policy during your file fetch:

```swift
let fetchedFile2 = try parseFile.fetch(options: [.cachePolicy(.reloadIgnoringLocalCacheData)])
```

**Comment by vdkdamian** [comment]
@cbaker6 Is it correct that I need to add the `(options: [.cachePolicy(.reloadIgnoringLocalCacheData)])` manually after my fetches?

I notice that unchanged file on the server return my corrupted data if I `.fetch` them for a second time.

Changing it to `.fetch(options: [.cachePolicy(.reloadIgnoringLocalCacheData)])` fixes this, but I want to ask if it's correct that developers need to do this manually?

**Comment by cbaker6** [comment]
You would add `.fetch(options: [.cachePolicy(.reloadIgnoringLocalCacheData)])` if you don't want to use the cached file, but in most cases, the default is to use the caching policy sent from the server containing the file. If your app cached the file before the bug fixes, you might want to delete the cache and see if it works after without adding the `.reloadIgnoringLocalCacheData` option

**Comment by vdkdamian** [comment]
> If your app cached the file before the bug fixes (`v2.2.1`), you might want to delete the cache and see if it works after without adding the `.reloadIgnoringLocalCacheData` option

Then it's still a bug. I had a new file that got uploaded via ParseSwift, and on another device, the first download is fine. But on second attemp it's the corrupted filedata again.

Adding the custom cachePolicy fixes the issue for me. But I don't know if you think there might be a bug somewhere else?

**Comment by vdkdamian** [comment]
I think nobody has this issue because they are not fetching a static file multiple times. But in my case, I need it to be able to fetch a file multiple times. 

It looks like if the file is already downloaded, it takes the path to that cached file and puts in the file Parse creates. But this only happens if the filename is the exact same, and if it already cached that file via `.fetch`. 

I don't know i you think this is a issue, or worth spending time at. But for me it's fixed by adding the cachePolicy. Maybe for developers with the same issue?

**Comment by cbaker6** [comment]
> Adding the custom cachePolicy fixes the issue for me. But I don't know if you think there might be a bug somewhere else?

I've tested it and don't see any issues. If you find a bug, you can open an issue. I recommend you look at my earlier comment https://github.com/parse-community/Parse-Swift/issues/226#issuecomment-917667292 and if you can't find a bug or fix your problem, then add the cache policy `.reloadIgnoringLocalCacheData` option which will re-download the file everytime you fetch instead of caching.

**Comment by cbaker6** [comment]
> It looks like if the file is already downloaded, it takes the path to that cached file and puts in the file Parse creates. But this only happens if the filename is the exact same, and if it already cached that file via .fetch.

This should work, fetching a file with the same url should yield the same file, so it's better to use cache. If you are changing the file, it should have a different url than the previous file.

**Comment by cbaker6** [comment]
Looking at your old screenshots in https://github.com/parse-community/Parse-Swift/issues/226#issuecomment-929592132, the first file has some data, though I don’t know what it is, I will assume it’s correct. The second time you attemp to fetch the same file it should hit the cache and shouldn’t produce a .tmp file (unless you changed the url or filename). It should point to the parse directory containing the first file where it contains the correct file name and extension from the first download. The data contained in that file should be the exact same data from the first .tmp file.

**Comment by vdkdamian** [comment]
> It should point to the parse directory containing the first file where it contains the correct file name and extension from the first download. The data contained in that file should be the exact same data from the first .tmp file.

That's not the case with me. It clearly show that it does something which results in the file data being a path instead of the actual data. 

After work, I'll try to look where I can change the file from your [#226 comment](https://github.com/parse-community/Parse-Swift/issues/226#issuecomment-917667292) on back4app. Maybe that's the issue, I'll see...

**Comment by cbaker6** [comment]
I wouldn’t say it’s clear:

1. You haven’t shown updated screenshots with the latest version 
2. You mentioned it only happens with photos you updated manually through the dashboard. 
3. You mentioned it worked on previous OS’s
4. No one else has reported the issue. I use files extensively in a couple of my apps and fetch from cache for a better user experience and don’t see the issue.
5. You also seem to do something different with the data in file 

To me, you have a lot of moving parts that need to be debugged. If you use your app with another SDK that uses cache, that might provide some insight.

**Comment by cbaker6** [comment]
Be sure to clear you cache, `ParseSwift.clearCache()`. The OS chooses to use the cache based on the request, meaning it may not choose to use cache. Just in case the OS choses not to cache you can check to see if the file is already downloaded and use it like I did in my repo: https://github.com/netreconlab/SnapCat/blob/f8fdcc0e039ea8ff62f9f0884804f8ee90575a0b/SnapCat/Utility.swift#L24-L60
