### ISSUE TITLE
Saving a Object with an Array of Files holds UI thread

### ISSUE THREAD

**Issue by dblythy** [parse-community/Parse-Swift#229]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description

Saving an object with an array of PFFiles halts UI.

### Steps to reproduce

1. Create a struct with [ParseFile]
2. Create a new object and set files
3. Calling `object.save` will hold the main thread

Here is my code:
```
        event.images = images
        Utils.loading(message: "Saving event")
        event.save { result in
            switch result {
            case .success(_):
                Utils.done()
            case .failure(let error):
                Utils.error(error: error)
            }
        }
```

https://user-images.githubusercontent.com/4974769/132307398-37f71f26-d457-45fe-9439-53516befb24e.mov

### Actual Outcome

UI thread is held

### Expected Outcome

UI not to hold.

### Environment

Client
- Parse Swift SDK version: `1.9.4`
- Xcode version: `12.4`
- Operating system (iOS, macOS, watchOS, etc.): `iOS`
- Operating system version: `14.4`

Server
- Parse Server version: `master`
- Operating system: `Ubuntu`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `AWS`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.5`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Atlas`

**Comment by cbaker6** [comment]
Tested the issue in Swift playgrounds and it seems to be fixed. If the issue still persists, feel free to reopen.

**Comment by dblythy** [comment]
Thank you for addressing this quickly @cbaker6! I'll check it out tomorrow. Much appreciated!
