### ISSUE TITLE
Verification Emails are triggered every time User.current is saved

### ISSUE THREAD

**Issue by dblythy** [parse-community/Parse-Swift#239]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description

Parse Swift triggers email verification whenever `User.current?.save` is called.

### Steps to reproduce

1. Turn `verifyUserEmails` on.
2. Update any field on `User.current`
3. Check emails

### Actual Outcome

Emails are sent every time user is updated

### Expected Outcome

Emails to only send on signup, or email update, as per the SDK.

Specifically, the issue seems to be related to here o the server:

```js
RestWrite.prototype._validateEmail = function () {
 if (!this.data.email || this.data.email.__op === 'Delete') {
    return Promise.resolve();
  } 
```

For the JS SDK, `this.data.email` is undefined on any update. For Parse Swift calls, this.data.email is passed.

### Environment

Client
- Parse Swift SDK version: `1.9.10`
- Xcode version: `10.15.7`
- Operating system (iOS, macOS, watchOS, etc.): `iOS`
- Operating system version: `14.3`

Server
- Parse Server version: `Master (around 4.5.0`
- Operating system: `macOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `mongoDB`
- Database version: `4.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Atlas`

**Comment by cbaker6** [comment]
In the JS SDK, are you able to show where the following occurs:

> For the JS SDK, this.data.email is undefined on any update

That will provide some guidance on where this is happening on the client level, or if the server is actually handling it.

**Comment by dblythy** [comment]
I'm probably not familiar enough with the JS SDK to point where exactly it happens, but my understanding is that `object.set(key)` add the `key` to a list of pending OPS, which is then sent to the server, and these specific keys are set. I detected this by console.logging `this.data` in `RestWrite.js`. As far as I can tell in my PR, Parse Swift sends the whole body to the server.

**Comment by dblythy** [comment]
Another way to replicate this is to have a simple `beforeSave` trigger on `Parse.User`, and log `object.dirtyKeys()`. Even with the code `User.current?.save{ result in }`, `dirtyKeys` is the entire struct for Parse Swift.

**Comment by cbaker6** [comment]
> I would assume it's _getSaveJSON, which determines what JSON objects need to be sent to the server, only if they have been mutated.

I see, this may be the case. Since ParseSwift uses structs it doesn't have getters/setters and doesn't have a notion of dirty. If the PR I just openned doesn't work, I think I may have a solution.

**Comment by dblythy** [comment]
The issue still occurs on the branch too.

EmailVerified isn't showing up in either master or this branch as a dirtyKey, the dirtyKeys are set as `'username', 'email', 'firstName', 'lastName', 'ACL'`.

I'm assuming the emailVerified is being triggered by server thinking `email` is being changed

**Comment by dblythy** [comment]
Some alternative options to make sure dirtyKeys is passed properly:

1. a cloud function that reverts database ops if original.get(key) === object.get(key)
2. special internal handling for ParseSwift to manage these dirtykeys 

Option 1 would require every class which is used in Parse Swift to have a beforeSave trigger. Option 2 would require server changes and no Parse Swift changes.

**Comment by cbaker6** [comment]
@dblythy thanks for reporting! I believe the linked PR fixes the issue you found.
