### ISSUE TITLE
Partially updating an object sends the full object to the server

### ISSUE THREAD

**Issue by dblythy** [parse-community/Parse-Swift#242]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description

When fetching a saved object and then calling `.save`, all keys are marked as `dirty` and saved to the backend, causing unnecessary traffic and database ops. 

### Steps to reproduce

1. Fetch an existing object
2. Have a Parse Cloud beforeSave trigger that logs `object.dirtyKeys()`. 

### Actual Outcome

All fields are dirty. 

### Expected Outcome

No fields should be dirty unless mutated. 

### Environment

Client
- Parse Swift SDK version: `1.9.10`
- Xcode version: `10.15.7`
- Operating system (iOS, macOS, watchOS, etc.): `iOS`
- Operating system version: `14.7`

Server
- Parse Server version: `4.5.0`
- Operating system: `macOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `localhost`

Database
- System (MongoDB or Postgres): `mongodb`
- Database version: `4.2`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Atlas`

**Comment by cbaker6** [comment]
Posting my responses to your comments in #241:

> So there's no way to only send mutated keys to the server using Parse Swift?

There are a few ways, but the developer has to take some action here. For example, developers can add the following method (or a similar one) to their `ParseObject`'s:

```swift
struct MyUser: ParseUser {
    var authData: [String: [String: String]?]?
    var username: String?
    var email: String?
    var emailVerified: Bool?
    var password: String?
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?

    // method that creates empty versions of self
    func emptyObject() -> Self {
        var object = Self()
        object.objectId = objectId
        return object
    }
}
```

Then add properties what will be mutated and saved. Only these get sent to the server:

```swift
var myObject = MyUser()
myObject.email = "myNewEmail@parse.com"
myObject.save { _ in }
```

This also can be easily achieved by using `ParseOperation`: https://github.com/parse-community/Parse-Swift/blob/ddcf35f54365397f75068744e6ff975e875dd73a/Tests/ParseSwiftTests/ParseOperationTests.swift#L100-L103

These examples should address most of your comments below:

> Just a quick comment - whilst this will likely fix the issue, the core problem of `dirtyKeys` still remains. This is problematic because:
> 
> * unnecessary data is sent to parse server, which in developing countries may result in unbearable latency, or, on a high scaled system, result in additional data expenses
> * unnecessary database ops will happen when no data is actually changing
> * Cloud functions will tell developers to assume keys are dirty when they are not
> * email being set to dirty is just an example of an unpredictable consequences of all the keys being sent, there could be other cases which we don’t know about.

When it comes to:
> @cbaker6 is there a way we could perhaps store the serverData from the initial fetch of the object, and then compare changes to keys onSave if we can’t directly listen to property changes on a struct?

"Listening to property changes" is typically associated to `reference types` or "instances of Classes" in many languages, not just Swift. Most/All of the Parse SDK's use "classes" with the exception of the Swift SDK. `value types` or "structs" don't have this ability and are one of the distinct difference between a `struct` and a `class`. The Swift SDK doesn't need to listen property changes and instead should use a method similar to what I mentioned at the beginning of this comment. It's important not to think or compare of the Swift SDK to the other SDKs as it has a completely different design philosophy. [Flo's comments and thread](https://github.com/parse-community/Parse-Swift/issues/3#issuecomment-328351357) provide good insight into the design philosophy and the reasoning. For these reasons, the Swift SDK can exist with zero dependencies, not run into the threading issues the other client SDKs encounter, along with having `ParseObject`'s play nicely with MVVM and SwiftUI (from what I see `reference types` is what's causing a major barrier when using MVVM in the [issues](https://github.com/parse-community/Parse-SDK-JS/issues/1316#issue-829292548) you and others mention with the JS SDK).

**Comment by dblythy** [comment]
Thank you for your reply here @cbaker6.

In my view, it shouldn't be up to the developer to custom code a solution for the SDK to work as expected with Parse Server. I understand that there are tradeoffs with the current implementation, but I still think it's problematic that at the end of the day, Parse Server has no distinction for `dirtyKeys` in the Swift SDK, which is different from any other SDK.

Although you've said in terms of philosophy it's not valuable to compare across SDKs, I think from both a developer and Server team perspective, it would be expected that beforeSave functions would function the same, regardless of the SDK. It just seems a little odd to me to say "if you use `.dirtyKeys` in Parse Cloud, make sure you customise ParseSwift so it doesn't send all the data".

And on the race condition, let's say you have an object that is being managed by two Swift SDK users at the same time. They both fetch the object at the same time. 

The object looks like:

```js
{
   foo: "bar",
   yolo: "xyz"
}
```

Both users query this object at the same time.

User one calls:

`obj.foo = "aaa"`, and then saves.

A few minutes later, user two calls:

`obj.yolo = "aaa"`, and then saves.

The result that will be saved in Parse Server would be:

```js
{
   foo: "bar",
   yolo: "aaa"
}
```

As all keys saved by user two will be overriden. If this was any other SDK, the result would be:

```js
{
   foo: "aaa",
   yolo: "aaa"
}
```

Meaning again, if you have a multi tenant solution (iOS App, Web App, Android App), using the Swift SDK in its purest form could be problematic and deliver unexpected results.


Could we perhaps store a clone of the fetched object somewhere, and then compare keys as part of the save operation? So when building the save operation, Parse Swift runs something like:

```js
const fetchedObj // this has the fetched state
const updatedObj // this has all the user mutations
const bodyToSend = {};
for (const key in updatedObject) {
  if (fetchedObj[key] !== updatedObj[key]) {
    bodyToSend[key] = updateObj[key]
  }
}
```

Forgive the JS as said I am not a Swift dev 😊

**Comment by dblythy** [comment]
If this technically can't be solved on the SDK side because the use of `struct`, maybe the solution is to override `dirtyKeys` in `RestWrite` if `object.key === original.key`. I've discussed this with @mtrezza, however he has stated that believes:

> Adding this to the server may be a mitigating step, but that doesn’t fully solve the cost and efficiency issue

**Comment by cbaker6** [comment]
> In my view, it shouldn't be up to the developer to custom code a solution for the SDK to work as expected with the core Parse Server. One of our attractive features is simple SDKs which offer a broad range of consistent features. I understand that there are tradeoffs with the current implementation, but I still think it's problematic that at the end of the day, Parse Server has no distinction for dirtyKeys in the Swift SDK, which is different from any other SDK.
>
> Although you've said in terms of philosophy it's not valuable to compare across SDKs, I think from both a developer and Server team perspective, it would be expected that beforeSave functions would function the same, regardless of the SDK. It just seems a little odd to me to say "if you use .dirtyKeys in Parse Cloud, make sure you customise ParseSwift so it doesn't send all the data".

It seems you are thinking in terms of the other SDKs, OOP, and Classes. I pointed to Flo's comment because the philosophy eludes to a number of things traditional users of the other SDKs may be unfamiliar with and the Swift SDK wasn't designed with the restrictions of OOP and Classes. I recommend looking into [protocol oriented programing (POP)](https://www.pluralsight.com/guides/protocol-oriented-programming-in-swift) as it already forces the developer to customize and add their own keys for their ParseObjects, even for the Parse provided keys. The addition of the method I mentioned is simple and straightforward. In POP, developers should feel comfortable using the provided methods, replacing with their own, and adding extensions. As I mentioned in my previous comment, the design patterns of the other SDKs in terms of using OOP and Classes lead to other issues that are not present in the Swift SDK.

> Could we perhaps store a clone of the fetched object somewhere, and then compare keys as part of the save operation? So when building the save operation, Parse Swift runs something like:
>
> const fetchedObj // this has the fetched state
> const updatedObj // this has all the user mutations
>const bodyToSend = {};
> for (const key in updatedObject) {
>  if (fetchedObj[key] !== updatedObj[key]) {
>    bodyToSend[key] = updateObj[key]
>  }
> }

ParseSwift doesn't have local storage (besides using the Keychain for `current`) and if it did have storage, it would be protocol based, meaning the developer would implement it or use some 3rd party storage that conformed to the "storage protocol". The 3rd party storage could have some notion of "dirty" if it felt it was needed. The JS code you mentioned is in the style of the other SDKs which all use runtime encoders/decoders to dynamically access key/value pairs. ParseSwift uses compile time encoders/decoders and doesn't/shouldn't be doing anything like `toJSON` like the other SDKs to access/modify properties of an object.

Of course, a developer doesn't have to use the Swift SDK and can use the [iOS SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX) if they want OOP and Class based ParseObjects.

**Comment by cbaker6** [comment]
> As all keys saved by user two will be overriden. If this was any other SDK, the result would be:
>
>{
>   foo: "aaa",
>   yolo: "aaa"
>}
>Meaning again, if you have a multi tenant solution (iOS App, Web App, Android App), using the Swift SDK in its purest form could be problematic and deliver unexpected results.

This looks like a synchronization issue as a developer can run into the same issue with any of the SDKs if 2 clients attempted to modify the same property of an object at the same time. The race condition you mentioned is because Parse doesn't have a real synchronization mechanism and out-of-the-box asks developers to depend on a wall-clock (`createdAt` and `updatedAt`). If developers implement their storage in a decentralized way as I suggested in https://github.com/parse-community/Parse-Swift/projects/2#card-53117524, they will never run into the issue you mentioned with the Swift SDK or any other of the SDKs.

**Comment by dblythy** [comment]
Right, you're much more familiar with Swift and POP than I am, so I can't confidently argue either way. It just seems strange to me that updating an object with `save` fundamentally interacts differently with Parse Server than any other SDK. Creating, deleting objects is great with Parse Swift, but I'm having to create a custom method to update an existing object - a core feature of Parse. As I've said previously, I think this should be a consideration developers should be aware of, especially if they use cloud functions.

The synchronization issue will happen for the clients in the other SDKs, but it _won't_ happen on the Parse Server as with the other sdks, only mutated keys are `dirty`. When a user calls .fetch in the JS SDK, they will get an object with both keys set by each respective user, whereas in the swift sdk they will only get the second users' save.

**Comment by cbaker6** [comment]
> As I've said previously, I think this should be a consideration developers should be aware of, especially if they use cloud functions.

Agreed, they should definitely be made aware and see the workarounds I mentioned earlier.

**Comment by dblythy** [comment]
Right, so the consideration here to be aware of, is that if you use Parse Swift, calling `.save` on an existing object, will _always_ send all keys to be updated, regardless of whether they are mutated? And this can't be avoided internally on the SDK side because of the way that POP works?

**Comment by cbaker6** [comment]
> If this is the case, I think we should mitigate the dirtyKeys on the server to minimise the potential confusion with cloud code, or unpredictable consequences of internal read-only keys becoming modified.

Im not sure what you mean here. Internal parse keys such as objectId, createdAt, etc. are always skipped when using the Swift SDK (unless when using customObjectId), if they get modified, it’s not because of the Swift SDK.

**Comment by cbaker6** [comment]
I see your server PR, makes sense and my guess is the trade off will be negligible when compared to the DB writes. The server does a lot of key checking already, the only possible improvement I can think of there is if you added your check to a place that was already checking keys to avoid another for loop, but I’m not sure if/where that place exists

**Comment by dblythy** [comment]
The main concern for the server PR is to make sure `.dirty` and `dirtyKeys` can be use as expected with ParseSwift

**Comment by cbaker6** [comment]
I think the PR I just opened with respect to this issue solves this problem and makes it pretty easy for the developer, server, and cloud code to handle dirty keys properly (server and cloud code due what they normally do). Essentially, the developer just has to:

1. add `.emptyObject()` when turning their `ParseObject` into a mutable object 
2. make modifications/mutations as they normally would do
3. save as they normally would do 

Let me know what you think...

**Comment by dblythy** [comment]
That sounds like a good solution to me!

**Comment by mtrezza** [comment]
What are the risks for the developer when using `emptyObject`? I assume the risks mentioned in previous [comments](https://github.com/parse-community/Parse-Swift/issues/242#issuecomment-925444819) have not been eliminated.

**Comment by dblythy** [comment]
My understanding is that if a developer uses `emptyObject`, they still need to compare the updated fields to the fields on fetch. 

E.g,

1. object is fetched
2. text fields are entered, save is pressed
3. Check if text !== originalObject.key
4. Assign to `emptyObject` if the key is dirty 
5. Call .save on `emptyObject`
6. Enumerate through `emptyObject` keys and set them to the original object

**Comment by cbaker6** [comment]
> What are the risks for the developer when using emptyObject? I assume the risks mentioned in previous comments have not been eliminated.

what risk has emptyObject not eliminated?

**Comment by mtrezza** [comment]
I am referring to the [comments](https://github.com/parse-community/Parse-Swift/issues/242#issuecomment-925444819) against using a mutable object. If the Parse SDK is now offering a way for a developer to implement this, do the arguments against a mutable object still stand?

**Comment by cbaker6** [comment]
> My understanding is that if a developer uses `emptyObject`, they still need to compare the updated fields to the fields on fetch.
> 
> E.g,
> 
> 1. object is fetched
> 2. text fields are entered, save is pressed
> 3. Check if text !== originalObject.key
> 4. Assign to `emptyObject` if the key is dirty
> 5. Call .save on `emptyObject`
> 6. Enumerate through `emptyObject` keys and set them to the original object

The Swift SDK doesn't work like this. If a developer is "enumerating through keys" they are using the SDK incorrectly, introducing unnecessary client overhead and processing, and possibly introducing errors that are unrelated to the SDK. The proper process of using emptyObject correctly is outlined here https://github.com/parse-community/Parse-Swift/pull/243#issue-1005536964 and examples are in the playground files:

Regular ParseObject: https://github.com/parse-community/Parse-Swift/blob/5451e5cb39ddfb51425fe89c20a54e5d5ba19538/ParseSwift.playground/Pages/1%20-%20Your%20first%20Object.xcplaygroundpage/Contents.swift#L81-L123

Current User:  https://github.com/parse-community/Parse-Swift/blob/5451e5cb39ddfb51425fe89c20a54e5d5ba19538/ParseSwift.playground/Pages/4%20-%20User%20-%20Continued.xcplaygroundpage/Contents.swift#L102-L122

Current Installation: https://github.com/parse-community/Parse-Swift/blob/5451e5cb39ddfb51425fe89c20a54e5d5ba19538/ParseSwift.playground/Pages/6%20-%20Installation.xcplaygroundpage/Contents.swift#L57-L74

There's no checking for dirty on the client-side or checking for any keys. You simply mutate the keys on emptyObject you want changed on the server and `save`. On the server side, you should do everything the same as you normally would. No special handling is needed unless you are creating your own way to handle data.

**Comment by dblythy** [comment]
> The Swift SDK doesn't work like this. If a developer is "enumerating through keys"

in the first example you showed, you set the required fields to emptyObject, and then after save set those fields on originalObject, which is the process I was explaining. If a developer wanted only updated keys to be assigned to emptyObject, they would add a simple if statement comparing new value to original object value.

**Comment by cbaker6** [comment]
> I am referring to the [comments](https://github.com/parse-community/Parse-Swift/issues/242#issuecomment-925444819) against offering a mutable object. If the Parse SDK is now offering a way for a developer to implement this, do the arguments against a mutable object still stand?

Can you clarify what you are referring to? The Swift SDK has always offered mutable objects. The original concern from @dblythy was all keys were always sent to the server, no matter if their values were dirty/modified or not. My original response was developers could add a simple method to their ParseObjects to address this. The PR added the method for the developer to make the process easy. The Swift SDK still doesn't have a notion of dirty, because it isn't needed from the SDK. If a developer wants/needs dirty, they could do so when they implement their local storage option.

**Comment by mtrezza** [comment]
Is local storage needed to implement a notion of dirty or is that possible without it?

**Comment by cbaker6** [comment]
> > The Swift SDK doesn't work like this. If a developer is "enumerating through keys"
> 
> in the first example you showed, you set the required fields to emptyObject, and then after save set those fields on originalObject, which is the process I was explaining. If a developer wanted only updated keys to be assigned to emptyObject, they would add a simple if statement comparing new value to original object value.

I see your points, if the developer wanted to update the original object locally after saving the mutations on `emptyObject` they could use something similar to what you mentioned. This is all use-case dependent though and if they have implemented  their own local storage, they may or may not need this.

**Comment by dblythy** [comment]
> If a developer wants/needs dirty

Purely from an optimisation perspective, I don’t understand where a developer wouldn’t need dirty. For newer devs, sending the whole object all the time might seem fine as it doesn’t have any side effects, but in terms of saving server costs, using `emptyObject` or a local storage with the notion of `dirty` seems essential to me

**Comment by cbaker6** [comment]
> Purely from an optimisation perspective, I don’t understand where a developer wouldn’t need dirty. 

This is using the mindset of the old SDKs which this SDK doesn't follow. In addition, this is all use-case dependent, I personally would never use dirty and the way the other SDKs implement in conjunction with the Parse Server promotes bad synchronization, but to each as on for design... 

> For newer devs, sending the whole object all the time might seem fine as it doesn’t have any side effects, but in terms of saving server costs, using emptyObject or a local storage with the notion of dirty to minimise the amount of data sent seems essential to me

The PR of `emptyObject` already solved this problem completely, so I'm not sure why this particular issue was reopened. The PR doesn't need "dirty" to accomplish this.

**Comment by mtrezza** [comment]
Reopening because I think @dblythy makes an important point. This can be a major concern in a real-word business environment.

- As long as sending only dirty fields is not yet the default behavior of the SDK, there should be a warning for developers that this SDK does not behave like all other Parse SDKs. Otherwise someone may switch from the ObjC to Swift SDK and get a surprise with their next cloud provider bill. Is there one already maybe?

- From reading this and flovimart's thread I don't understand yet what the specific technical constraint are that do not allow the SDK to have a fully functional dirty implementation. Maybe we can just talk about the specific technical challenge and put our heads together to see if we can find a solution together?

**Comment by cbaker6** [comment]
> From reading this and flovimart's thread I don't understand yet what the specific technical constraint are that do not allow the SDK to have a fully functional dirty implementation. Maybe we can just talk about the specific technical challenge and put our heads together to see if we can find a solution together?

Sounds like a time-sync that I don't see going anywhere. I've either commented or linked all my reasoning. If you all feel you want to discuss/design/develop a solution, feel free, but I won't be able to commit time to this topic as I don't see it leading to anything productive.

The topic, "All keys are marked as dirty using Parse Swift, full body is sent when only one key is updated" has been addressed in its entirety.

**Comment by mtrezza** [comment]
You don't have to commit any time, maybe someone else will. I am asking because you are the expert here and maybe you can help me understand this:

How would the SDK make a http spec compliant PATCH request where only modified fields are sent, once Parse Server supports that?

**Comment by cbaker6** [comment]
> How would the SDK make a http spec compliant PATCH request where only modified fields are sent, once Parse Server supports that? Wouldn't that require a dirty implementation?

The developer would use emptyObject or have something in their local storage implementation that only produces the modified fields to send to the server.

**Comment by dblythy** [comment]
I’m sure I’ve said this before, but if a key is set to increment, and a developer uses `operations` to increment it, if they save without `emptyObject` it will override its incremented sync. 

I like the solution of `emptyObject` for now, but it seems a hard-coded dirty option will require a storage option out of the box.

**Comment by mtrezza** [comment]
> A hard-coded dirty option will require a storage option out of the box.

Why would it require local storage?

**Comment by dblythy** [comment]
> Why would it require local storage?

I think with what Corey was saying that with POP, the object would have to be stored in storage on fetch, and then compared on save to decide what keys are sent to the server. I think it's because the protocols don't hold data or class methods themselves, they are just a JSON representation of the server data. I'm not entirely sure if I've interpreted this though.

Otherwise I think the alternative is to add a JSON or Data representation to the `protocol`, such as `lastFetched`, which could store the last fetched state of the object, used to compare to the current state on save to decide what keys to send. I'd assume this would be a breaking change for the Swift SDK as a new variable would need to be added to the protocol.

Do you have any ideas around OOTB solutions @mtrezza?

**Comment by mtrezza** [comment]
That probably depends primarily on what requires the least effort. I'm thinking either add mutating properties to struct, or just switch from `struct` to `class`. There's nothing wrong with reference types and shared instances if threading is properly handled, and we would introduce a read/write queue with write lock. The perf implication should be negligible and still less than that of any local storage solution, which would also queue based anyway.

Regarding the often mentioned design philosophy, I see two ways of thinking about this:

- the academic perspective that has the freedom to philosophize and be experimental in design
- the business perspective, that is constrained by real-world applications of Parse Server and business requirements

Parse Platform is a business tool, so the business perspective has to take precedence.

**Comment by novemTeam** [comment]
> > If a developer wants/needs dirty
> 
> 
> 
> For newer devs, sending the whole object all the time might seem fine as it doesn’t have any side effects, but in terms of saving server costs, using `emptyObject` or a local storage with the notion of `dirty` to minimise the amount of data sent seems essential to me

If I understand correctly, what makes the difference between sending the full object or only the modified keys? 
Just the size of the data send, I would assume?

But does it really make that big of a difference for the server costs? 

I pay for a plan on Back4App, but they don't charge for the size of the requests send. Only on the amount of requests send. I took measures for this by limiting my requests. But that isn't easy.

With the ParseSwift `1.10.0` update, the init() protocol of ParseObject's changed, and I still don't really understand why it was needed for this related issue. 

But for me, I think it's a step back since you can't set non-optional variables anymore.

I changed my code to adopt to this, but it seems a little les secure to me now.

**Comment by dblythy** [comment]
> Just the size of the data send, I would assume?

The size of the data send, as well as the core interaction with the Parse Server - the way that Cloud Code runs, multi-user ACLs are handled, etc. It mightn't seem like a big deal to you if you use a service that doesn't charge per data, but for other users with thousands of objects, this could be a difference of hundreds of dollars. It's in everyone's interest to make Parse Server and it's SDKs as secure and effective as they can be. 

I wasn't aware that `emptyObject` was a breaking change, which is why we have these discussions in the first place, to balance and discuss the potential benefits whilst limiting the breaking changes / migrations that are required of our SDK users. If you would like to contribute to the respectful discussion of how to make this SDK function with Parse Server like the other SDKs whilst limiting the amount of migration for ParseSwift users, we would appreciate insightful input.

**Comment by dblythy** [comment]
Also worth mentioning here that the current solution to `dirtyKeys` introduces other issues. An OOTB solution could remove `emptyObject` and the requirement for an empty initializer, hopefully fixing the issue mentioned at #247.

**Comment by novemTeam** [comment]
>
>
> 
> ParseSwift is a great package with so many benefits, so why shouldn’t we make it better and more efficient? Otherwise developers have to choose this SDK for simplicity, or the other one for being cheaper and more efficient. 

Yes, I agree. I came from the Parse SDK for objective c. And I really like the ParseSwift SDK.

It's amazing what Corey accomplished with the SDK in less than a year. Very thankfull for that.   
> 
> 
> 
> I wasn't aware that `emptyObject` was a breaking change, which is why we have these discussions in the first place, to balance and discuss the potential benefits whilst limiting the breaking changes / migrations that are required of our SDK users. If you would like to contribute to the respectful discussion of how to make this SDK function with Parse Server like the other SDKs whilst limiting the amount of migration for ParseSwift users, we would appreciate insightful input. 

I also support your point about only sending the edited keys. 

If we/someone would have an idea to fix this without breaking the init() methods, it would be very welcome. I do think it's worth to check it out. 

I now have adjusted my code to it, and it's not the worst change, but I do think it's a little less efficient then previous versions. 

It's not up to me to decide what's best, but I can just give my opinion for the greater good.

**Comment by dblythy** [comment]
> I now have adjusted my code to it, and it's not the worst change, but I do think it's a little less efficient then previous versions.

Well hopefully to your delight we can work out a solution and you'll have to change your code back again 😝

**Comment by dblythy** [comment]
I'm glad we have the `operation` feature for single keys, but as we've discussed, ideally it would be nice to work towards this core SDK being restrictive in the keys that it sends using `.save`. `.save` should function differently for `CREATE` events vs `UPDATE` events.

By the sounds of it, it's a technical challenge though that us and others are welcome to discuss potential solutions. Regardless of someone's technical solutions or the amount of commits that they have made, OS is about people of different skill levels working towards a solution that benefits the package and broader community, discussing pros vs cons of a certain approach, and encouraging the community to drive the direction and growth of a package.

As "core" functionality, I understand this isn't a priority to certain users, or that time could be better spent somewhere else. I don't see why we can't welcome the discussion with other potential contributors - regardless of skill level - for ideas or a plan to how we could address this. Improving the core efficiency of this package and ensuring consistency across SDKs only has upsides in my view.

Thanks for your insight so far Corey, I appreciate although you've stated your opinion on the feature, you've still given us some guidance and the discussions lead to the `operation` feature, which is a good start imo. Let's hope we can get some ideas and can work towards some sort of plan for how to make `save` more efficient without being a breaking change to the SDK.

**Comment by mtrezza** [comment]
I mean a problem statement for why we cannot change the SDK to send only modified fields on `save`.

**Comment by dblythy** [comment]
> this isn’t an option for this SDK, if you both are for this you should commit to making your updates to the objective-c SDK as it’s designed for this

Ok, this is good constructive feedback as to why `classes` isn't the option.

**Comment by dblythy** [comment]
For context, it's also worth mentioning that using `save` for existing objects with highly scaled applications is problematic. Consider an app with hundreds of concurrent users who access the same Parse object, with two fields, a `counter` and a `name` field. Using `operation.increment` on a the `counter` field and `operation.save` will increment the counter irrespective of the objects' state when the client fetched it. This allows for all hundred users to concurrently increment the counter once, and the counter value to be 100.

However, if one client calls `.save` on the entire object, even for a single key update (such as changing the "name" field), all `increment` calls between the last fetch / save will be wiped. If the counter was 2 when the object was fetched, it will be hard reset to 2 in the database when `.save` is called.

This as well as scalable network costing concerns, in my view, is the reason why this issue is relevant and the discussion is open. `operation.set` or a custom `emptyObject` is the current work-around, but I think working towards default behaviour similar to it would help the ease of use for this SDK, especially for concurrent and network conscious applications.

**Comment by mtrezza** [comment]
@cbaker6 You mentioned in https://github.com/parse-community/Parse-Swift/pull/392#discussion_r949696871 that this issue has been fixed, which would be great news.

It may help to untangle this discussion if you could provide a simple example here that shows what's needed to make this SDK only send the updated keys.

As we know, in other SDKs it's as simple as this:

```
const obj = new Parse.Object(`Example`);
obj.save();
obj.set(key, value);
obj.save();
```

What would be the simple example for the Swift SDK?

**Comment by cbaker6** [comment]
> It may help to untangle this discussion if you could provide a simple example here that shows what's needed to make this SDK only send the updated keys.

https://github.com/parse-community/Parse-Swift/blob/675168eb8b40fdbd84089652c98a732532c3d688/ParseSwift.playground/Pages/1%20-%20Your%20first%20Object.xcplaygroundpage/Contents.swift#L107-L143

**Comment by mtrezza** [comment]
So looking again at the JS example:

```
const obj = new Parse.Object(`Example`);
obj.save();
obj.set(key, value);
obj.save();
```

Would this be the complete equivalent in Swift?

```
struct Example: ParseObject {
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
    var key: Int?
}

let obj = Example()
obj.save()
var objMutable = obj.mergeable
objMutable.key = value
objMutable.save()
```

**Comment by cbaker6** [comment]
https://github.com/parse-community/Parse-Swift/blob/675168eb8b40fdbd84089652c98a732532c3d688/ParseSwift.playground/Pages/1%20-%20Your%20first%20Object.xcplaygroundpage/Contents.swift#L32-L53

**Comment by mtrezza** [comment]
So let try again,

```
struct Example: ParseObject {
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
    var originalData: Data? 
    var key: Int?

    func merge(with object: Self) throws -> Self { 
         var updated = try mergeParse(with: object) 
         if updated.shouldRestoreKey(\.key, 
                                      original: object) { 
             updated.key = object.key 
         } 
         return updated 
     } 
}

let obj = Example()
obj.save()
var objMutable = obj.mergeable
objMutable.key = value
objMutable.save()
```

Is this now the complete equivalent?

**Comment by cbaker6** [comment]
It looks right

**Comment by mtrezza** [comment]
I've been trying to read through #315 but it's a lengthy thread.

Is it correct that in order to send only updated keys to the server the developer must:
- add the `originalData` property
- add the `merge` method
- when changing custom properties keep in mind to manually duplicate those changes in the merge method
- do that for every Parse Object class

So your conclusion in #315 is that there is no way to prevent that the developer has to implement and maintain all this overhead and instead build this into the SDK?

**Comment by cbaker6** [comment]
> add the originalData property but doesn't have to interact with it

`originalData` is added automatically to all `ParseObject`'s by the compiler due to the protocol, just like `objectId`, etc. The developer doesn't need to interact with it 

> add the merge method but doesn't have to interact with it
> when changing custom properties keep in mind to manually reflect those changes in the merge method

The developers override the default implementation of `merge` for each `ParseObject`. When overriding, they add their custom properties by using the additional helper methods like so:

https://github.com/parse-community/Parse-Swift/blob/675168eb8b40fdbd84089652c98a732532c3d688/ParseSwift.playground/Pages/1%20-%20Your%20first%20Object.xcplaygroundpage/Contents.swift#L44-L53

**Comment by mtrezza** [comment]
> If the developer doesn't override merge, only the modified keys are sent to the server (assuming they mutated mergeable). They won't have the merged changes locally, instead, they will need to call fetch on the respective object to have the original and merged updates locally. 

Can you confirm that you see no technical way to avoid the developer having to override the `merge` method to achieve the same behavior?

**Comment by cbaker6** [comment]
> Can you confirm that you see no technical way to avoid the developer having to override the merge method to achieve the same behavior?

If I knew of a better way it would have been in PR 316-400

**Comment by mtrezza** [comment]
Thanks, I've updated the Migration guide with a condensed version of this information. Could you please review the code examples and suggest any changes you may want to see?

**Comment by cbaker6** [comment]
> Thanks, I've updated the Migration guide with a condensed version of this thread. Could you please review the code examples and suggest any changes you may want to see?

1. I don’t see a reason to have a “third” place to have code examples. Instead you should have added a “migration” section following the directions in #325 
2. I mention in 325 that all examples should be written in the “async await” form. There’s no reason to teach developers to make synchronous networking calls. In addition, synchronous networking calls in Apple OS hold up the main thread and Xcode will throw a ton of purple run time warnings along with creating a sluggish app. This encourages developers to come back to the repo and complain that it’s an issue with the SDK. The issue is their usage of the SDK that they learned from bad documentation
3. Multiple variants of Swift examples? There should only be one variant shown, encouraging developers to use mergeable. Showing multiple variants is encouraging bad decisions that will lead to open issues and complaints. 

> My suggestion would be to close this issue, as the bug has been addressed and it's now possible to send only the updated properties to the server, albeit with additional code and not by default. I would also move the point in the migration guide from "Known Issues" to "Behavioral Differences", as it's just the required difference in code we want to point out.

I’m fine with this

**Comment by mtrezza** [comment]
> I don’t see a reason to have a “third” place to have code examples. Instead you should have added a “migration” section following the directions in Convert Playgrounds to DocC Interactive Tutorials

The examples are to explain the behavioral difference between ObjC and Swift SDK. I don't intend on writing DocC tutorials, but anyone if free to do so. For now it's important to have a central migration guide, rather than bits of information scattered across issues and PR treads. Even a simple txt file would be better than nothing at this point.

> I mention in 325 that all examples should be written in the “async await” form. There’s no reason to teach developers to make synchronous networking calls.

This is a migration guide not a programming guide. It's not intended to teach when to use async/sync. There's a clear note that sync calls are used for simplicity. Feel free to open a PR to add async calls to the examples.

> Multiple variants of Swift examples? There should only be one variant shown, encouraging developers to use mergeable. 

The goal of the guide is to help developers transition their way of thinking coming from the ObjC SDK. Each variant gives context to lead them to the final recommended approach. If you find a way to convey that info in 1 condensed example please feel free to open a PR.

**Comment by mtrezza** [comment]
If there's no objection from @dblythy I'll go ahead and close this issue and open a feature request as commented above.

**Comment by mtrezza** [comment]
Closing as limitation has been addressed; further improvement tracked in https://github.com/parse-community/Parse-Swift/issues/401.
