### ISSUE TITLE
Parse iOS Build Error...

### ISSUE THREAD

**Issue by DevStreamLine** [parse-community/Parse-Swift#244]
Hello,

My iOS project was building fine until this morning after an Xcode upgrade.  Now when I try to build the project with the Parse SDK, I get the following error:

MyApp-iOS/Pods/Parse/ParseUI/Classes/Internal/Views/Buttons/PFActionButton.m:60:5: Use of undeclared identifier '_configuration'; did you mean 'configuration'?

Has anyone else seen this issue?  I have performed a pod update so I have the latest.

**Comment by cbaker6** [comment]
It looks like you posted on the wrong SDK. You are looking for https://github.com/parse-community/Parse-SDK-iOS-OSX
