### ISSUE TITLE
User sessions are not getting removed on app uninstall

### ISSUE THREAD

**Issue by Vortec4800** [parse-community/Parse-Swift#246]
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description
When uninstalling an app and reinstalling, the `currentUser` still reports the same session from before the app was uninstalled. This doesn't match user expected behavior, where deleting and reinstalling an app would start things "fresh" for them.

This is likely due to the fact that Keychain values are not cleared when an app is uninstalled, which Apple seems to claim is not a bug. This may be happening with other Keychain-stored values as well like Installations, but I haven't checked those specifically at this point.

### Steps to reproduce
1. Install a test app and log in using any method.
2. Verify killing and relaunching app logs in the user and `currentUser` is populated.
3. Uninstall the test app from the simulator/device.
4. Reinstall the test app and launch.

### Actual Outcome
Upon launching after second install, `currentUser` is populated and the app is logged in.

### Expected Outcome
The user's expected outcome would be that the newly installed app is not logged in and `currentUser` would return nil.

### Environment

Client
- Parse Swift SDK version: `1.10`
- Xcode version: `13`
- Operating system (iOS, macOS, watchOS, etc.): `iOS`
- Operating system version: `15`

Server
- Parse Server version: `4.10.3`
- Operating system: `Ubuntu`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `DO`

Database
- System (MongoDB or Postgres): `Mongo`
- Database version: `4.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `DO`

**Comment by Vortec4800** [comment]
I'm happy to put together a PR for this but I'd like some direction first. How should the SDK go about fixing this? A common method is to store something in `UserDefaults` as that does get cleared as expected and if that key is missing then discard Keychain data. It could also write a plist/dictionary to a folder in the application bundle and check for that as well.

Thoughts on this? Maybe there is also an easier fix I'm not thinking of.

**Comment by cbaker6** [comment]
You as the app developer should be handling the keychain, particularly when you uninstall the app. You can check the sample app I released for an [example](https://github.com/netreconlab/SnapCat/blob/8218047ef311c7610da8f4cde6db0dd1108c0047/SnapCat/SnapCatApp.swift#L30-L37):

```swift
        // Clear items out of the Keychain on app first run. Used for debugging
        if UserDefaults.standard.object(forKey: Constants.firstRun) == nil {
            try? User.logout()
            // This is no longer the first run
            UserDefaults.standard.setValue(String(Constants.firstRun),
                                           forKey: Constants.firstRun)
            UserDefaults.standard.synchronize()
        }
```

The link above is using a SwiftUI app cycle, but the same code can go in your app delegate.

**Comment by Vortec4800** [comment]
This is indeed a workaround that can be included, but the SDK should be responsible for cleaning up its own keys so behavior matches user expectations.

If the app developer was responsible for the Keychain/User state, then it would be expected that the SDK doesn't handle Keychain storage at all and it would be up to the app to persist the user and installation data on its own. The SDK handles this instead, which implies that it would handle the entire lifecycle of those keys and state.

**Comment by cbaker6** [comment]
> This is indeed a workaround that can be included, but the SDK should be responsible for cleaning up its own keys so behavior matches user expectations.

This has never been handled by any of the iOS related SDKs in the past. Of course, if you have a way of doing so, please submit a PR.

> If the app developer was responsible for the Keychain/User state, then it would be expected that the SDK doesn't handle Keychain storage at all and it would be up to the app to persist the user and installation data on its own. The SDK handles this instead, which implies that it would handle the entire lifecycle of those keys and state.

This seems to be an opinion, but if you come up with a solution, I'll review it.

**Comment by cbaker6** [comment]
> I haven't investigated how it works, but the current Objective-C Parse SDK returns a nil currentUser after uninstall/reinstall.

If this is true, I recommend looking there to get an idea on how/where to add the feature as the Keychain in the Swift SDK is similar.
