### ISSUE TITLE
Drop support for iOS 12, tvOS 12, watchOS 5, and macOS 10.13/14

### ISSUE THREAD

**Issue by cbaker6** [parse-community/Parse-Swift#255]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description

Original discussion began here: https://github.com/parse-community/Parse-Swift/pull/13#issuecomment-669015795

The current OS's to be removed (iOS 12, tvOS 12, watchOS 5, and macOS 10.13/14) are currently in limbo as the Swift SDK should work well with them with the exception that `ParseLiveQuery` cannot be used. This is due to native websocket additions in iOS13+. Any OS before the aforementioned OS's already have to resort to the Obj-C SDK.

The Swift SDK leverages modern Swift: value types, `Combine`, web sockets, and with modification; SwiftUI. The minimum requirements for the aforementioned modern features is iOS 13. In addition, the Swift SDK indirectly supports the `Identifiable` protocol (if the developer adds the `id` property themselves) which simplifies using `ParseObject`'s as models for SwiftUI. `iOS 13` [supports devices as old as 6+ years (2015)](https://www.computerworld.com/article/3282811/which-iphones-ipads-support-apples-ios-13-and-ipados.html).

Supporting the "limbo" OS's requires additional code (as seen in PR #254) and require extra care with maintaining.  There were [massive changes added by Swift 5.1](https://swift.org/blog/swift-5-1-released/) with minimum OS support for iOS13, tvOS 13, watchOS 6, and macOS 10.15. Dropping the "limbo" OS's allow for easier app development for developers as ParseObject's natively conform to `Identifiable` and simplifies maintenance and addition of features.

What can happen next is next version of the Swift SDK, 1.11.0 (which should include #238 and #248) will be the last release supporting the "limbo" OS's. After, 2.0.0 will drop support.

### Steps to reproduce

Try to use `Identifiable`, `Combine`, natively on an older OS.

### Actual Outcome

Won't compile.

### Environment

Client
- Parse Swift SDK version: 1.10.4
- Xcode version: Xcode 13
- Operating system (iOS, macOS, watchOS, etc.): iOS 15
- Operating system version: Big Sur

Server
- Parse Server version: 4.10.3
- Operating system: linux
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): self host

Database
- System (MongoDB or Postgres): Postgres
- Database version: 13
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): self host

**Comment by mtrezza** [comment]
> After, 1.11.0 will drop support.

What versioning system is used for the Parse Swift SDK? Shouldn't a breaking change make a major version jump?

**Comment by cbaker6** [comment]
I was using SemVer, but didn't think of moving to 2.0.0. I'm fine with this type of change doing so.

**Comment by mtrezza** [comment]
Yes, we're using semver across most Parse repos, so I think that would be good.

**Comment by mtrezza** [comment]
Regarding this issue, I think a good indicator for making a decision whether to drop SDK support is the [distribution](https://developer.apple.com/support/app-store/). We can see that 7-12% of devices run on <=iOS 12, which I think is acceptable for dropping support.
