### ISSUE TITLE
"current" ParseObjects should be immutable

### ISSUE THREAD

**Issue by cbaker6** [parse-community/Parse-Swift#267]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).

### Current Limitation

Currently all objects can be set through current, like: `ParseUser.current`, `ParseInstallation.current`, `ParseConfig.current`. These should be mutable and when the developer wants to mutate, they make mutable copies. This prevents unintended behavior such as setting `ParseUser.current` to `nil` directly as `current` should only become `nil` when using the `ParseUser.logout()` method. It also prevents setting to a different user incorrectly.

### Feature / Enhancement Description

Note: All playgrounds examples have shown how to make mutable copies instead of setting `current` directly for some time now. Many people learn how to use the SDK from the Swift playground examples.

Related to a previous discussion: https://github.com/parse-community/Parse-Swift/pull/22#discussion_r491168728. I should have done this back before the first release, but forgot about it.

> And regardless of that result, until we properly implement local storage, should I make the setters internal only?
> Sounds reasonable to me. The one thing I've been doing is using the playground files to make sure everything is correct on the parse-server. The unit-tests are good, but they are mocking the parse-server. If you aren't already, you should make sure your changes work via playgrounds with a real parse-server. I posted some basic instructions and docker container (has parse-dashboard also) just for this here.

### Example Use Case

```swift
struct User: ParseUser {
    //: These are required for `ParseObject`.
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?

    //: These are required for `ParseUser`.
    var username: String?
    var email: String?
    var emailVerified: Bool?
    var password: String?
    var authData: [String: [String: String]?]?

    //: Your custom keys.
    var customKey: String?

    /*:
     It's recommended the developer adds the emptyObject computed property or similar.
     Gets an empty version of the respective object. This can be used when you only need to update a
     a subset of the fields of an object as oppose to updating every field of an object. Using an
     empty object and updating a subset of the fields reduces the amount of data sent between
     client and server when using `save` and `saveAll` to update objects.
    */
    var emptyObject: Self {
        var object = Self()
        object.objectId = objectId
        object.createdAt = createdAt
        return object
    }
}

// Problems
User.current = nil // Shouldn't be possible, should be using logout instead
User.current = User() // Shouldn't be allowed to change the current user. Should use a login method to do this properly
User.current?.customKey = "Updated" // Developers shouldn't be doing this and should be mutating a copy instead
do {
  try await User.current?.save()
} catch {
  // Handle error
}

// What proposed changes will require developers to do instead:
var user = User.current
user?.customKey = "Updated"

do {
  try await user?.save()
} catch {
  // Handle error
}

// or developers can use the computed property to only send changes to the server
var user = User.current?.emptyObject
user?.customKey = "Updated"

do {
  try await user?.save()
} catch {
  // Handle error
}
```

### Alternatives / Workarounds

Ask the the developers to make mutable copies before mutating and hope they do so. Developer's can also add a computed property that makes a copy of their object for them.

**Comment by dblythy** [comment]
Sorry for the delay in response it has been a busy week.

Is there any way to make a local only change to current user now?

In my flow, I assign a `Business` object to the current user on the backend using an aftersave trigger on the Business class.

Previously, I was doing:

```
var business = Business()
business.name = name
business.save { result in
  switch result {
  case .success(_):
    UserModel.current?.business = business
```

So that way the UI in the rest of the app would update (as UserModel.current?.business is defined).

Would the solution to this now be to call `current?.fetch`?

**Comment by cbaker6** [comment]
You would make the change to a mutable copy of the current user which is returned to you after the save:

```swift

var business = Business()
business.name = name
business.save { result in
  switch result {
  case .success(let savedUser):
    var mutableUser = savedUser
    mutableUser.business = business
    mutableUser.save() 
   // Or you can pass mutableUser to your view. After the save, the latest version should be in User.current without the need of fetch
```

**Comment by lsmilek1** [comment]
I apologise for late reply as I was traveling offline for few weeks. Now I updated the SDK after that while and got into a breaking change with this update. I think I can rewrite most of the logic but I wonder now how to handle the workaround for Apple SignIn re-login mentioned [here](https://community.parseplatform.org/t/new-session-sign-in-with-apple/2105/3?u=lsmilek1)
```swift
var currentUser = User.current
if currentUser != nil {
   try? User.logout()
}
User.apple.login(user: appleIDCredential.user, identityToken: token) { result in
   switch result {
   case .success(let user):
   User.current = currentUser
   ...
```

With previous version I did not have to call extra save as all the changes had to be done only locally (server had values before and after login correct). Now it seems that I need to `.save()` the mutable copy in order to get it stored locally, what will trigger the server save request. Am I right that there is no way around it?

**Comment by cbaker6** [comment]
This type of call, User.current = currentUser, should have never been done in the first place. The very reason for this change is to prevent users from doing this. Even if you thought it was working, it wasn’t. After you call User.apple.login, the SDK automatically updates the current user, and User.current = currentUser was actually overwriting the new saved current user.
