### ISSUE TITLE
Bool query not working...

### ISSUE THREAD

**Issue by LilMoke** [parse-community/Parse-Swift#282]
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [ x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [ x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description
I can do this: Word.query(WordKey.word == “Some Text”) and it works (string compare)
I can so this: Word.query(WordKey.wordOrder < 8) and it works (int)
But this does not: Word.query(WordKey.isWordNeeded == true) Bool fields do not seem to work, it always return a 0 result set

Is there something special with a bool that I am missing?

Could this be related to this issue: https://github.com/parse-community/Parse-Swift/pull/49

### Steps to reproduce
Create a query as follows:
	@ObservedObject var wordsWordViewModel = Word.query(WordKey.isWordNeeded == true)
		.order([.descending("word")])
		.viewModel

### Actual Outcome
0 records are return even though several exist with the a bool value of true

### Expected Outcome
several records to be returned in the result set

### Environment
Heroku Server

Client
- Parse Swift SDK version: 2.2.5
- Xcode version: 13.1
- Operating system (iOS, macOS, watchOS, etc.): iOS
- Operating system version: mac OS Monterey 12.0.1

Server
- Parse Server version: 4.10.1
- Operating system: Ubuntu 18.04 
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Heroku

Database
- System (MongoDB or Postgres): MongoDB
- Database version: 
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): MongoDB

**Comment by cbaker6** [comment]
Can you fill out the whole template?

**Comment by LilMoke** [comment]
ok, updated

**Comment by cbaker6** [comment]
This seems to be a false alarm and probably something wrong with how you are saving your objects. See response here: https://community.parseplatform.org/t/parseswift-query-question/2180/9?u=cbaker6

**Comment by cbaker6** [comment]
Closing via response here: https://community.parseplatform.org/t/parseswift-query-question/2180/11?u=cbaker6
