### ISSUE TITLE
Convenience methods for ParseGeoPoint

### ISSUE THREAD

**Issue by jaysonng** [parse-community/Parse-Swift#288]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).

### Current Limitation

There's no "easy" way to get latitude and longitude out of a ParseGeoPoint to convert them to CLLocation and CLLocation2D without have repetitive code.

### Feature / Enhancement Description

Adding toCLLocation and toCLLocationCoordinate2D methods.

### Example Use Case

let clLocation = point.toCLLocation()
let coordinate2D = point.toCLLocationCoordinate2D()

### Alternatives / Workarounds

Currently, you would have to create CLLocation or CLLocationCoordinate2D by pulling out the latitude and longitude from the geopoint and initialize CLLocation with the said latitude and longitude.

### 3rd Party References

no.

**Comment by cbaker6** [comment]
I removed the spaces in your checkboxes so they show up correctly. They should look like "- [x]"
