### ISSUE TITLE
Saving ParseObjects with File properties

### ISSUE THREAD

**Issue by alexvenom** [parse-community/Parse-Swift#31]
Right now I am trying to save an ParseObject with a File (ParseFile) property as this:

```swift
    struct TestClass: ParseObject {
        var objectId: String?
        var createdAt: Date?
        var updatedAt: Date?
        var ACL: ParseACL?
        var location: GeoPoint?
    
        var name: String
        var age: Int
        var photo: File
    
        init(name: String, age: Int) {
            self.name = name
            self.age = age
        }
    }
```

It gives me two errors:
Type 'TestClass' does not conform to protocol 'Equatable'
Type 'TestClass' does not conform to protocol 'Hashable'

The first one I can fix by:
`
    static func == (lhs: TestClass, rhs: TestClass) -> Bool {
        return lhs.objectId == rhs.objectId
    }`

How exactly can I save such a property?

**Comment by cbaker6** [comment]
File hasn't been implemented yet so it won't save properly when you add it to a ParseObject. It's possible the File isn't making your object not conform to ParseObject.

There are examples (https://github.com/parse-community/Parse-Swift/blob/main/ParseSwift.playground/Pages/1%20-%20Your%20first%20Object.xcplaygroundpage/Contents.swift) in playground on how to create ParseObjects, once File is finished an example of how to use it will be added to Playgrounds and test cases.

**Comment by laosb** [comment]
Will it be supported in near future? Seriously considering using Apollo GraphQL instead of ParseSwift now...

**Comment by cbaker6** [comment]
It's currently being worked, should be one of the next features finished.

**Comment by cbaker6** [comment]
@alexvenom to conform to `Hashable`, you can write an extension:

```swift
extension TestClass {

    // Equatable
    public static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.uuid == rhs.uuid
    }

   //Hashable
    public func hash(into hasher: inout Hasher) {
        //Need to have a unique value, you can add uuid (remember the `objectId` is only present after a save so you can't use that
        hasher.combine(self.uuid)
    }
}
```

Be sure to read the warning in the documentation (it discusses my comments above): http://parseplatform.org/Parse-Swift/api/Protocols/ParseObject.html

**Comment by novemTeam** [comment]
Is there currently a way of getting to your files with ParseSwift?

**Comment by cbaker6** [comment]
In response to my earlier comment:

> File hasn't been implemented yet so it won't save properly when you add it to a ParseObject. It's possible the File isn't making your object not conform to ParseObject.

This is confirmed:

1. `File` wasn't implemented, so it would have crashed the app during any fetching/saving/etc.
2. `File` wasn't Hashable, which would also give you `Equatable`, causing the error, `Type 'TestClass' does not conform to protocol 'Hashable'` and `Type 'TestClass' does not conform to protocol 'Hashable'`.

The linked PR adds File support and the errors reported here shouldn't be seen unless you add a non-Hashable object to your `ParseObject` in which case you will need to mitigate the issue using something similar to https://github.com/parse-community/Parse-Swift/issues/31#issuecomment-734501641

Lastly, `File` has been renamed to `ParseFile`.
