### ISSUE TITLE
Response parsing error when ParseUser is successfully signed up

### ISSUE THREAD

**Issue by Climbatize** [parse-community/Parse-Swift#313]
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description

When sining up a User Parse sever response may not contain a sessionToken (Parse 4.2)

### Steps to reproduce

- Create a ParseUser subclass

```swift
import Foundation
import ParseSwift
​
struct User: ParseUser {
    var emailVerified: Bool?
    var password: String?
    var authData: [String: [String: String]?]?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
​
    public var objectId,
			   email,
               qrCode:         String?
​
​
}
```

- Uses one of the ParseUser methods to sign up an instance ()

```swift
var user = User();
                   user.password = password;
                   user.username = username;
                   user.email = email;
                   user.qrCode = "";
            
user.signup() { result in
    switch result {
    case .failure(let error):
        //: Publish error.
        self.error = error
        print(error.message)
    case .success(user):
        print("Successfully queried data")
    case .success(_):
        print("Successfully queried data")
    }
}
```
or
```swift
var user = User();
                   user.password = password;
                   user.username = username;
                   user.email = email;
                   user.qrCode = "";
            
let publisher = user
    .signupPublisher()
        .sink(
                receiveCompletion: { result in
                    switch result {
                    case .failure(let error):
                        //: Publish error.
                        self.error = error
                        print(error.message)
                    case .finished:
                        print("Successfully queried data")
                    }
                }, receiveValue: { user in
                    self.user = user
                }
        )
publisher.store(in: &subscriptions)
```

### Actual Outcome
Subscription results as an unknown error but the ParseUser is stored in database

### Expected Outcome
Returns a success or an explaination on why the outcome is an error

### Environment

Client
- Parse Swift SDK version: `3.0.0`
- Xcode version: `13.2.1`
- Operating system (iOS, macOS, watchOS, etc.): `iOS`
- Operating system version: ` 13-15`

Server
- Parse Server version: `4.2.0`
- Operating system: `N/A`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Back4App`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Back4App`

### Logs
```
(ParseSwift.ParseError) error = {
  code = unknownError {}
  message = "Invalid struct: No value associated with key CodingKeys(stringValue: \"sessionToken\", intValue: nil) (\"sessionToken\")."
  otherCode = nil {
    some = (_value = 0)
  }
}
```

**Comment by cbaker6** [comment]
Not your I understand your issue...

You log response states it couldn't decode the `sessionToken`, you stated:

> When sining up a User Parse sever response may not contain an AccessToken (Parse 4.2)

Do you mean `sessionToken`? Also, are you saying that Parse Server 4.2 doesn't always send a `sessionToken` and it's designed that way? 

If the server isn't sending a `sessionToken`, it's not going to work with the Swift SDK.

Lastly, Parse Server 4.2 (Early 2020) is pretty old compared to the Swift SDK (first came out Early 2021), Swift SDK 3.0.0 is Early 2022. I recommend upgrading your server to something closer to what the SDK was designed against.

**Comment by Climbatize** [comment]
> Not your I understand your issue...
> 
> You log response states it couldn't decode the `sessionToken`, you stated:
> 
> > When sining up a User Parse sever response may not contain an AccessToken (Parse 4.2)
> 
> Do you mean `sessionToken`? Also, are you saying that Parse Server 4.2 doesn't always send a `sessionToken` and it's designed that way?
> 
> If the server isn't sending a `sessionToken`, it's not going to work with the Swift SDK.
> 
> Lastly, Parse Server 4.2 (Early 2020) is pretty old compared to the Swift SDK (first came out Early 2021), Swift SDK 3.0.0 is Early 2022. I recommend upgrading your server to something closer to what the SDK was designed against.

Yeah, sorry, I fixed my description. 🙇 
I understand that my server is pretty old, but it's managed by my client not by me, so I have no way to upgrade it for now. 😢 

Parse 4.2 does not send a session token on signup call, at least the Back4App Parse 4.2 servers.

Also, Parse is still officially on version 4, there should not be breaking changes between version 4.2 and 4.10. I just forked `Parse-Swift` and fixed the issue on my side by making `sessionToken` optional in the answer, so I don't really need a fix for this bug, I just wanted to provide a PR following this ticket. 

I understand that you don't want to support a version from 2020, but
4.2 is just another minor version from the latest stable one, that's why I thought the lib was compatible with 4.+. Sorry if I made you loose your time.
Is there a documentation entry where I can find which versions are supporting 4.2?

**Comment by Climbatize** [comment]
I asked the administrator to update the server, thanks for the heads up

**Comment by cbaker6** [comment]
And the Server only being a minor update, that doesn’t apply until 5.0.0, see the notes about versioning https://github.com/parse-community/parse-server/blob/alpha/CONTRIBUTING.md#versioning

**Comment by Climbatize** [comment]
Thanks A lot @cbaker6 for all these explanations! I'm re-discovering Parse as last time I used it it was not yet open source. I'm in touch with Back4App to know why they are not sending me a session token, even on 4.10. Strangely enough, this issue is not present on Android side, so I suspect a bad implementation on my side.

**Comment by mtrezza** [comment]
> There’s no documentation about what servers the Swift SDK runs on.

I think we could do a better job in showing which Parse client SDK version is compatible with which Parse Server version. We have had this issue coming up also in other SDKs. A simple compatibility table in each SDK's readme would do it.

**Comment by asielcabrera** [comment]
You just need to declare var access_token: string? in your user model

struct User: ParseUser {
    var emailVerified: Bool?
    var password: String?
    var authData: [String: [String: String]?]?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
​    
    var access_token: string?

    public var objectId,
			   email,
               qrCode:         String?
​
​
}

**Comment by asielcabrera** [comment]
I have something similar when I try to login: 
ParseError code=-1 error=Invalid struct: No value associated with key CodingKeys(stringValue: "createdAt", intValue: nil) ("createdAt").

User Model: 
struct User: ParseUser {
    var score: Double?
    
    
    //: These are required by `ParseObject`.
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
    var originalData: Data?
    
    //: These are required by `ParseUser`.
    var username: String?
    var email: String?
    var emailVerified: Bool?
    var password: String?
    var authData: [String: [String: String]?]?
    
    var access_token: String?
}

**Comment by cbaker6** [comment]
@Climbatize and @asielcabrera both of your errors are odd. I don't see why a current Parse Server or even an old server wouldn't send the `sessionToken` or `createdAt` during sign up. Even if you are using back4app, there are a number of people who use this SDK with back4app like @vdkdamian.

I recommend you both:
1. [fork this commit of ParseSwift](https://github.com/parse-community/Parse-Swift/tree/3c3a6e8637a1d93c5f1b910a942aeaedffc77fda)
2. open [Common.swift](https://github.com/parse-community/Parse-Swift/blob/3c3a6e8637a1d93c5f1b910a942aeaedffc77fda/ParseSwift.playground/Sources/Common.swift) and change the config to point to your Parse Server with all of the necessary credentials
3. Open and run [ParseSwift.playground](https://github.com/parse-community/Parse-Swift/blob/3c3a6e8637a1d93c5f1b910a942aeaedffc77fda/ParseSwift.playground/Pages/3%20-%20User%20-%20Sign%20Up.xcplaygroundpage/Contents.swift). If this signup works, then your client and server are fine and you are doing something wrong in your code. If it doesn't work, then that means something is configured incorrectly on your server

Feel free to test the rest of the Playground files.

**Comment by vdkdamian** [comment]
@asielcabrera I saw your previous comment that you suggested to add `var access_token: String?` to fix his issue, but the access_token isn't a variable for a ParseUser in the database.

@Climbatize is also referring to a `sessionToken` which is only found in the `Session` class.

@Climbatize Any news on your contact with Back4App?

**Comment by asielcabrera** [comment]
if you declare var access token: String? in your model when it does the decode it makes the match with the data that you get from the server. I am consuming a private parse server and doing that, it returns the accessToken.

2 days ago the login function was implemented and it worked but today xcode updated the dependencies and got that error with the createdAt key

**Comment by cbaker6** [comment]
@asielcabrera you will need to open another issue. Your issue isn’t related to this one and you need to provide your info about your setup and code

**Comment by cbaker6** [comment]
I've ran through the ParseSwift Playgrounds on Parse Server 4.2.0 and didn't see the issue with signing up and not receiving a session token.

I'm closing this for now. Feel free to reopen if you find an issue pops up with the Swift SDK.

**Comment by Climbatize** [comment]
@vdkdamian No luck with Back4App, they just remain silent.
@cbaker6 no problem I'll keep you in touch

**Comment by Climbatize** [comment]
@vdkdamian @cbaker6 I finally found this issue on this one, it took me a while as I had no answer from B4A. The thing is B4A was configured by the administrator of the app I'm working ont to prevent login if email is not verified. 

So I think this case is not managed by Parse-Swift. I don't know if it should be managed, but this happens on Back4App, and that causes a parsing error instead of generating a 209

**Comment by vdkdamian** [comment]
> @vdkdamian @cbaker6 I finally found this issue on this one, it took me a while as I had no answer from B4A. The thing is B4A was configured by the administrator of the app I'm working ont to prevent login if email is not verified.
> 
> So I think this case is not managed by Parse-Swift. I don't know if it should be managed, but this happens on Back4App with Parse server option `preventLoginWithUnverifiedEmail`, and that causes a parsing error instead of generating a 209. So don't you think `sessionToken` should be optional and managed at signing time?

Well found, never used the `preventLoginWithUnverifiedEmail` option, so it's possible this is causing the issue.

**Comment by cbaker6** [comment]
I tried this on Parse Servers 4.2.0 and the 5.0.0.alpha and did not run into this problem. The user logs in fine. The settings I used on the server are: 

```javascript
verifyUserEmails: true,
  preventLoginWithUnverifiedEmail: true,
  emailAdapter: { }
```

It looks like this needs further investigation as this still seems to me to be a server config issue and not the Swift SDK.

**Comment by cbaker6** [comment]
Though I believe #332 may solve this issue, I didn't experience it while signing up or logging in. Instead I ran into while trying to debug this error and implementing `verifyPassword`.

You can see how the server tests for the issue you mentioned here: https://github.com/parse-community/parse-server/blob/4c29d4d23b67e4abaf25803fe71cae47ce1b5957/spec/VerifyUserPassword.spec.js#L356-L388
