### ISSUE TITLE
LiveQuery not working with User model

### ISSUE THREAD

**Issue by pmmlo** [parse-community/Parse-Swift#316]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description

LiveQuery subscription not working with User model.  Digging into the query object shows "Failed to get the 'some' field from optional 'event'"
- Other models have been confirmed to work in the same environment.
- User data schema types in macOS project correspond to the types set in database.

### Steps to reproduce

```
var query = User.query("objectId" == "XYZ")

struct ContentView: View {
    @ObservedObject var subscription = query.subscribe!

    var body: some View {
        VStack {

            if subscription.subscribed != nil {
                Text("Subscribed to query!")
            } else if subscription.unsubscribed != nil {
                Text("Unsubscribed from query!")
            } else if let event = subscription.event {

                //: This is how you register to receive notifications of events related to your LiveQuery.
                switch event.event {

                case .entered(let object):
                    Text("Entered with score: \(object.score)")
                case .left(let object):
                    Text("Left with score: \(object.score)")
                case .created(let object):
                    Text("Created with score: \(object.score)")
                case .updated(let object):
                    Text("Updated with score: \(object.score)")
                case .deleted(let object):
                    Text("Deleted with score: \(object.score)")
                }
            } else {
                Text("Not subscribed to a query")
            }

            Text("Update User in Parse Dashboard to see changes here:")

            Button(action: {
                try? query.unsubscribe()
            }, label: {
                Text("Unsubscribe")
                    .font(.headline)
                    .background(Color.red)
                    .foregroundColor(.white)
                    .padding()
                    .cornerRadius(20.0)
            })
            Spacer()
        }
    }
}
```

### Actual Outcome

LiveQuery socket connection is not triggered by events.

### Expected Outcome

LiveQuery events would be triggered with associated actions.

### Environment

Parse-Swift 3.1.0

Client
- Parse Swift SDK version: 3.1.0
- Xcode version: 13.2.1
- Operating system (iOS, macOS, watchOS, etc.): macOS
- Operating system version: 12.1

Server
- Parse Server version: 5.0.0-beta.6
- Operating system: Official Docker package
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Local

Database
- System (MongoDB or Postgres): Postgres
- Database version: 14.1
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Local

### Logs

No errors or logs produced in console.

**Comment by pmmlo** [comment]
User model:
```
struct User: ParseUser {
    var authData: [String : [String : String]?]?

    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
    var score: Double?

    var emailVerified: Bool?
    var username: String?
    var email: String?
    var password: String?

    var isActive: Bool? /// <-- The added column.
}
```

**Comment by cbaker6** [comment]
If it’s working with your other ParseObjects, I suspect this not something with the Swift SDK, but more on how your CLP’s are setup on your server. By default, there are restrictions on the server for querying other users. You can adjust your CLPs or other settings on the server to see if your live queries work then

**Comment by pmmlo** [comment]
That makes sense.  Will give that a try.

**Comment by pmmlo** [comment]
So, after some playing around:

1. A standard query with `find` has no problem retrieving the object(s) matching the constraints.
2. Even with a more permissive CLP (compared to the working non-User tables), event still reports `Failed to get the 'some' field from optional 'event'`
3. Also, made sure the ACLs weren't blocking.  No issues there when checking with Dashboard and looking at the queried object (though User does have an explicit ACL for the user to read/write itself).

@cbaker6 I think you are probably right in thinking this is a Server restriction more than a SDK error.  Just wanted to bring it up and see, if the community had any solutions.

**Comment by pmmlo** [comment]
After googling around, one passing thought I had is maybe the `AuthData` object is being called with a strict type, but I have no evidence other than what one random person thought `Failed to get the 'some' field from optional` means.

As an aside, I tried excluding more sensitive fields like `password` and `ACL`, but no success.  An aside, `exclude` does not seem to exclude keys with Server 5.0.0-alpha.18.

I'm stumped.  Would appreciate any other ideas.

Cheers!

**Comment by cbaker6** [comment]
> An aside, exclude does not seem to exclude keys with Server 5.0.0-alpha.18.

Exlude worked the last time I tested it in the Playgrounds (which was recently). If I remember correctly, ParseObject keys are not suppose to get excluded, but the fix on the server side is https://github.com/parse-community/parse-server/issues/7245. I recommend running the Playgrounds files, if those work, there usually isn't an issue: https://github.com/parse-community/Parse-Swift/blob/b92667fb177bbefd59fb79f05e5b1707bc7b501b/ParseSwift.playground/Pages/2%20-%20Finding%20Objects.xcplaygroundpage/Contents.swift#L147-L164

**Comment by cbaker6** [comment]
> After googling around, one passing thought I had is maybe the AuthData object is being called with a strict type, but I have no evidence other than what one random person thought Failed to get the 'some' field from optional means.

I recommend you set a breakpoint here while running your code and try to decode manually to see if you can find "some" key in there or if something looks off: https://github.com/parse-community/Parse-Swift/blob/fa1e07fde29d9c6e35f4e720355156b558f2224b/Sources/ParseSwift/LiveQuery/Subscription.swift#L77

**Comment by pmmlo** [comment]
Thanks for the replies.  @cbaker6  Let me spend some time on this and make sure it's not a bug in my local deployment.

Let me deploy a more realistic base Server and give it a try.  I should have tried it first, but just doing this on the side for myself.

**Comment by cbaker6** [comment]
I checked `exclude` in alpha.18 using Postgres and the Playgrounds and it worked for me.

**Comment by pmmlo** [comment]
@cbaker6 In terms of User livequery, I completely forgot about the prefixed underscore in the `classNames`.  Works perfectly with `_User`, not `User`

Just in case someone else makes this mistake, if you have a common express implementation of parse-server:
```
const server = new ParseServer({
  databaseURI: postgresql://foo:bar@localhost:4321
  ...
  liveQuery: {
    classNames: ["_User"]
  },
  ...
})
```

Still playing with `exclude` but considering my user error, I'm going to keep playing with it to make sure I don't have a bug somewhere.

Thanks for your help, as usual.
