### ISSUE TITLE
Response parsing error when ParseUser is login or Signup

### ISSUE THREAD

**Issue by asielcabrera** [parse-community/Parse-Swift#324]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description
When login up o Signup a User response may not contain a createdAt key. 

### Steps to reproduce

- Create a ParseUser subclass

```Swift
struct User: ParseUser {
    
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
    
    var username: String?
    var email: String?
    var emailVerified: Bool?
    var password: String?
    var authData: [String: [String: String]?]?
    
    var access_token: String?
    
}


extension User {
    init(username: String, password: String, email: String) {
        self.username = username
        self.password = password
        self.email = email
    }
}
```

- Uses one of the ParseUser methods to login 

```Swift
User.login(username: username, password: password) { result in
                switch result {
                case .failure(let err):
                    print(err)
                case .success(let user):
                    print(user)
                }
            }
```

### Actual Outcome
`
ParseError code=-1 error=Invalid struct: No value associated with key CodingKeys(stringValue: "createdAt", intValue: nil) ("createdAt").
`

### Expected Outcome
The user who has been authenticated

### Environment

Client
- Parse Swift SDK version: `3.1.2`
- Xcode version: `13.2.1`
- Operating system (iOS, macOS, watchOS, etc.): `iOS`
- Operating system version: `15.2`

Server
- Parse Server version: `4.2.0`
- Operating system: `Ubuntu`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Digital Ocean`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

### Logs
`ParseError code=-1 error=Invalid struct: No value associated with key CodingKeys(stringValue: "createdAt", intValue: nil) ("createdAt").`

**Comment by cbaker6** [comment]
You mentioned that previous versions of the SDK worked. There's no changes in `createdAt` from [3.0.0 - 3.1.2](https://github.com/parse-community/Parse-Swift/compare/3.0.0...3.1.2). Can you try 3.1.0 and 3.0.0 to verify. Can you also try the playgrounds like I mentioned in the other post.

**Comment by asielcabrera** [comment]
playgrounds: 
Successfully logged out
Error logging in: ParseError code=-1 error=Invalid struct: No value associated with key CodingKeys(stringValue: "createdAt", intValue: nil) ("createdAt").

and in the project I also changed the version and it is showing me the same error

**Comment by asielcabrera** [comment]
reviewing I have realized that the applicationId and the clientKey had changed on the server and now it has the necessary behavior.

But now my question when the app finishes loading, when does the SDK authentication. shouldn't it show some log initialize error?

**Comment by cbaker6** [comment]
You can check the health of your server using code from the playgrounds: https://github.com/parse-community/Parse-Swift/blob/054a226559ce5ec6a7a3f08d045af560c06d4861/ParseSwift.playground/Pages/1%20-%20Your%20first%20Object.xcplaygroundpage/Contents.swift#L25-L31

**Comment by cbaker6** [comment]
Closing as this was a developer configuration issue and not a Swift SDK issue.
