### ISSUE TITLE
Error with signing up 

### ISSUE THREAD

**Issue by AMSH92** [parse-community/Parse-Swift#344]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description
Whenever I try to signup a new user I get this error ( Fatal error: Error saving: ParseError code=-1 error=Invalid struct: No value associated with key CodingKeys(stringValue: "createdAt", intValue: nil) ("createdAt").)

### Steps to reproduce
Try signing up with a new user

### Actual Outcome
Fatal error: Error saving: ParseError code=-1 error=Invalid struct: No value associated with key CodingKeys(stringValue: "createdAt", intValue: nil) ("createdAt").

### Environment

Client
- Parse Swift SDK version: `4.1.0`
- Xcode version: `13.2`
- Operating system (iOS, macOS, watchOS, etc.): `iOS`
- Operating system version: `14.0`

Server
- Parse Server version: `4.5.0 - Parse Server 4.5.0`
- Operating system: `NA`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `back4app`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `NA`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `remote host back4app`

### Logs
</ParseUser.swift:72: Fatal error: Error saving: ParseError code=-1 error=Invalid struct: No value associated with key CodingKeys(stringValue: "createdAt", intValue: nil) ("createdAt").>

**Comment by cbaker6** [comment]
Can you post your `PsrseUser` struct and code used to sign up?

**Comment by AMSH92** [comment]
Hi @cbaker6 
I just found out that I am assigning my `applicationId` to the `clientKey` which was causing the issue. 
However, thank you for your fast response. :)
