### ISSUE TITLE
Repo can't push to CocoaPods

### ISSUE THREAD

**Issue by cbaker6** [parse-community/Parse-Swift#346]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description

It looks like someone changed the CocoaPods credentials recently but didn't update the settings across the repo. The [CI reports the following issue](https://github.com/parse-community/Parse-Swift/runs/5336382761?check_suite_focus=true#step:5:2926) when attempting to push a new version to CocoaPods:

```bash
"{\"error\":\"You (tfox@hey.com) are not allowed to push new versions for this pod. The owners of this pod are services@parseplatform.org.\"}"
```

### Steps to reproduce

Try to push a new release to cocoapods

### Actual Outcome

Can't create release

### Expected Outcome

To release as it was before

### Environment

GitHub actions release.yml

Client
- Parse Swift SDK version: n/a
- Xcode version: n/a
- Operating system (iOS, macOS, watchOS, etc.): n/a
- Operating system version: n/a

Server
- Parse Server version: n/a
- Operating system: n/a
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): n/a

Database
- System (MongoDB or Postgres): n/a
- Database version: n/a
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): n/a

**Comment by cbaker6** [comment]
@mtrezza it looks like the credentials have been changed for CocoaPods (see comments above), can you or someone or the Core Team update the credentials along with the required token so new versions can be pushed?

**Comment by mtrezza** [comment]
Yes, I assume this repo needs a new trunk token that is generated with the service user. Let me look into this.

**Comment by mtrezza** [comment]
@cbaker6 I updated the trunk token, can you please try.

**Comment by cbaker6** [comment]
> Does the repo code itself contain any CocoaPods user reference?

Yes, this repo produces pods here (linked to the pod badge on the readme): https://cocoapods.org/pods/ParseSwift

> Note: The update was also for Parse ObjC SDK.

I believe if you set this at the organization level of GitHub any repo that needs pods can use it. Previously we had the Swift and Objective-C repos sharing the same token so it stays fresh.

> I updated the trunk token, can you please try.

This worked and the new pod is pushed, thanks!
