### ISSUE TITLE
Update of model with required field fails

### ISSUE THREAD

**Issue by pmmlo** [parse-community/Parse-Swift#349]
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x ] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description

Very odd behavior.  Initial edit of a nil-valued field saves without error, but subsequent changes/updates to the model returns an error 142 with the required field needed.

### Steps to reproduce

1. Create a model with a required field and other customized field(s) on the server-side (e.g.  modelschema.addPointer('createdBy', '_User', { required: true }).
2. Save an object in this class with the customized field as nil.
3. Update a customized field as a mergeable object.
4. Update the customized field again and try to save.  Error occurs here consistently.  Error 142 with 'createdBy' is a required field.

Additionally, when I make the require column unrequired, there is no error.  In other words, a class with no required fields succeeds without issue.

Example:
```
struct GameScore: ParseObject {
    //: These are required by ParseObject
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
    var originalData: Data?

    //: Your own properties.
    var shots: [ShotCodable]?
    var createdBy: Pointer<User>?

    init() {}

    //: Implement your own version of merge
    func merge(with object: Self) throws -> Self {
        var updated = try mergeParse(with: object)
        if updated.shouldRestoreKey(\.shots,
                                     original: object) {
            updated.shots = object.shots
        }
        if updated.shouldRestoreKey(\.createdBy,
                                     original: object) {
            updated.createdBy = object.createdBy
        }
        return updated
    }
}

struct ShotCodable: Codable, Hashable {
    var name: String?
    var shooter: Pointer<User>?
    var score: Int?

    init(){}

    init(name: String?, shooter: Pointer<User>?, score: Int?) {
        self.name = name
        self.shooter = shooter
        self.score = score
    }
}

var gameScore = GameScore()
gameScore.createdBy = try? User.current.toPointer()
gameScore.save { result in
    switch {
    case .success(let success):
        gameScore = success
    case .failure(let error):
        print("Failed to save \(error)")
    }
}

let shot = ShotCodable(name: "Curry", shooter: try? User.current.toPointer(), score: 3)
var mergeableGameScore = gameScore.mergeable()
mergeableGameScore.shots = [shot]
mergeableGameScore.save { result in
    switch {
    case .success(let success):
        print(success)
    case .failure(let error):
        print("Failed to save \(error)")
    }
}

let anotherOne = ShotCodable(name: "Green", shooter: try? User.current.toPointer(), score: 2)
mergeableGameScore.shots?.append(anotherOne)
mergeableGameScore.save { result in
    switch {
    case .success(let success):
        print(success)
    case .failure(let error):
        print("Failed to save \(error)") // <--- Error 142 occurs here.
    }
}
```

### Actual Outcome

Error 142 with [required field] needed.

### Expected Outcome

Save success.

### Environment

Client
- Parse Swift SDK version: 4.2.0
- Xcode version: 13.3
- Operating system (iOS, macOS, watchOS, etc.): macOS
- Operating system version: 12.3

Server
- Parse Server version: 5.2.0-beta.2
- Operating system: local
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): local

Database
- System (MongoDB or Postgres): Postgres
- Database version: 14
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): local

**Comment by pmmlo** [comment]
@cbaker6 Any chance you could take a look?

It's really odd behavior.  I have no problem updating once, but on the second/subsequent updates I get an error about needing a required field.  Even if I pass the required field, I get the error.

**Comment by cbaker6** [comment]
Try changing: `var createdBy: Pointer<User>?` -> `var createdBy: User?` as this what you probably really want anyways. The SDK will handle turning `createdBy` to the proper pointer during the first save. After the initial save, you may need to `fetch` or `include` `createdBy` in your queries. `ShotCodable` should probably conform to `ParseObject` based on how you are using and `var shooter: Pointer<User>?` should be `var shooter: User?`.

Also, the code below is asynchronous and their's no guarantee the saved version of GameScore:

```swift
var gameScore = GameScore()
gameScore.createdBy = try? User.current.toPointer()
gameScore.save { result in
    switch {
    case .success(let success):
        gameScore = success
    case .failure(let error):
        print("Failed to save \(error)")
    }
}
```

Before `gameScore.mergeable()`:

```swift
let shot = ShotCodable(name: "Curry", shooter: try? User.current.toPointer(), score: 3)
var mergeableGameScore = gameScore.mergeable()
mergeableGameScore.shots = [shot]
mergeableGameScore.save { result in
    switch {
    case .success(let success):
        print(success)
    case .failure(let error):
        print("Failed to save \(error)")
    }
}
```

You can fix this by using async/await or moving the code into the first `save() { result in... }`

**Comment by pmmlo** [comment]
Yup, that was the issue.  Thanks!

**Comment by pmmlo** [comment]
I should actually be clearer just in case someone has a similar issue.  Your answer is great, but wasn't the issue.  It was apparently using `createdAt`, `updatedAt`, and `objectId` as parameters within an array object.  I suspect those are reserved, so those were not being saved.  Not sure exactly for sure, but renaming these in my local project updates the object.

Thanks for the help!

**Comment by cbaker6** [comment]
I still recommend the changes. The way your objects are setup in your question reduces the ability of Swift SDK and Parse and requires you to make extra calls to the server along with write extra code (your example). The coding footprint can be reduced significantly by following the suggested way in Playgrounds along with the ability to use include/exclude/fetch directly.
