### ISSUE TITLE
Security review of 3rd party services

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-Swift#358]
We are doing our annual security review of 3rd party services. The goal is to remove permissions of services that are no longer used in this repository's CI workflow.

Services that need to be reviewed:

- [ ] Travis CI for Open Source
- [ ] Coveralls
- [ ] StyleCI
- [ ] Travis CI
- [ ] AppVeyor
- [ ] AppVeyor CI
- [ ] CircleCI
- [ ] Code Climate
- [ ] Packagist

**Comment by cbaker6** [comment]
This repo doesn't use any of the aforementioned services.

**Comment by mtrezza** [comment]
Thanks, that was quick; if you have a minute and could take a look at the [ObjC SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX/issues/1643), that would be wonderful.
