### ISSUE TITLE
Include keys for multiple levels...

### ISSUE THREAD

**Issue by LilMoke** [parse-community/Parse-Swift#359]
I have an object that has a pointer to another object.

I know I can use .include to get the first object, but how do I get the second third object from the second?

Here is my playground code:

if let pointer = try User.current?.toPointer() {
	let friends = try Friend
		.query("userId" == pointer)
		.include("friendId")
		.include("friendId.profilePicture")
		.find()
}

I am trying to avoid iterating through each of the first level objects and doing a fetch.

**Comment by cbaker6** [comment]
The [docs](https://parseplatform.org/Parse-Swift/release/documentation/parseswift/query/includeall()) and playgrounds discuss and demonstrate how to do this: https://github.com/parse-community/Parse-Swift/blob/5307210d97dedeb88297c653b0675ff1ef920221/ParseSwift.playground/Pages/8%20-%20Pointers.xcplaygroundpage/Contents.swift#L174-L208

**Comment by LilMoke** [comment]
I dont think this answers the question.  I am unclear where this addresses Object 1 has a pointer to Object 2 and Object 2 has a pointer to Object 3.

I want to retrieve all objects from all levels at once?  The highlighted section shows IncludeAll.  I was under the impression, and have viewed, that includeAll will retrieve all the objects in a record, but not nested objects.

**Comment by cbaker6** [comment]
You should check to see if the server has that ability and if not, check the issues on parse-server [repo](https://github.com/parse-community/parse-server) for the pro's and con's of such a feature. If it turns out the server has it and the Swift SDK doesn't, you can open an issue in this repo by completing the issue template.

**Comment by cbaker6** [comment]
A comment about such behavior is on the JS SDK, https://github.com/parse-community/Parse-SDK-JS/issues/1336#issuecomment-815387797, and the SDK is acting as expected. If you want such a feature you will need to open an issue on the Parse Server and have the discussion with the Server team.
