### ISSUE TITLE
And/Or Query on ParseSwift

### ISSUE THREAD

**Issue by LilMoke** [parse-community/Parse-Swift#368]
Can someone point me to a sample of how to construct and and/or query in ParseSwift?

I have not had much success.

**Comment by cbaker6** [comment]
https://github.com/parse-community/Parse-Swift/blob/c14723a028174dc6e42367acd3a8be437c7f61e3/ParseSwift.playground/Pages/7%20-%20GeoPoint.xcplaygroundpage/Contents.swift#L223-L241

**Comment by cbaker6** [comment]
I recommend asking these type of questions on [discord](https://community.parseplatform.org/c/client-sdks/parseswift-sdk/25). We use issues on GitHub for issues with the SDK.

In addition, you will need to complete the entire issue template to have issues addressed as the template is intended to help developers provide full descriptions of their issues.
