### ISSUE TITLE
User.current not returning all variables

### ISSUE THREAD

**Issue by novemTeam** [parse-community/Parse-Swift#37]
When a user is logged in, and you request a custom key from the user, it returns `nil` even though there is a value for that user in the database.

**This is my ParseUser structure**
```
struct User: ParseUser {
            //: These are required for ParseObject
            var objectId: String?
            var createdAt: Date?
            var updatedAt: Date?
            var ACL: ParseACL?

            //: These are required for ParseUser
            var username: String?
            var email: String?
            var emailVerified: Bool?
         
            //: Custom
            var userId: String?
 }
```

**This is what I call on launch**
```
let currentUser = User.current
        print("currentUser - objectId: \(String(describing: currentUser?.objectId))")
        print("currentUser - createdAt: \(String(describing: currentUser?.createdAt))")
        print("currentUser - updatedAt: \(String(describing: currentUser?.updatedAt))")
        print("currentUser - ACL: \(String(describing: currentUser?.ACL))")
        
        print("currentUser - username: \(String(describing: currentUser?.username))")
        print("currentUser - email: \(String(describing: currentUser?.email))")
        print("currentUser - emailVerified: \(String(describing: currentUser?.emailVerified))")
        //Custom key
        print("currentUser - userId: \(String(describing: currentUser?.userId))")
```

**This is the log**
<img width="724" alt="Schermafbeelding 2020-12-20 om 00 40 06" src="https://user-images.githubusercontent.com/44820440/102701924-a5bd4080-425c-11eb-9a2e-ca1515c792ef.png">

**This is an example of 3 users in Parse database**
![Schermafbeelding 2020-12-20 om 00 46 07](https://user-images.githubusercontent.com/44820440/102701938-d8ffcf80-425c-11eb-89e1-3a2a242117ce.png)

**Comment by cbaker6** [comment]
Are you setting those custom keys from either the CloudCode or the Dashboard? If so, you need to fetch the data from your server because your local user doesn't have it and has no way to know it's been updated. What happens when you try?:

```swift
let updatedUser = try User.current?.fetch()
print(updatedUser.emailVerified)
print(updatedUser.userId)
```

If you are saving these custom values from the device itself and not seeing the values after, something else is going on. I don't see this being the case because this works in playgrounds https://github.com/parse-community/Parse-Swift/blob/e2dde15dc6d9655498521edba6d676d49de71d51/ParseSwift.playground/Pages/4%20-%20User%20-%20Continued.xcplaygroundpage/Contents.swift#L10-L41

Also, make sure you have the latest version of Parse-Swift, there was recently (12/17/20) a fix to fetch.

**Comment by cbaker6** [comment]
Update, I need to look into fetch on the current user, but I suspect you are changing the custom keys from the server as I mentioned above. In order to get that info and save it to your current user you can do the following:

```swift
var findUser = User.query()
findUser.where("objectId" == User.current!.objectId!) //Force unwrapping to be concise, but you should guard agains these

findUser.first(callbackQueue: .main) {
    result in
    switch result {
    case .success(let updatedUser):
        print("Successfully fetched latest user from ParseServer: \(updatedUser)")
        User.current = updatedUser
        print(User.current!.emailVerified!) //Will contain the latest value from the server
        print(User.current!.userId!) //Will contain the latest value from the server
    case .failure(let error):
        print("Failed to update user: \(error)")
    }
}
```

**Comment by cbaker6** [comment]
After #38 is merged, you will be able to fetch User.current or Installation.current like I mentioned earlier:

```swift
//Synchronous
let _ = try User.current?.fetch()
print(User.current?.emailVerified)
print(User.current?.userId)

//Asynchronous
User.current?.fetch { result in
    switch result {
    case .success(_):
        print("Successfully fetched updated user from ParseServer: \(User.current!)")
    case .failure(let error):
        print("Failed to fetch user: \(error)")
    }
}
```

**Comment by novemTeam** [comment]
@cbaker6 I am sorry, I indeed didn't fetch the user. I thought this happend in the background code from ParseSwift.

**Comment by cbaker6** [comment]
You should use the query block of code until the merge:

```
var findUser = User.query()
findUser.where("objectId" == User.current!.objectId!) //Force unwrapping to be concise, but you should guard agains these

findUser.first(callbackQueue: .main) {
    result in
    switch result {
    case .success(let updatedUser):
        print("Successfully fetched latest user from ParseServer: \(updatedUser)")
        User.current = updatedUser
        print(User.current!.emailVerified!) //Will contain the latest value from the server
        print(User.current!.userId!) //Will contain the latest value from the server
    case .failure(let error):
        print("Failed to update user: \(error)")
    }
}
```
