### ISSUE TITLE
Could not find module 'ParseSwift' for target 'arm64-apple-macos'

### ISSUE THREAD

**Issue by phbardon** [parse-community/Parse-Swift#379]
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description

Unable to build ParseSwift Playground downloaded.

I tried to re-install the package, and also to use Pod to install ParseSwift. I tried on MacPro (non-M1 Mac)

### Steps to reproduce

- Download an open

### Actual Outcome

Could not find module 'ParseSwift' for target 'arm64-apple-macos'; found: arm64-apple-ios, at: /Users/phbardon/Library/Developer/Xcode/DerivedData/ParseSwift_PN-bvmozlgoznalozhfpaqmtjwxeasl/Build/Intermediates.noindex/Playgrounds/Products/Debug-iphoneos/ParseSwift/ParseSwift.framework/Modules/ParseSwift.swiftmodule

### Expected Outcome

Build succeeded

#### Client MacBook Pro

![](https://www.dropbox.com/s/ubyiw4yhfyotmlf/Mac_Info-20220704170459.png?raw=1)

- Parse Swift SDK version: `4.7.0`
- Xcode version: `13.4.1 (13F100) `
- Operating system (iOS, macOS, watchOS, etc.): `MacOS`
- Operating system version: `12.4.1`

#### Client Mac Pro

![](https://www.dropbox.com/s/txv9gsfyw1idis2/Mac_Info-20220704170754.png?raw=1)

- Parse Swift SDK version: `4.7.0`
- Xcode version: `13.2.1 (13C100) `
- Operating system (iOS, macOS, watchOS, etc.): `MacOS`
- Operating system version: `12.0.1`

#### Server

- Parse Server version: `3.6.0`
- Operating system: `Unknown`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `SASHIDO`

Database
- System (MongoDB or Postgres): `Unknown`
- Database version: `Unknown`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB`

**Comment by cbaker6** [comment]
This doesn't look like a bug in the SDK, but rather your Xcode. Try cleaning your build folder and if you still see the error, close Xcode, and delete your `DerivedData`.

When running Playgrounds it's best to set the target to the `macOS` framework and build for mac. See the comments at the top of Playground file: https://github.com/parse-community/Parse-Swift/blob/b0bdf71dfe2890b44910c06382af98e17726fa96/ParseSwift.playground/Pages/1%20-%20Your%20first%20Object.xcplaygroundpage/Contents.swift#L1-L5

**Comment by phbardon** [comment]
Sorry for my mistake, I forgot to select the MacOS target! Thank you. Philippe.
