### ISSUE TITLE
GeoQuerie's withinPolygon are not working properly

### ISSUE THREAD

**Issue by alexvenom** [parse-community/Parse-Swift#380]
### Issue Description
GeoQueries running with withinPolygon constraint do not work and return error -1 (Unknown server Error) or 1 (Internal Server Error), either when used with a Polygon such as:
```
let query = City.query(withinPolygon(key: "location", polygon: myPolygon))
```

or with an array of GeoPoints such as:
```
let query = City.query(withinPolygon(key: "location", points: [geoPoint1, geoPoint2, geoPoint3, geoPoint4]))
```

### Steps to reproduce
Parse 4.5.0 running at Back4App
Parse-Swift in the latest version added to the project using SPM
Class with GeoPoint property contained in the area of Polygon or array of GeoPoints

### Actual Outcome
Parse Error either Error -1 (Unknown Server Error) or 1 (Internal Server Error)
Message from Debug Print:

```
Error querying: ParseError code=1 error=Internal server error.
```

### Expected Outcome
A list of objects contained in the current Polygon or GeoPoint Array.
Same code with same coordinates when used with the JS SDK return objects correctly.

JS SDK output:
```
{"location":{"__type":"GeoPoint","latitude":-15.79485821477289,"longitude":-47.88391074690196},"name":"Brasília","createdAt":"2022-06-20T01:53:03.809Z","updatedAt":"2022-06-20T01:53:03.809Z","objectId":"7gd45OXwIi"}
```

### Environment
Client
- Parse Swift SDK version: `4.7.0 installed via SPM`
- Xcode version: `XCode 13.3`
- Operating system (iOS, macOS, watchOS, etc.): `Mac OSX Monterey 12.3.1`
- Operating system version: `12.3.1`
- Emulator: `iOS 14.0 image`

Server
- Parse Server version: `4.5.0`
- Operating system: `Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Back4App`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Back4App`

### Logs
Error querying: ParseError code=1 error=Internal server error.

### Code to Reproduce
Assuming you have a Class called "City" which contains a property named "location" that has a valid GeoPoint contained in the Polygon or array of GeoPoints.
The code below uses an array of GeoPoints, but the behavior is the same with a Polygon.

```
private func withinPolygon_query() {
        do {
            let geoPoint1 = try ParseGeoPoint(latitude: 90.0, longitude: -180.0)
            let geoPoint2 = try ParseGeoPoint(latitude: -90.0, longitude: -180.0)
            let geoPoint3 = try ParseGeoPoint(latitude: 90.0, longitude: 180.0)
            let geoPoint4 = try ParseGeoPoint(latitude: -90.0, longitude: 180.0)
            
            let query = City.query(withinPolygon(key: "location", points: [geoPoint1, geoPoint2, geoPoint3, geoPoint4]))
            
            query.find { results in
                switch results {
                    case .success(let cities):
                        cities.forEach { (city) in
                            print("Found City with objectId \"\(city.objectId!)\"")
                        }
                    case .failure(let error):
                        print("Error querying: \(error)")
                }
            }
        } catch let error as ParseError {
            print("Failed to instantiate vertices: \(error.message)")
        } catch {
            print("Failed to instantiate vertices: \(error.localizedDescription)")
        }
    }
```

Same implementation in Node.JS using the JS SDK, which responds correctly with all objects:

```
async function run(){
    let geoPoint1 = new Parse.GeoPoint({latitude: 90.0, longitude: -180.0});
    let geoPoint2 = new Parse.GeoPoint({latitude: -90.0, longitude: -180.0});
    let geoPoint3 = new Parse.GeoPoint({latitude: 90.0, longitude: 180.0});
    let geoPoint4 = new Parse.GeoPoint({latitude: -90.0, longitude: 180.0});

    const query = new Parse.Query("City");
    query.withinPolygon("location", [geoPoint1, geoPoint2, geoPoint3, geoPoint4]);
    const results = await query.find();
    results.forEach((result) => {
        console.log(JSON.stringify(result));
    });
}
```

**Comment by cbaker6** [comment]
Thanks for reporting this will be fixed by #381
