### ISSUE TITLE
Enable queries to use caching policies

### ISSUE THREAD

**Issue by aliasad106** [parse-community/Parse-Swift#382]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).

### Current Limitation
The query does not allow me to add cachePolicy cacheThenNetwork as it was implemented there in the Parse iOS/macOS SDK. 

### Feature / Enhancement Description
When given the .cacheThenNetwork. It will first check from cache and respond and then it will load from network.

### Example Use Case
Example use case is. When I load my feeds it first shows from cache and simultaneously fetches from network and respond and it also updates the cache with new data. 

### Alternatives / Workarounds
No 

### 3rd Party References
[Parse](https://docs.parseplatform.org/ios/guide/#caching-queries)

**Comment by cbaker6** [comment]
Please complete the [issue template](https://github.com/parse-community/Parse-Swift/issues/382#issue-1303958596) in it's entirety by adding information under each header.

Caching was added in #196. You can change the default cache policy the SDK uses for your app when you initialize the SDK using `requestCachePolicy`, `cacheMemoryCapacity`, and `cacheDiskCapacity` as stated in the [documentation](https://parseplatform.org/Parse-Swift/release/documentation/parseswift/parseswift/initialize(applicationid:clientkey:masterkey:serverurl:livequeryserverurl:allowingcustomobjectids:usingtransactions:usingequalqueryconstraint:keyvaluestore:requestcachepolicy:cachememorycapacity:cachediskcapacity:migratingfromobjcsdk:deleti-97083)). Details can be found by looking at Apple's [documentation](https://developer.apple.com/documentation/foundation/url_loading_system/accessing_cached_data).

If you want to choose a different caching policy for an individual query, simply pass the caching policy option you want to your query:

```swift
let options: API.Options = [.cachePolicy(.reloadIgnoringLocalCacheData))]
let query = GameScore.query("points" > 50)
let results = try await query.find(options: options)
...
```

**Comment by cbaker6** [comment]
This is probably because the SDK uses `.POST` instead of `.GET` for queries: https://github.com/parse-community/Parse-Swift/blob/b0bd3510100f17b2c2b848f4bd6aa189b268ee30/Sources/ParseSwift/Types/Query.swift#L1271-L1447

**Comment by aliasad106** [comment]
@cbaker6 I have updated to 4.9.3 and it still doesn't show me cacheThanNetwork.
