### ISSUE TITLE
`saveAll` doesn't handle pointers

### ISSUE THREAD

**Issue by dblythy** [parse-community/Parse-Swift#387]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description

Parse Swift doesn't properly convert Parse Object to Pointers on `.saveAll`, leading to schema mismatch errors.

### Steps to reproduce

```swift
var parent = Parent()
parent.name = "name"
do {
            let response = try parent.save()
            let children = childObjects.map{ obj -> Child in
                obj.parent = response
                return obj
            }
            try children.saveAll()
            print("\n\n\n all saved")
        } catch let error {
            print(error)
        }
```

### Actual Outcome

Schema mismatch, expected Pointer<Parent> received object. Errors are not thrown using `children.first.save()`

### Expected Outcome

Objects to save.

### Environment

Client
- Parse Swift SDK version: `4.7.0`
- Xcode version: `13.4.1`
- Operating system (iOS, macOS, watchOS, etc.): `macOS`
- Operating system version: `12.2`

Server
- Parse Server version: `alpha`
- Operating system: `macos`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `localhost`

Database
- System (MongoDB or Postgres): `mongodb`

**Comment by vdkdamian** [comment]
On the latest versions of iOS 16 and macOS, saveAll is actually broken.

**Comment by cbaker6** [comment]
In your example, please add more details for your ParseObjects along with using async/await or completion blocks instead of synchronous calls

**Comment by dblythy** [comment]
You're awesome @cbaker6 👏

**Comment by cbaker6** [comment]
Thanks for reporting the issue!
