### ISSUE TITLE
Updating a saved ParseObject using save produces error

### ISSUE THREAD

**Issue by vdkdamian** [parse-community/Parse-Swift#405]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Swift SDK](https://github.com/parse-community/Parse-Swift/releases). 

### Issue Description
I am unable to upload objects using the `saveAll()` method. I get the error: `"ParseError code=105 error=Invalid field name: __type."`

This is my struct:

```
struct PGRListItem: NVMParseObject {
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
    var originalData: Data?
    
    var id: String { nvmId ?? Novem.generate_nvmId() }
    
    var userId: String?
    var nvmId: String?
    var timeStamp: Date?
    
    var deviceId: String?
    var deviceName: String?
    
    var selected: Bool?
    var shops: [Shop]?
    var brand: String?
    var priority: Int?
    var amount: Float?
    var price: [String : String]?
    
    var checkedHistory: [Date]?
    var uncheckedHistory: [Date]?
    var checkedTimes: Int?
    var uncheckedTimes: Int?
    var lastUsed: Date?
    
    init() {
        self.nvmId = Novem.generate_nvmId()
    }
}
```

Here is my code that saves the objects.

```
if let synchronizableObject = synchronizableObjects.first, synchronizableObjects.count == 1 {
    let object = try await synchronizableObject.save()
    
    self.removeSynchronizingObject(object.nvmId)
    try self.storeParseItems([object],
                             storeGroup: self.storeGroup,
                             encryption: self.encrypted ?? false,
                             fetch: .none)
    
} else {
    let results = try await synchronizableObjects.saveAll()
    try self.storeResults(results,
                          storeGroup: self.storeGroup,
                          encryption: self.encrypted ?? false)
}
```

Also might be important, if only one object needs to be saved, my code makes use of `.save()`. Multiple objects use `.saveAll()`. It's good to know that the `.save()` function never throws this error.

### Steps to reproduce
Using the saveAll() method

### Actual Outcome
`ParseError code=105 error=Invalid field name: __type.`

### Expected Outcome
No error

### Environment

Client
- Parse Swift SDK version: `4.10.0`
- Xcode version: `14.0 beta 6`
- Operating system (iOS, macOS, watchOS, etc.): `iOS, macOS`
- Operating system version: `iOS 16, macOS 13`

Server
- Parse Server version: `4.5.0`
- Operating system: `Back4app`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Back4app`

Database
- System (MongoDB or Postgres): `MongoDB `
- Database version: `3.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Back4app`

**Comment by cbaker6** [comment]
> I am unable to upload objects using the saveAll() method. I get the error: "ParseError code=105 error=Invalid field name: __type."

I'm not able to replicate your issue. Some notes:

1. You are running on Xcode 14 beta, this isn't officially supported even though I've run the full test-suite on Xcode 14 Beta 5 and 6 and it passes without issues
2. You never posted the code you are using that "actually" produces the `saveAll` error. Please update your issue with the code
1. Is there a reason for `var id: String { nvmId ?? Novem.generate_nvmId() }`? Not sure if that's causing your current issue, but you are bound to run into issues with items that require `Identifiable` based on the code you've shown so far. A `ParseObject` comes with a default implementation of `id`, 90% of use-cases should use the default implementation shown here:  https://github.com/parse-community/Parse-Swift/blob/a94ac8c95d67c82cdeca870a9aeb977882d040aa/Sources/ParseSwift/Objects/ParseObject.swift#L175-L185
1. I ran all of the code in Playgrounds in Xcode 13.4.1 and Xcode 14 Beta 6 and all of it works as expected: https://github.com/parse-community/Parse-Swift/blob/a94ac8c95d67c82cdeca870a9aeb977882d040aa/ParseSwift.playground/Pages/1%20-%20Your%20first%20Object.xcplaygroundpage/Contents.swift#L148-L252 https://github.com/parse-community/Parse-Swift/blob/a94ac8c95d67c82cdeca870a9aeb977882d040aa/ParseSwift.playground/Pages/8%20-%20Pointers.xcplaygroundpage/Contents.swift#L269-L330 https://github.com/parse-community/Parse-Swift/blob/a94ac8c95d67c82cdeca870a9aeb977882d040aa/ParseSwift.playground/Pages/12%20-%20Roles%20and%20Relations.xcplaygroundpage/Contents.swift#L282-L317

I recommend:

1. Forking the repo and running all of the `saveAll` code in Playgrounds (step 4 above) connected to your server or development server on whatever service you use to host. If this code works as expected, proceed to step 2
1. Modify the Playgrounds to a situation that represents yours. Are you able to replicate the error? If so, post all of the code
1. Try the modified code in the previous step in Xcode 13.4.1, does it still throw an issue?

**Comment by cbaker6** [comment]
In addition, I suspect:

```swift
init() {
        self.nvmId = Novem.generate_nvmId()
}
```

is related to your issue based on `"ParseError code=105 error=Invalid field name: __type."` The empty initialize should be "empty". If you want to create another initializer, place it in an extension and it should take at least one value. This is mentioned in the Documentation and `Playgrounds`:

https://github.com/parse-community/Parse-Swift/blob/a94ac8c95d67c82cdeca870a9aeb977882d040aa/ParseSwift.playground/Pages/1%20-%20Your%20first%20Object.xcplaygroundpage/Contents.swift#L55-L66

**Comment by vdkdamian** [comment]
I totally forgot I can't use custom init(). 

But my custom ID is for the exact reason as you mention. I had an issue where I needed the ID on objects that where not saved yet. 

I'll try to reform all the mess I made later today.

**Comment by vdkdamian** [comment]
I completely removed the custom init, and the custom id var. It still shows the error.

**Comment by vdkdamian** [comment]
> I recommend:
> 
> 1. Forking the repo and running all of the `saveAll` code in Playgrounds (step 6 above) connected to your server or development server on whatever service you use to host. If this code works as expected, proceed to step 2

I don't know how to connect the Playgrounds to my server. Is there a tutorial or something?

**Comment by gemiren** [comment]
I'm having the exact issue. saveAll() works for new objects (object never saved to Parse server yet) but doesn't work for modifying existing objects (object already exists on the Parse Sever). 

Below is the log from Parse Sever when saveAll() is used to save existing objects. You can see that the `body` contents wrong encoding of the object. No changed keys of the object are sent to the server.
```
verbose: REQUEST for [POST] /parse//batch: {
  "requests": [
    {
      "body": {
        "__type": "Pointer",
        "className": "TestingParseObject",
        "objectId": "38vPLCcGKA"
      },
      "method": "PUT",
      "path": "/parse/classes/TestingParseObject/38vPLCcGKA"
    }
  ],
  "transaction": false
} {"body":{"requests":[{"body":{"__type":"Pointer","className":"TestingParseObject","objectId":"38vPLCcGKA"},"method":"PUT","path":"/parse/classes/TestingParseObject/38vPLCcGKA"}],"transaction":false},"headers":{"accept":"*/*","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9","connection":"keep-alive","content-length":"204","content-type":"application/json","host":"147.182.187.161:1337","user-agent":"PodcastApp/1 CFNetwork/1390 Darwin/22.0.0","x-parse-application-id":"LUqHFAQFXnmfp6TN","x-parse-client-version":"swift4.14.1","x-parse-installation-id":"cecc6f78-72f6-49c0-8b44-2e7ce66b2b0e","x-parse-request-id":"d121c68b-49fc-488f-969b-ef75e2fa26b4","x-parse-session-token":"r:8b0b27669791b030b7d88ff289eab7a6"},"method":"POST","url":"/parse//batch"}
verbose: RESPONSE from [POST] /parse//batch: {
  "response": [
    {
      "error": {
        "code": 105,
        "error": "Invalid field name: __type."
      }
    }
  ]
} {"result":{"response":[{"error":{"code":105,"error":"Invalid field name: __type."}}]}}
```

When saving new objects with saveAll() the log from Parse Server looks like this:
```
verbose: REQUEST for [POST] /parse//batch: {
  "requests": [
    {
      "body": {
        "ACL": {
          "peYQ4RYdyp": {
            "read": true,
            "write": true
          }
        },
        "favorite": true,
        "hide": 0,
        "playedTime": 0,
      },
      "method": "POST",
      "path": "/parse/classes/TestingParseObject"
    }
  ],
  "transaction": false
}
verbose: RESPONSE from [POST] /parse//batch: {
  "response": [
    {
      "success": {
        "objectId": "38vPLCcGKA",
        "createdAt": "2022-09-30T00:50:20.327Z"
      }
    }
  ]
} {"result":{"response":[{"success":{"createdAt":"2022-09-30T00:50:20.327Z","objectId":"38vPLCcGKA"}}]}}
```
The `body` content is the object itself.

Digging into the source code, it looks the culprit is from this line https://github.com/parse-community/Parse-Swift/blob/a94ac8c95d67c82cdeca870a9aeb977882d040aa/Sources/ParseSwift/Coding/ParseEncoder.swift#L345. For existing objects the pointer encoding is send to the Parse Sever. 

For new objects, it goes to the line https://github.com/parse-community/Parse-Swift/blob/a94ac8c95d67c82cdeca870a9aeb977882d040aa/Sources/ParseSwift/Coding/ParseEncoder.swift#L353, which encodes the object itself correctly.

**Comment by vdkdamian** [comment]
Fix is working! Thanks

**Comment by bcbeta** [comment]
Since updating when I create 2 related parse objects and save one of them I get the error:
`ParseError code=111 error=schema mismatch for PFRoute.creator; expected Pointer<_User> but got Object
  - code : ParseSwift.ParseError.Code.incorrectType
  - message : "schema mismatch for PFRoute.creator; expected Pointer<_User> but got Object"`

Previously when I called save() on one of the objects it deep saved both but now I get this error.

**Comment by cbaker6** [comment]
@bcbeta can you provide the code for your objects and your call to save. It's best to edit the Playgrounds examples and make it produce the error as mentioned here: https://github.com/parse-community/Parse-Swift/issues/405#issuecomment-1238725358

**Comment by bcbeta** [comment]
Yes sorry I deleted my comment because I need to spend a little more time describing the issue. I’ll try to get to it tonight. Something with the latest update broke my apps ability to save objects.

**Comment by cbaker6** [comment]
> Something with the latest update broke my apps ability to save objects.

This is unfortunate. I ran the whole [Playgrounds suite](https://github.com/parse-community/Parse-Swift/tree/main/ParseSwift.playground/Pages) along with the CI test suite and didn't see any breaks. Feel free to open a new issue if you discover how to replicate the problem you are facing.
