### ISSUE TITLE
Allow implementations of ParseObjects to set their own className

### ISSUE THREAD

**Issue by atonylai** [parse-community/Parse-Swift#421]
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/Parse-Swift/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-Swift/issues?q=is%3Aissue).

### Current Limitation
struct extensions of ParseObject seem to force their name as the classTitle

`struct GameScore: ParseObject { ... }`

We use Stripe as another library - Stripe has a class called Event. One of the tables in our database that is heavily populated is already called Event.

### Feature / Enhancement Description
Allow extensions of ParseObject to function more like PFObject. While it's a lot of work for us to have to add in 

`struct SomeDatabaseTableName: ParseObject { ... }`

this is not impossible, albeit just a lot of boilerplate code.

### Example Use Case

```
struct RandomClassName: ParseObject { 

   var className = "ActualDatabaseClassName"

 }
```

### Alternatives / Workarounds
We could migrate the entire table into a new one and update all of the code to point to a new table, but that would still leave us at the mercy of any of our dependencies adding in a new class or struct that conflicts with ours.

### 3rd Party References

The original obj-c Parse SDK

**Comment by cbaker6** [comment]
`className` Is a computed property that has a default implementation. You can easily replace the computed property with whatever you want. This is inherent in `Protocols`. See [example](https://github.com/netreconlab/ParseCareKit/blob/main/Sources/ParseCareKit/Objects/PCKCarePlan.swift#L60) as well as [others](https://github.com/netreconlab/ParseCareKit/tree/main/Sources/ParseCareKit/Objects):

``swift

public struct PCKCarePlan: PareseObject {
    public static var className: String {
        "CarePlan"
    }

```

**Comment by atonylai** [comment]
Hi, thank you for this!

> a lot of work

So here's some sample code from our project

```
class Event {

  var PFData: PFObject!

  var available: Int
  var purchased: Int
  
  init?(with object: PFObject) {
    self.PFData = object
    
    guard let available = object[String.Event.available.rawValue] as? Int else {
      return nil
    }
    self.available = available
    
    guard let purchased = object[String.Event.purchased.rawValue] as? Int else {
      return nil
    }
    self.purchased = purchased
    
    ...
  }

  func soldOut() -> Bool {
     return purchased >= available
  }

}
```

From reading the initial docs and playground code, it seems like I can't just say 

```
  guard let someVariable = object["someString"] as? Int else { return nil }
```

or even 

anymore, without declaring

```
struct Event: ParseObject { 
  var someString: Int
}
```

and then changing it to

```
  let someVariable = Event.someString
```

with something on the order of 30 classes, and rapid changing of these classes, it seems like this is a huge amount of overhead just to add variables to a ParseObject? I'll read the evolution plan in a bit, but this is what I first gathered from looking at the docs

**Comment by atonylai** [comment]
> In your examples you are using strings as keys to access values, you are way more prone to errors compared to using properties or key paths (the Swift SDK), particularly when you have "rapid changing of these classes".

Not actually - as I stated in my original code snippet:

```
  guard let available = object[String.Event.available.rawValue] as? Int else {
      return nil
    }
```

Since we never in practice use `object["available"]` but only `object[String.Event.available.rawValue]` - this prevents errors due to mistyping.

> It's important to treat it as such. The Swift SDK doesn't derive from the Objective-C SDK.

I understand this, I was just answering your earlier comment on 

> I’m not sure what you mean by “a lot of work,”

- because the two are completely different in design philosophy and architecture, having to write a lot of wrappers for each and every database class seems... a little heavy-handed?

But again, thank you for taking the time to reply! I appreciate it.

**Comment by cbaker6** [comment]
> Since we never in practice use object["available"] but only object[String.Event.available.rawValue] - this prevents errors due to mistyping a string since the compiler will catch it.

If you really want to treat your `ParseObject`'s as dictionaries and bit use key paths, you can see my response [here](https://community.parseplatform.org/t/i-need-help-to-switch-from-parse-ios-sdk-to-parse-swift-with-a-redux-like-implementation/2962/2?u=cbaker6) as possible way.

**Comment by atonylai** [comment]
Got it! Thank you so much!!!
