### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by nebitrams** [parse-community/Parse-Swift#442]
I can see that there is very few activity on this repo.  Is this repo out of support now?  Is there any planned release?

I might need to start migrating my app back to the old iOS client library.

**Comment by mtrezza** [comment]
We are currently reviewing our general strategy for all Parse SDKs, to keep them all on the same development level and for feature parity. Hence we are currently focused on bringing the [Parse iOS SDK](https://github.com/parse-community/Parse-SDK-iOS-OSX) up-to-date, see the recent activity there.
