### ISSUE TITLE
URLSessionWebSocketTask unavailable on Linux

### ISSUE THREAD

**Issue by jt9897253** [parse-community/Parse-Swift#63]
Building this project on Linux is currently broken.

Problem is, `URLSessionWebSocketTask` is not available on Linux, not even in `FoundationNetworking`.

For reference, this is for example discussed in the swift forum: "[Is there a WebSocketTask in FoundationNetworking?](https://forums.swift.org/t/is-there-a-websockettask-in-foundationnetworking/38844)" 

Solution proposed there was using [websocket-kit](https://github.com/vapor/websocket-kit).

For now, to make my code compile locally, I added `#if !os(Linux)` in `ParseLiveQueryDelegate.swift`.

Also, it might be a good idea to add a Linux build to continuous integration to catch Linux issues more early.

**Comment by cbaker6** [comment]
Are you using version 1.0.2? https://github.com/parse-community/Parse-Swift/releases

`ParseLiveQuery` won't be available for Linux until `URLSessionWebSocketTask` is added to Swift since this SDK is intended to remain dependency free. You can see the [PR](https://github.com/parse-community/Parse-Swift/pull/59) for more details.

**Comment by jt9897253** [comment]
Did not notice that 1.0.2 was released, now it compiles.

Thanks to everyone working on this project!

**Comment by cbaker6** [comment]
@jt9897253 since you are using Swift Linux, you may know about how to access the file system using Swift. Would you be willing to take a look at this issue so Linux devs can use `ParseFile`? https://github.com/parse-community/Parse-Swift/projects/2#card-53414087

**Comment by jt9897253** [comment]
Let's see, if time permits, I can try to have a look.
