### ISSUE TITLE
SPM Broken on v1.1.0+ and branch main

### ISSUE THREAD

**Issue by pmmlo** [parse-community/Parse-Swift#68]
Today, I pulled the latest version of Parse-Swift and it crashes Xcode.  This did not happen yesterday.  It happens for versions branch main, 1.1.0 and greater.  Oddly, I thought I pulled v1.1.2 earlier but could be wrong.  Other SPM packages are pulled down without issue.

**DO NOT TEST THIS ON A PROJECT YOU CARE ABOUT.  CREATE A TEST PROJECT.  THE PROJECT GOES INTO A CRASH LOOP.**
Steps to reproduce:
1) Create new iOS app.
2) Add Parse-Swift package with versions from branch main, 1.1.0, or 1.1.2 in SPM.
3) Xcode crashes as it pulls down the library.

@cbaker6 For some reason, I thought these versions were working earlier with SPM.  Any ideas?

**Comment by cbaker6** [comment]
Thanks for reporting this. I'm not sure what the issue is yet, but I'm able to replicate it

**Comment by cbaker6** [comment]
I don't have a problem with 1.1.0. Something is up with 1.1.0...

The workaround for now is to edit your `Package.swift` in vi or nano and use `exact`:

```
.package(url: "https://github.com/parse-community/Parse-Swift", .exact("1.1.0"))
```

You should be able to double click you the Package.swift to open up your project from there.

You can always get your project open somehow, it will not destroy your project

**Comment by cbaker6** [comment]
So I have a guess, though it doesn't really make sense... SPM doesn't like the number `1.1.1`?

If you try the `encoderDocs` branch, which literally just adds comments after 1.1.1, it works fine, so:

```
.package(url: "https://github.com/parse-community/Parse-Swift", .branch("encoderDocs"))
```

**Comment by pmmlo** [comment]
> I don't have a problem with 1.1.0. Something is up with 1.1.1...
> 
> The workaround for now is to edit your `Package.swift` in vi or nano and use `exact`:
> 
> ```
> .package(url: "https://github.com/parse-community/Parse-Swift", .exact("1.1.0"))
> ```
> 
> You should be able to double click you the Package.swift to open up your project from there.
> 
> You can always get your project open somehow, it will not destroy your project

Oddly, I'm having the same issue with 1.1.0 on a fresh project with exact, using the interface.

Unfortunately, it's a catalyst project, so I don't think it has Package.swift.  But, you can go into project.pbxproj and Package.resolved to delete the references.  Starts right up.  Also, I'm an emacs guy.

Yeah, no problem at all.  Fortunately, I was just testing out some cloud code, so I didn't lose much anyways.

**Comment by cbaker6** [comment]
I think this is probably an SPM issue. Maybe it doesn't like skipping versions.

Using this line allows you to use 1.1.1 with no issue:

```
.package(url: "https://github.com/parse-community/Parse-Swift", from: "1.1.1")
```

I found some random crashes with SPM here: https://developer.apple.com/forums/thread/660678

**Comment by cbaker6** [comment]
I changed the `from` in the README to start from 1.1.1 in #67

**Comment by pmmlo** [comment]
> So I have a guess, though it doesn't really make sense... SPM doesn't like the number `1.1.1`?

I guess it's not impossible.  You never touched Package.swift.  A lot was done in the playground and tests.  I thought it might be the linter, but essentially no change there.  But, I'm wondering if SPM is not liking 

> The workaround for now is to edit your Package.swift in vi or nano and use exact:

Yeah, I'm pulling this directly without wrapping it, so I don't have a Package.swift.  I can't get it to work but am trying a couple things.  Will report back if it works.

**Comment by cbaker6** [comment]
> Yeah, I'm pulling this directly without wrapping it, so I don't have a Package.swift. I can't get it to work but am trying a couple things. Will report back if it works.

If you are using SPM directly through Xcode, delete your derived data folder. Once you open your project, go quickly yo SPM and change 1.0.0 to 1.1.1. This worked for me in 2 projects

**Comment by pmmlo** [comment]
This is a dummy project, so completely new.  I pulled each of the packages in a new project...  Definitely not working for me.

**Comment by cbaker6** [comment]
I'm not using Beta:
- Xcode 12.3 (12C33)
- macOS 10.15.6
- Mac Pro

I also tried on my MBP using macOS 11.1 and I'm getting the crash. So I'm not sure what the real problem is

**Comment by cbaker6** [comment]
Let me know if the new version works

**Comment by pmmlo** [comment]
> Let me know if the new version works

Works great!
