### ISSUE TITLE
Session expiresAt stored?

### ISSUE THREAD

**Issue by pmmlo** [parse-community/Parse-Swift#75]
@cbaker6 Does anybody know if the session `expiresAt` date is stored on login or if I need to make an additional query to 
`Session` directly or apply `become(session)`?

**Comment by cbaker6** [comment]
I’m note sure I understand your question. If you want `expiresAt`, you need conform to `ParseSession`, and query your particular session

**Comment by pmmlo** [comment]
That answers my question.  I asked because I get a fresh `sessionToken` after login through `ParseUserConform.current.sessionToken`.

Thanks!

**Comment by cbaker6** [comment]
@pmmlo are you familiar with https://community.parseplatform.org

It's a good place to get better answers (than the ones I provide) about Cloud code and server questions. Also, more people will see the Q&A and can chime in.

**Comment by pmmlo** [comment]
@cbaker6 Thanks for the suggestion.  Will look there in the future.
