### ISSUE TITLE
initialize in SwiftUI App Protocol

### ISSUE THREAD

**Issue by novemTeam** [parse-community/Parse-Swift#87]
Is it wise to initialize Parse on the mainview .onappear? 
Since there is no applicationDidFinishLaunching anymore, what is the best way to do it?

I know there is a workaround to still be able to use applicationDidFinishLaunching, but i think its not prefered.

**Comment by novemTeam** [comment]
Maybe also change the Documentation for SwiftUI App Protocol?

**Comment by cbaker6** [comment]
> Is it wise to initialize Parse on the mainview .onappear?

This might work. It depends on how your app is setup and when you begin parse calls. I personally still use AppDelegate. 

It seems even with the new SwiftUI life cycle,  people are still using App delegate for didFinishLaunching and registering for notifications https://prafullkumar77.medium.com/how-to-handle-push-notifications-in-swiftuis-new-app-lifecycle-7532c21d32d7

**Comment by novemTeam** [comment]
Thanks, I'll probably keep it in the appdelegate then.

**Comment by novemTeam** [comment]
Just a little update, I now put the Parse Initialize in the `init()` method.

**Like this:**

`@main
struct MyDemoApp: App {
    init() {
        ParseSwift.initialize(applicationId: "id", clientKey: "key", serverURL: URL(string: "url")!)
        Installation.current?.save { results in
            switch results {
            case .success(let updatedInstallation):
                print("Succesufully saved Installation to ParseServer: \(updatedInstallation)")
            case .failure(let error):
                print("Failed to update installation: \(error)")
            }
        }
    }
    var body: some Scene {
        WindowGroup {
            MainView()
        }
    }
}`

**Comment by novemTeam** [comment]
@cbaker6 Maybe add this to the documentation?

**Comment by cbaker6** [comment]
When using `Installation.current?.save` I recommend following the warning in the [documentation](http://parseplatform.org/Parse-Swift/api/Protocols/ParseInstallation.html):

> Only use ParseInstallation.current installations on the main thread as they require UIApplication for badge

You can get unexpected behavior if you don't follow the warning. It should look like:

```swift
DispatchQueue.main.async {
            Installation.save { result in ... }
}
```

> Maybe add this to the documentation?

Feel free to open a PR with your suggestions and it will be reviewed.
