### ISSUE TITLE
Question about the sync saveAll call

### ISSUE THREAD

**Issue by Vortec4800** [parse-community/Parse-Swift#95]
I noticed the `[].saveAll()` call returns Result objects, one for each item in the array, but also throws. This is a bit confusing as now there are two routes for errors to propigate. Should we expect this call to throw if there are any errors, or if all are errors? Or some other combination? I haven't had a chance to dig through the code yet, but thought there might be a standard error handling procedure it follows.

**Comment by cbaker6** [comment]
I'm assuming you are referring to a "synchronous" `saveAll`? This comment may help answer your question https://github.com/parse-community/Parse-Swift/issues/47#issuecomment-756336169

**Comment by Vortec4800** [comment]
That's right. So the try/catch error is a connection-level error, and the array of result errors are specific object-level errors?

**Comment by cbaker6** [comment]
> That's right. So the try/catch error is a connection-level error, and the array of result errors are specific object-level errors?

Yes, or the try/catch can be some other server level error not related to the particular objects.

**Comment by cbaker6** [comment]
Closing due to the question being answered and inactivity. Feel free to reopen if needed.
