### ISSUE TITLE
Custom objectId before saving

### ISSUE THREAD

**Issue by lsmilek1** [parse-community/Parse-Swift#99]
Hello,

is there a way how to set custom objectId before the object gets saved into Parse? This does not need to be for user login/sign-up, bot than later for other objects. The reason is that I am allowing user to save objects locally in the app (Realm) before they need or are synced with server, so the Id is already defined. 

After login the user I tried following object:

`struct TestParseObject: ParseObject {
    
    var objectId: String?
    var createdAt: Date?
    var updatedAt: Date?
    var ACL: ParseACL?
    var itemName: String?
    
}` 

saving with this code:

`static func testSave() {
        var testObject = TestParseObject()
        testObject.itemName = "Able"
        testObject.objectId = "EaGax1Mnym"
        testObject.save { (result) in
            print("save result: \(result)")
        }
    }`

result is:
_save result: failure(ParseSwift.ParseError(code: ParseSwift.ParseError.Code.objectNotFound, message: "Object not found."))_

If I do not change objectId, the object saves successfully.

Workaround would be to add one more field and save the other Id in that separate field, but that feels like unnecessary traffic and server load. In the custom server setting I was able to set:

`{
    "allowCustomObjectId": true
}`

And I noticed through the community that above functionality should be possible. Looking into the code description I see that there might be some wrong password also:

`/**
         Object doesn't exist, or has an incorrect password.
         */
        case objectNotFound = 101`

But the password reference is only for user object, right?

**Comment by cbaker6** [comment]
Parse-Swift current doesn't support this. If was briefly mentioned in the forums: https://community.parseplatform.org/t/cant-fetch-objects-with-pointers/1471/5?u=cbaker6

It looks like the JS SDK implemented this here: https://github.com/parse-community/Parse-SDK-JS/pull/1309. My guess is the process is similar to adding it to this SDK. If you would like to open a PR and add the functionality, I can review it.

**Comment by cbaker6** [comment]
I personally have a situation like this, but I just create another field called `uuid` (basically whatever the name of the field is in the local database). I don't cross these over when syncing to the Parse Server, I just either query for `objectId` or `uuid`.

**Comment by cbaker6** [comment]
This actually seems pretty easy to add to the SDK, I’ll see if I can find some time later on today to add it

**Comment by lsmilek1** [comment]
Great! Let me know how can I buy you a coffee!

**Comment by cbaker6** [comment]
> And I noticed through the community that above functionality should be possible. Looking into the code description I see that there might be some wrong password also:
> /** Object doesn't exist, or has an incorrect password. */ case objectNotFound = 101

Someone from the server team might have to chime (@dplewis do you have some insight?) in about this particular error. My guess is from the message, it's kind of broad and covers a few different types. Maybe after the PR you won't receive this error anymore.

> Great! Let me know how can I buy you a coffee!
Thanks for offering, I never had this setup before, but just added it to my GitHub profile.

**Comment by cbaker6** [comment]
@lsmilek1 just released [1.2.2](https://github.com/parse-community/Parse-Swift/releases) with the ability to add custom objectIds. Let us know if it works out for you.

**Comment by lsmilek1** [comment]
Hi, I am trying it now, but I might be missing some point again unfortunately. I added parameter in the init function in the`didFinishLaunchingWithOptions` function:

`ParseSwift.initialize(applicationId: "coYfuTYV3z35Z8iwv8q3NOTdGQs2ywJtt7tUUg4p",
                              clientKey: "L8PDqQEMofo44rf9XJTegf5uWGJTDhIdU0wQ87gl",
                              serverURL: URL(string: "https://parseapi.back4app.com")!,
                              allowCustomObjectId: true)`

in the first controllers `viewDidLoad` I print successfully the current user:

`Optional(_User ({"createdAt":{"__type":"Date","iso":"2021-03-21T17:55:01.092Z"},"username":"hoho","objectId":"Zf47seCdcD"}))`

and after I try to run following on the same test object as the first post:

`static func testSave() {
        var testObject = TestParseObject()
        testObject.itemName = "Able2"
        testObject.objectId = "EaGax1M111"
        testObject.save { (result) in
            print("save result: \(result)")
        }
    }`

the result is a bit longer description:

`Failure(ParseSwift.ParseError(code: ParseSwift.ParseError.Code.unknownError, message: "Error decoding parse-server response: Optional(<NSHTTPURLResponse: 0x7fce7d530760> { .... _long description_ ... with error: The data couldn’t be read because it is missing. Format: Optional(\"{\\\"message\\\":\\\"Not Found\\\",\\\"error\\\":{}}\")"))`

I double-checked and I have `"allowCustomObjectId": true` in the Custom Parse Server Options. Did I miss to set any other parameter somewhere to get it working or do I simply set the objectId at wrong place/time?

**Comment by cbaker6** [comment]
> in the first controllers viewDidLoad I print successfully the current user:
Optional(_User ({"createdAt":{"__type":"Date","iso":"2021-03-21T17:55:01.092Z"},"username":"hoho","objectId":"Zf47seCdcD"}))

Does this mean you were able to save your user with a custom objectId?

**Comment by lsmilek1** [comment]
User I did not tried to save with custom Id as this is not required by the app architecture. The user I created and logged in yesterday already

**Comment by cbaker6** [comment]
> I double-checked and I have "allowCustomObjectId": true in the Custom Parse Server Options. Did I miss to set any other parameter somewhere to get it working or do I simply set the objectId at wrong place/time?

Setting `allowCustomObjectId` on the server and in the SDK are the only places I believe you need to set. Did you reset your server after changing the setting? @dplewis do you have any insight on this? Let me know if I misinterpreted something in the save/update testcases: https://github.com/parse-community/Parse-Swift/blob/453ebdbcddf30cf3baad6bcf79fbc1fc0ba07fe2/Tests/ParseSwiftTests/ParseObjectCustomObjectId.swift#L146-L200

**Comment by lsmilek1** [comment]
In the Back4App dashboard I went to **Server Settings --> Core Setting --> Restart App** now and seems to not have any effect. I also did clean and build the project in Xcode with the updated SPM library, I forgot to mention in previous post

**Comment by cbaker6** [comment]
@lsmilek1 the problem was how I implemented this in ParseSwift. I've added a fix and test on an actual server in #101

**Comment by lsmilek1** [comment]
I can confirm this is working now. Thank you for your support!

**Comment by cbaker6** [comment]
Awesome! Let us know if you run into any other issues
